#!/usr/bin/env python3
"""lib/assemble.py (noether-symmetry draft B, "the glass box") · writes lib/arsenal.gen.js = three arsenal modules (verbatim copies in
lib/, comments and indentation stripped, demo-only blocks cut or replaced in the assembled copy only) and ../film.js = lib/film.src.js.
Deterministic: run twice, diff, identical. Inlined through film.json "libs" (chain-recipes 3B): lib/data.js (lib/prep.py) then lib/arsenal.gen.js.
Modules: gl-pointcloud (body from `const VERT` replaced by lib/pc-morph.js: per-point home coordinates, a mix knob, a lit band; F4 of the brief),
gl-camera-rig (demo scene cut, the rig kept), gl-labels (solve + projector kept, demo scene cut).
formula-bind is NOT assembled: its `product` form multiplies two counts into a grid, and distance x speed are measured values (see NOTES.md)."""
import os, re, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
MODS = ["gl-pointcloud.js", "gl-camera-rig.js", "gl-labels.js"]   # arsenal/patterns/<id>/pattern.js

def strip(src):
    out, i, n = [], 0, len(src)
    prev = ""                          # last significant char, to tell a regex literal from a division
    while i < n:
        c = src[i]; d = src[i + 1] if i + 1 < n else ""
        if c in "'\"`":
            j = i + 1
            while j < n and src[j] != c:
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1]); prev = c; i = j + 1; continue
        if c == "/" and d == "*":
            j = src.find("*/", i + 2); i = n if j < 0 else j + 2; out.append(" "); continue
        if c == "/" and d == "/":
            j = src.find("\n", i); i = n if j < 0 else j; continue
        if c == "/" and (prev == "" or prev in "(,=:[!&|?{};+-*%<>~^" or re.search(r"\breturn\s*$", "".join(out[-3:]))):
            j, cls = i + 1, False
            while j < n:
                if src[j] == "\\": j += 2; continue
                if src[j] == "[": cls = True
                elif src[j] == "]": cls = False
                elif src[j] == "/" and not cls: break
                j += 1
            j += 1
            while j < n and src[j].isalpha(): j += 1
            out.append(src[i:j]); prev = "/"; i = j; continue
        if c in " \t":
            nxt = src[i + 1] if i + 1 < n else ""
            if (out and out[-1] in (" ", "\t", "\n")) or (out and out[-1] in "{}();,=:?[]<>!&|*%") or nxt in "{}();,=:?[]<>!&|*%":
                i += 1; continue
        out.append(c)
        if not c.isspace(): prev = c
        i += 1
    lines = [l.strip() for l in "".join(out).split("\n")]
    return "\n".join(l for l in lines if l)


PC_PATCH = open(os.path.join(HERE, "pc-morph.js"), encoding="utf-8").read().rstrip("\n")

# each cut: [start regex, end regex (not cut) or None (one line), replacement?]
CUTS = {
    "gl-pointcloud.js": [
        (r"^  const VERT = `", r"^\}\)\(\);", PC_PATCH),
    ],
    "gl-camera-rig.js": [
        (r"^  /\* for a depth-of-field post", r"^  const rig = \{"),                                  # dof, sample, the knob rows: the film writes its own knobs
        (r"^  const rig = \{", None, "  const rig = { compile, at, apply, worldToScreen, basis };"),
        (r"^  /\* \u2550+ the demo scene", r"^\}\)\(\);", "  A.patterns['gl-camera-rig'] = { id: 'gl-camera-rig', renderer: 'webgl', rig };"),
    ],
    "gl-labels.js": [
        (r"^  /\* ---------- drawing: flat", r"^  /\* kit2: placements"),                               # drawGL: the film draws SVG
        (r"^  /\* ---------- the demo scene", r"^\}\)\(\);",
         "  A.patterns['gl-labels'] = { id: 'gl-labels', renderer: 'webgl', ROLES, solve, kit, project: (cam, W, H) => projector(cam, W, H) };"),
    ],
}

def cut(src, rules):
    lines = src.split("\n")
    for rule in rules:
        start, end, rep = (rule + (None,))[:3]
        i = next(k for k, l in enumerate(lines) if re.match(start, l))
        j = i + 1 if end is None else next(k for k, l in enumerate(lines) if k > i and re.match(end, l))
        lines[i:j] = ["/* [cut by lib/assemble.py: %d lines the film never calls] */" % (j - i)] + ([rep] if rep else [])
    return "\n".join(lines)

def main():
    parts = ["/* noether-symmetry draft B \u00b7 lib/arsenal.gen.js is GENERATED by lib/assemble.py from verbatim copies in lib/.\n"
             "   Modules (comment-stripped, demo blocks cut): " + ", ".join(MODS) + " */",
             "window.ARSENAL = window.ARSENAL || {}; ['patterns','structures','materials','brands','core'].forEach(function (k) { window.ARSENAL[k] = window.ARSENAL[k] || {}; });"]
    for m in MODS:
        src = open(os.path.join(HERE, m), encoding="utf-8").read()
        body = cut(src, CUTS[m]) if m in CUTS else src
        parts.append("/* \u2500\u2500 lib/%s sha256 %s%s \u2500\u2500 */\n" % (m, hashlib.sha256(src.encode()).hexdigest()[:16], " (cut)" if m in CUTS else "") + strip(body))
    lib = "\n".join(parts) + "\n"
    with open(os.path.join(HERE, "arsenal.gen.js"), "w", encoding="utf-8") as f:
        f.write(lib)
    film = "/* noether-symmetry draft B \u00b7 film.js is GENERATED by lib/assemble.py from lib/film.src.js (comments and indentation stripped); edit that. */\n" + strip(open(os.path.join(HERE, "film.src.js"), encoding="utf-8").read()) + "\n"
    with open(os.path.join(HERE, "..", "film.js"), "w", encoding="utf-8") as f:
        f.write(film)
    print("lib/arsenal.gen.js %d bytes, film.js %d bytes" % (len(lib.encode()), len(film.encode())))

if __name__ == "__main__":
    main()
