#!/usr/bin/env python3
"""lib/prep.py (noether-symmetry draft B) · packs the topic data into lib/data.js (inlined through film.json "libs").
orb: 300 x 12 int16 little-endian (Lshell, Elevel, u0 x 32767, R00..R22 x 32767) from data/orbit_table.json, base64.
netw: 3000 x 3 int8, PCA weight coordinates x 40 (a picture of the weights; step 0.025). netc: 100 x 3 int16, each run's invariant triple (c0, c1, c2) x 10000,
the mean over its 30 steps (its drift, median 0.00095, is a claim from recompute.py and is below one pixel at this scale).
netshell: 100 bytes, the run's shell 0..2."""
import json, base64, struct, os
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.join(HERE, "..", "..", "..", "..", "..", "topics", "noether-symmetry", "data")
o = json.load(open(os.path.join(TOP, "orbit_table.json")))
rows = np.array(o["rows"], dtype=np.float64)
assert rows.shape == (300, 13)
orb = rows[:, 1:].copy(); orb[:, 2:] = np.round(orb[:, 2:] * 32767); orb = orb.astype("<i2")   # Lshell, Elevel, u0 x 32767, R x 32767
n = json.load(open(os.path.join(TOP, "network.json")))
r = np.array(n["rows"], dtype=np.float64)
assert r.shape == (3000, 10) and (np.diff(r[:, 0]) >= 0).all()
w = np.round(r[:, 3:6] * 40).astype("i1")      # int8, step 0.025 (0.4 world units at the box scale)
runs = r[:, 0].astype(int)
cq = np.zeros((100, 3)); sh = np.zeros(100, dtype=np.uint8)
for k in range(100):
    m = runs == k; cq[k] = r[m, 6:9].mean(0); sh[k] = int(r[m, 1][0]); assert m.sum() == 30
cq = np.round(cq * 10000).astype("<i2")
b64 = lambda a: base64.b64encode(a.tobytes()).decode("ascii")
out = "/* noether-symmetry draft B · lib/data.js is GENERATED by lib/prep.py from factory/topics/noether-symmetry/data/ */\n"
out += "window.NOETHER_DATA = " + json.dumps({"orb": b64(orb), "netw": b64(w), "netc": b64(cq), "nets": b64(sh)}, separators=(",", ":")) + ";\n"
open(os.path.join(HERE, "data.js"), "w").write(out)
print("lib/data.js", len(out), "bytes")
