#!/usr/bin/env python3
"""noether-frontier · recompute every in-film number, and write the data the film draws.

Run:  python3 -I factory/topics/noether-frontier/recompute.py [--write]

numpy only, fixed seeds, no network. Without --write it only prints and checks (exit 1 on any failed check).
With --write it also writes data/neurons.json, data/question_tree.json, data/toy.json, data/recompute_out.json.

A. RECALL CLOUD (HOOK, CASE 12-50). Part 1's 300 orbits x 100 moments = 30,000 dots, read from
   factory/topics/noether-symmetry/data/orbit_table.json (the film rebuilds the states with the Kepler solution; nothing is
   shipped twice). Count = orbits x per_orbit.
B. BLIND SEARCH (ILLUSTRATION, CASE 28-36). Given only the states (x y z vx vy vz) of the 300 orbits and a plain library of
   22 terms (all degree-2 products of the six state variables, plus 1/r), find every combination of terms that stays constant
   along every orbit. It is NOT the Liu-Tegmark program. It shows that the picture "the machine sorts the tangle onto shells"
   is what a blind search really returns: the null space is 4-dimensional and equals span{Lx, Ly, Lz, E}.
C. TRAINING (COUNT 62-98). 60 runs of a 2-layer ReLU net, 8 hidden units, no biases, 2 inputs, 1024 seeded points, teacher of
   3 units. Per hidden unit i: a = |u_i| (input weights), b = |v_i| (output weight), c = a^2 - b^2. Scale symmetry
   (u, v) -> (s u, v / s) leaves the function unchanged, so c is conserved by gradient FLOW (Du-Hu-Lee 2018, Kunin et al. 2021);
   gradient DESCENT drifts by O(lr). Small step lr = 0.005 x 3920 steps and big step lr = 0.4 x 49 steps cover the same
   training time (T = 19.6); 50 states are recorded per unit. 60 runs x 8 units x 50 states = 24,000 dots per condition.
   Initial c levels: five layers -1, -0.5, 0, 0.5, 1 (round robin over units).
   COUNT OF LAWS. Per hidden unit one law c_i, so 8 for width 8. Checked three ways: (1) the 8 gradients of c_i are
   independent (rank 8); (2) the matrix Lie algebra generated by the model's gradient fields in the starting activation region
   (Marcotte-Gribonval-Peyre, the field of unit i at sample k is linear in theta) leaves exactly D - dim(Lie) = 8 independent
   conserved functions, for each of the 60 starting regions; (3) the same method gives r for r = 2, 3, 4. (It does NOT give
   r(r+1)/2 for this narrow net; that count needs input and output widths >= r, so no linear-net count goes on screen.)
D. TOY (ILLUSTRATION, COUNT 98-112). Three independent sub-answers (a, b, c) = (4, 7, 9); the claim is their sum. All 3! = 6
   orders give the same sum. A toy "model" that listens less to later facts (weights 1.0, 0.8, 0.6) gives 6 different answers.
   Only 3, 6, 4, 7, 9 and the sum 20 are drawn; the toy model's six values are colours, never digits.
E. THE OWNER'S COURSE (COUNT 119-135). Counts of what exists, read from /home/user/manutej/noether-operadic-course/index.html if
   present (else the stored data/question_tree.json is used and a WARN is printed): 9 modules, 19 questions in the tree
   (4 level-1, 8 level-2, 7 level-3), 22 sources. The course also has 19 wiki entries: NEVER shown (count collision).
   Writes the tree (ids, levels, parents, layout) for gl-instances.
"""
import json, os, re, sys, itertools, math
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
DATA = os.path.join(HERE, "data")
WRITE = "--write" in sys.argv
COURSE = "/home/user/manutej/noether-operadic-course/index.html"
PART1 = os.path.join(ROOT, "factory", "topics", "noether-symmetry", "data", "orbit_table.json")

SEED = 20261012
FAILS = []
OUT = {}


def check(name, ok, detail=""):
    print(("  ok    " if ok else "  FAIL  ") + name + ((" : " + detail) if detail else ""))
    if not ok:
        FAILS.append(name)


# ---------------------------------------------------------------- A. recall cloud
GM = 1.0


def kepler_states(a, e, M):
    E = M.copy()
    for _ in range(60):
        E = E - (E - e * np.sin(E) - M) / (1 - e * np.cos(E))
    x = a * (np.cos(E) - e); y = a * np.sqrt(1 - e * e) * np.sin(E)
    r = a * (1 - e * np.cos(E)); n = np.sqrt(GM / a ** 3)
    vx = -a * n * np.sin(E) / (1 - e * np.cos(E)); vy = a * n * np.sqrt(1 - e * e) * np.cos(E) / (1 - e * np.cos(E))
    z0 = np.zeros_like(x)
    return np.stack([x, y, z0], 1), np.stack([vx, vy, z0], 1)


def part_a():
    print("A. recall cloud (Part 1 orbit table)")
    t = json.load(open(PART1))
    rows, per = t["rows"], int(t["per_orbit"])
    orbits = len(rows)
    out = dict(orbits=orbits, perOrbit=per, states=orbits * per, lShells=len(t["L_levels"]), eLevels=len(t["a_levels"]))
    print("  orbits", orbits, "x moments", per, "=", out["states"], "dots")
    check("recall cloud is 300 x 100 = 30,000", orbits == 300 and per == 100 and out["states"] == 30000)
    P, V, ORB = [], [], []
    for rw in rows:
        oid, li, ai, u0 = int(rw[0]), int(rw[1]), int(rw[2]), rw[3]
        R = np.array(rw[4:13]).reshape(3, 3)
        Ur, _s, Vr = np.linalg.svd(R); R = Ur @ Vr                  # the table stores R at 6 decimals: make it exactly orthogonal
        L = t["L_levels"][li]; a = t["a_levels"][ai]
        e = math.sqrt(1 - L * L / (GM * a))
        M = (np.arange(per) + u0) / per * 2 * np.pi
        p, v = kepler_states(a, e, M)
        P.append(p @ R.T); V.append(v @ R.T); ORB.append(np.full(per, oid))
    return out, np.concatenate(P), np.concatenate(V), np.concatenate(ORB)


# ---------------------------------------------------------------- B. blind search
def part_b(P, V, ORB):
    print("B. blind search over a plain library (ILLUSTRATION, not Liu-Tegmark)")
    S = np.concatenate([P, V], 1)                               # x y z vx vy vz
    r = np.linalg.norm(P, axis=1)
    names, cols = [], []
    lab = ["x", "y", "z", "vx", "vy", "vz"]
    for i in range(6):
        for j in range(i, 6):
            names.append(lab[i] + "*" + lab[j]); cols.append(S[:, i] * S[:, j])
    names.append("1/r"); cols.append(1.0 / r)
    F = np.stack(cols, 1)
    scale = np.abs(F).max(0)
    Fn = F / scale
    # within-orbit deviation: a combination is constant along every orbit iff it is in the null space of the deviations
    dev = Fn.copy()
    for o in np.unique(ORB):
        m = ORB == o
        dev[m] -= Fn[m].mean(0)
    U, s, Vt = np.linalg.svd(dev, full_matrices=False)
    rel = s / s[0]
    k = int((rel < 1e-9).sum())
    gap = (rel[-k - 1] if k < len(rel) else float("nan"), rel[-k] if k > 0 else float("nan"))
    null = Vt[-k:] if k else np.zeros((0, F.shape[1]))
    # the truths: Lx Ly Lz E expressed in the library (normalised columns)
    idx = {n: i for i, n in enumerate(names)}
    def vec(d):
        w = np.zeros(F.shape[1])
        for n_, c in d.items(): w[idx[n_]] = c * scale[idx[n_]]
        return w
    truths = [vec({"y*vz": 1, "z*vy": -1}), vec({"z*vx": 1, "x*vz": -1}), vec({"x*vy": 1, "y*vx": -1}),
              vec({"vx*vx": .5, "vy*vy": .5, "vz*vz": .5, "1/r": -1})]
    resid = []
    for w in truths:
        w = w / np.linalg.norm(w)
        proj = null.T @ (null @ w)
        resid.append(float(np.linalg.norm(w - proj)))
    print("  library terms", len(names), "| singular values below 1e-9 (relative):", k, "| gap", "%.2e -> %.2e" % gap)
    print("  residual of Lx, Ly, Lz, E outside the found null space:", ["%.1e" % x for x in resid])
    check("blind search finds exactly 4 constants", k == 4)
    check("they are Lx, Ly, Lz and E", max(resid) < 1e-8)
    return dict(libraryTerms=len(names), blindFound=k, maxResid=max(resid))


# ---------------------------------------------------------------- C. training
R_UNITS, D_IN, N_PTS = 8, 2, 1024
RUNS, STEPS_REC = 60, 50
LR_SMALL, N_SMALL = 0.005, 3920
LR_BIG, N_BIG = 0.4, 50
LEVELS = [-1.0, -0.5, 0.0, 0.5, 1.0]


def make_task(rng):
    X = rng.normal(size=(N_PTS, D_IN))
    tw = rng.normal(size=(3, D_IN)); tv = rng.normal(size=3)
    y = np.maximum(X @ tw.T, 0) @ tv
    return X, y


def init_run(rng, k):
    c = np.array([LEVELS[(k * R_UNITS + i) % len(LEVELS)] for i in range(R_UNITS)])
    b = rng.uniform(0.4, 1.4, R_UNITS)
    b = np.sqrt(np.maximum(b ** 2, 0.06 - c))                    # keeps a^2 = c + b^2 >= 0.06
    sgn = rng.choice([-1.0, 1.0], R_UNITS)
    a = np.sqrt(c + b * b)
    ang = rng.permutation((np.arange(R_UNITS) + rng.uniform(0.15, 0.85, R_UNITS)) * 2 * np.pi / R_UNITS)   # one input direction per 45 degrees, never two alike
    u = np.stack([a * np.cos(ang), a * np.sin(ang)], 1)
    return u, b * sgn, c


def train(X, y, u, v, lr, steps, rec):
    u = u.copy(); v = v.copy(); n = len(X); out = []; loss = []
    for s in range(steps + 1):
        h = np.maximum(X @ u.T, 0); f = h @ v; e = (f - y) / n
        if s in rec:
            out.append((np.linalg.norm(u, axis=1), np.abs(v), np.sum(u * u, 1) - v * v)); loss.append(float(0.5 * np.mean((f - y) ** 2)))
        gv = h.T @ e
        gu = ((e[:, None] * (h > 0)) * v[None, :]).T @ X
        u -= lr * gu; v -= lr * gv
    return out, loss


def lie_laws(X, u, v, r, d):
    """D - dim of the matrix Lie algebra generated by the gradient fields of the model outputs, at the point (u, v), in the
    activation region of the data at (u, v). The field of the output at sample k is linear in theta, so it is a matrix
    M_k = sum_{i,j} act_ik x_kj E_ij (E_ij couples u_ij and v_i); the bracket is the commutator."""
    D = r * (d + 1)
    act = ((X @ u.T) > 0).astype(float)                           # (n, r)
    A = (act[:, :, None] * X[:, None, :]).reshape(len(X), r * d)  # coordinates of M_k in the span of the r*d matrices E_ij
    E = np.zeros((r * d, D, D))
    for i in range(r):
        for j in range(d):
            E[i * d + j, i * (d + 1) + j, i * (d + 1) + d] = 1.0
            E[i * d + j, i * (d + 1) + d, i * (d + 1) + j] = 1.0
    _, sv, Vt = np.linalg.svd(A, full_matrices=False)
    nrank = int((sv > 1e-9 * sv[0]).sum())
    gens = [np.tensordot(Vt[m], E, axes=1) for m in range(nrank)]
    basis = np.zeros((0, D * D))                                  # orthonormal rows: the algebra so far
    def add(M):
        nonlocal basis
        w = M.ravel().copy()
        for _ in range(2):
            if len(basis): w -= basis.T @ (basis @ w)
        nw = np.linalg.norm(w)
        if nw > 1e-9 * max(1.0, np.linalg.norm(M)):
            basis = np.vstack([basis, w / nw]); return True
        return False
    frontier = [g for g in gens if add(g)]
    for _ in range(12):
        new = []
        for g in gens:
            for h in frontier:
                c = g @ h - h @ g
                if np.linalg.norm(c) > 1e-9 and add(c): new.append(c)
        if not new: break
        frontier = new
    theta = np.concatenate([np.concatenate([u[i], [v[i]]]) for i in range(r)])
    cols = np.array([b_.reshape(D, D) @ theta for b_ in basis])
    rank = int(np.linalg.matrix_rank(cols, tol=1e-8)) if len(cols) else 0
    return D - rank, len(basis)


def part_c():
    print("C. training: 60 runs, 8 units, two step sizes (the same training time)")
    rng = np.random.default_rng(SEED)
    X, y = make_task(rng)
    rec_s = set(80 * k for k in range(STEPS_REC))                                           # 0 .. 3920, every 80 steps
    rec_b = set(range(STEPS_REC))                                                           # 0 .. 49
    inits = [init_run(rng, k) for k in range(RUNS)]
    small, big, laws, nbasis = [], [], [], []
    dsmall, dbig, travel, l0, l1 = [], [], [], [], []
    for k, (u, v, c) in enumerate(inits):
        os_, ls = train(X, y, u, v, LR_SMALL, N_SMALL, rec_s)
        ob, lb = train(X, y, u, v, LR_BIG, N_BIG - 1, rec_b)
        small.append(os_); big.append(ob)
        cs = np.array([o[2] for o in os_]); cb = np.array([o[2] for o in ob])
        dsmall.append(np.abs(cs - cs[0]).max(0)); dbig.append(np.abs(cb - cb[0]).max(0))
        asm = np.array([o[0] for o in os_]); bsm = np.array([o[1] for o in os_])
        travel.append(np.hypot(asm[-1] - asm[0], bsm[-1] - bsm[0]))
        l0.append(ls[0]); l1.append(ls[-1])
        nl, nb = lie_laws(X, u, v, R_UNITS, D_IN)
        laws.append(nl); nbasis.append(nb)
    dsmall = np.concatenate(dsmall); dbig = np.concatenate(dbig); travel = np.concatenate(travel)
    n_dots = RUNS * R_UNITS * len(rec_s)
    print("  dots per condition", n_dots, "| recorded steps small", len(rec_s), "big", len(rec_b))
    print("  loss first/last (median): %.3f -> %.4f" % (np.median(l0), np.median(l1)))
    print("  median unit travel in the (|u|, |v|) plane: %.3f" % np.median(travel))
    print("  c drift per unit (max over time): small step median %.5f, max %.5f | big step median %.5f, max %.5f"
          % (np.median(dsmall), dsmall.max(), np.median(dbig), dbig.max()))
    print("  independent laws from the Lie algebra, per starting region:", sorted(set(laws)), "(60 regions); algebra dims", min(nbasis), "-", max(nbasis))
    check("training dots = 60 x 8 x 50 = 24,000", n_dots == 24000 and len(rec_b) == 50)
    check("small step keeps every c within 0.02 of its start", dsmall.max() < 0.02)
    check("big step drifts at least 10x more (median)", np.median(dbig) > 10 * np.median(dsmall))
    check("big step stays on the page: median drift of c at least 0.05 (a tenth of the layer gap)", np.median(dbig) >= 0.05)
    check("both conditions stay finite", np.isfinite(dbig).all())
    check("8 laws in every one of the 60 starting regions", set(laws) == {R_UNITS}, str(sorted(set(laws))))
    # (1) independence of the 8 gradients of c_i at a random point
    u0, v0, _ = inits[0]
    J = np.zeros((R_UNITS, R_UNITS * (D_IN + 1)))
    for i in range(R_UNITS):
        J[i, i * (D_IN + 1):i * (D_IN + 1) + D_IN] = 2 * u0[i]; J[i, i * (D_IN + 1) + D_IN] = -2 * v0[i]
    rankJ = int(np.linalg.matrix_rank(J))
    check("the 8 gradients of c_i are independent (rank 8)", rankJ == R_UNITS, str(rankJ))
    # (3) the same method on r = 2, 3, 4
    rr = np.random.default_rng(SEED + 1)
    for r_ in (2, 3, 4):
        Xr = rr.normal(size=(1024, D_IN)); ur = rr.normal(size=(r_, D_IN)); vr = rr.normal(size=r_)
        nl, _nb = lie_laws(Xr, ur, vr, r_, D_IN)
        check("Lie-algebra count for width %d is %d" % (r_, r_), nl == r_, str(nl))
    # unit count for the exact claim on stage
    return dict(neurons=R_UNITS, runs=RUNS, recSteps=len(rec_s), dots=n_dots, laws=int(laws[0]), lrSmall=LR_SMALL, lrBig=LR_BIG,
                stepsSmall=N_SMALL, stepsBig=N_BIG - 1, driftSmallMedian=float(np.median(dsmall)), driftSmallMax=float(dsmall.max()),
                driftBigMedian=float(np.median(dbig)), driftBigMax=float(dbig.max()), travelMedian=float(np.median(travel)),
                lossFirst=float(np.median(l0)), lossLast=float(np.median(l1)), rankJ=rankJ), small, big, inits, rec_s


def pack_neurons(small, big, inits, rec_s):
    """Compact file for the film: int x1000, delta coded along each unit's 50 states. Unit id = run * 8 + i."""
    def arr(cond, idx):
        out = []
        for run in cond:
            for i in range(R_UNITS):
                vals = [int(round(1000 * st[idx][i])) for st in run]
                out.append([vals[0]] + [vals[k] - vals[k - 1] for k in range(1, len(vals))])
        return out
    d = dict(note="unit id = run*8 + i; a = |u| (input weights), b = |v| (output weight), x1000, first value absolute then deltas; "
                  "c(t) = a^2 - b^2; small = lr 0.005 x 3920 steps (every 80th), big = lr 0.4 x 49 steps (every step); same training time T = 19.6; 50 states each; "
                  "c0 = the unit's starting layer; follow = a unit that travels far (for the pinned dot)",
             seed=SEED, runs=RUNS, units=R_UNITS, states=STEPS_REC, levels=LEVELS,
             c0=[round(float(x), 3) for (_u, _v, c) in inits for x in c],
             smallA=arr(small, 0), smallB=arr(small, 1), bigA=arr(big, 0), bigB=arr(big, 1))
    asm = np.array([[run[-1][0][i] - run[0][0][i] for i in range(R_UNITS)] for run in small]).ravel()
    d["follow"] = int(np.argmax(np.abs(asm)))
    return d


# ---------------------------------------------------------------- D. toy
TOY = (4, 7, 9)
TOY_W = (1.0, 0.8, 0.6)


def part_d():
    print("D. toy of three independent sub-answers (ILLUSTRATION)")
    perms = list(itertools.permutations(TOY))
    sums = [sum(p) for p in perms]
    toy_model = [round(sum(w * x for w, x in zip(TOY_W, p)), 1) for p in perms]
    out = dict(questions=len(TOY), orders=len(perms), a=TOY[0], b=TOY[1], c=TOY[2], total=sums[0],
               distinctSums=len(set(sums)), distinctToyModel=len(set(toy_model)), toyModelValues=toy_model, orderList=perms)
    print("  3 questions ->", len(perms), "orders; sums", sorted(set(sums)), "; toy model values", sorted(set(toy_model)))
    check("3! = 6 orders", len(perms) == 6 == math.factorial(3))
    check("the sum is the same in all 6 orders (20)", set(sums) == {20})
    check("the toy model gives 6 different answers", len(set(toy_model)) == 6)
    out["orderList"] = [list(p) for p in perms]
    return out


# ---------------------------------------------------------------- E. the owner's course
def part_e():
    print("E. the owner's program (counts of what exists)")
    stored = os.path.join(DATA, "question_tree.json")
    if os.path.exists(COURSE):
        h = open(COURSE, encoding="utf-8").read()
        qids = re.findall(r'<span class="qid">([^<]+)</span>', h)
        titles = re.findall(r'<span class="qid">[^<]+</span>\s*([^<]+)</summary>', h)
        mods = sorted(set(re.findall(r'id="mod-(\d)"', h)))
        s = h[h.index('id="sources"'):]; s = s[:s.index("</table>")]
        n_src = len(re.findall(r"<tr>", s)) - 1
        wiki = len(re.findall(r'class="wiki-card"', h))
        thesis = len(re.findall(r'class="thesis-sec"', h))
        src = "read from " + COURSE
    elif os.path.exists(stored):
        t = json.load(open(stored))
        qids = [n["id"] for n in t["nodes"]]; titles = [n["title"] for n in t["nodes"]]
        mods = [str(i) for i in range(t["counts"]["modules"])]; n_src = t["counts"]["sources"]; wiki = t["counts"]["wikiEntriesNeverShown"]
        thesis = t["counts"]["thesisSections"]; src = "WARN: course not found, using stored data/question_tree.json"
    else:
        raise SystemExit("neither the course nor data/question_tree.json is present")
    print(" ", src)
    lvl = lambda q: 1 if q.startswith("L1-") else 2 if q.startswith("L2-") else 3
    counts = {1: 0, 2: 0, 3: 0}
    for q in qids: counts[lvl(q)] += 1
    nodes = []
    for q, ttl in zip(qids, titles):
        L = lvl(q)
        if L == 1: parent = None
        elif L == 2: parent = "L1-Q" + q[3]
        else: parent = "L2-" + q[3:].split("-")[0]
        nodes.append(dict(id=q, level=L, parent=parent, title=" ".join(ttl.split())))
    # layout: leaves left to right in document order, parents centred over their children, y by level
    kids = {}
    for n in nodes: kids.setdefault(n["parent"], []).append(n["id"])
    pos = {}
    cursor = [0.0]
    def place(nid):
        ch = kids.get(nid, [])
        if not ch:
            pos[nid] = cursor[0]; cursor[0] += 1.0
        else:
            for c_ in ch: place(c_)
            pos[nid] = sum(pos[c_] for c_ in ch) / len(ch)
    for root in kids[None]: place(root)
    lo, hi = min(pos.values()), max(pos.values())
    for n in nodes:
        n["x"] = round(2 * (pos[n["id"]] - lo) / (hi - lo) - 1, 4)
        n["y"] = {1: 1.0, 2: 0.0, 3: -1.0}[n["level"]]
        n["z"] = 0.0
        n["noetherBranch"] = n["id"] == "L1-Q2" or n["id"].startswith("L2-2") or n["id"].startswith("L3-2")
    out = dict(modules=len(mods), questions=len(qids), level1=counts[1], level2=counts[2], level3=counts[3], sources=n_src,
               thesisSections=thesis, wikiEntriesNeverShown=wiki, noetherBranchNodes=sum(n["noetherBranch"] for n in nodes))
    print("  modules", out["modules"], "| questions", out["questions"], "=", counts[1], "+", counts[2], "+", counts[3], "| sources", n_src,
          "| (never shown: wiki entries", wiki, ")")
    check("9 modules", out["modules"] == 9)
    check("19 questions = 4 + 8 + 7", (out["questions"], counts[1], counts[2], counts[3]) == (19, 4, 8, 7))
    check("22 sources", n_src == 22)
    check("the Noether branch is 7 nodes (off screen)", out["noetherBranchNodes"] == 7)
    check("wiki collision: the 19 wiki entries are never shown (rule, not a number check)", wiki == 19 and out["questions"] == 19)
    tree = dict(note="ids and titles as in the course's 'Operadic question tree'; layout is deterministic (x by leaf order, y by level); "
                     "counts are of what exists; nothing here is a measured or conserved quantity",
                counts=out, nodes=nodes)
    return out, tree


def main():
    print("noether-frontier recompute (seed %d)" % SEED)
    a, P, V, ORB = part_a()
    b = part_b(P, V, ORB)
    c, small, big, inits, rec_s = part_c()
    d = part_d()
    e, tree = part_e()
    OUT.update(A=a, B=b, C=c, D=d, E=e)
    neu = pack_neurons(small, big, inits, rec_s)
    sz = len(json.dumps(neu, separators=(",", ":")))
    print("data/neurons.json would be %.0f KB (compact)" % (sz / 1024))
    print("\nclaims table")
    print("  states", a["states"], "| liu systems 5 (published, not recomputed) | neuronDots", c["dots"], "| neurons", c["neurons"], "| laws", c["laws"],
          "| toy questions", d["questions"], "orders", d["orders"], "sum", d["total"], "| tree", e["questions"], (e["level1"], e["level2"], e["level3"]),
          "| modules", e["modules"], "| sources", e["sources"])
    if WRITE:
        os.makedirs(DATA, exist_ok=True)
        json.dump(neu, open(os.path.join(DATA, "neurons.json"), "w"), separators=(",", ":"))
        json.dump(tree, open(os.path.join(DATA, "question_tree.json"), "w"), indent=1)
        json.dump(dict(questions=d["questions"], orders=d["orders"], a=d["a"], b=d["b"], c=d["c"], total=d["total"], orderList=d["orderList"],
                       toyModelWeights=list(TOY_W), toyModelValues=d["toyModelValues"],
                       note="ILLUSTRATION. Six rows, one per order; a row's colour = the toy model's answer (never a digit); the sum is 20 in every row"),
                  open(os.path.join(DATA, "toy.json"), "w"), indent=1)
        json.dump(OUT, open(os.path.join(DATA, "recompute_out.json"), "w"), indent=1, default=float)
        print("wrote data/neurons.json, question_tree.json, toy.json, recompute_out.json")
    if FAILS:
        print("\nFAILED:", FAILS); sys.exit(1)
    print("\nall checks passed")


if __name__ == "__main__":
    main()
