/* pass-every-time draft A, the test floor · film.js is GENERATED by lib/assemble.py; edit lib/film.src.js.
   Arsenal modules inlined (comment-stripped, demo scenes cut): lib/gl-camera-rig.js, lib/gl-labels.js. */
window.ARSENAL = window.ARSENAL || {}; ['patterns','structures','materials','brands','core','post'].forEach(function (k) { window.ARSENAL[k] = window.ARSENAL[k] || {}; });
/* ── lib/gl-camera-rig.js sha256 1b4cc859ead02a78 (cut) ── */
(function(){
const A=(window.ARSENAL=window.ARSENAL||{patterns:{},structures:{},materials:{},brands:{}});
const EASE_COPY={
linear:(u)=>u,smooth:(u)=>u*u*(3 - 2*u),in:(u)=>u*u*u,out:(u)=>1 - Math.pow(1 - u,3),
inout:(u)=>(u<0.5?4*u*u*u:1 - Math.pow(-2*u + 2,3)/ 2),expo:(u)=>(u>=1?1:1 - Math.pow(2,-10*u)),
back:(u)=>1 + 2.70158*Math.pow(u - 1,3)+ 1.70158*Math.pow(u - 1,2),step:(u)=>(u>=1?1:0),
};
const EASES=()=>(A.core&&A.core.timeline&&A.core.timeline.ease)||EASE_COPY;
const EASE_NAMES=['linear','smooth','in','out','inout','expo','back','step'];
const easeOf=(name)=>EASES()[name||'inout']||EASES().inout;
function mulberry32(a){return function(){a|=0;a=(a + 0x6D2B79F5)|0;let t=Math.imul(a ^(a>>>15),1|a);t=(t + Math.imul(t ^(t>>>7),61|t))^ t;return((t ^(t>>>14))>>>0)/ 4294967296;};}
const clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x));
const lerp=(a,b,u)=>a +(b - a)*u;
const geo=(a,b,u)=>(a>0&&b>0?a*Math.pow(b / a,u):lerp(a,b,u));
const D2R=Math.PI / 180,R2D=180 / Math.PI;
const add=(a,b)=>[a[0]+ b[0],a[1]+ b[1],a[2]+ b[2]],sub=(a,b)=>[a[0]- b[0],a[1]- b[1],a[2]- b[2]];
const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s],dot=(a,b)=>a[0]*b[0]+ a[1]*b[1]+ a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]- a[2]*b[1],a[2]*b[0]- a[0]*b[2],a[0]*b[1]- a[1]*b[0]];
const len=(a)=>Math.hypot(a[0],a[1],a[2]),nrm=(a)=>{const l=len(a)||1;return[a[0]/ l,a[1]/ l,a[2]/ l];};
const mix=(a,b,u)=>[lerp(a[0],b[0],u),lerp(a[1],b[1],u),lerp(a[2],b[2],u)];
const fmt=(n)=>String(n).replace(/\B(?=(\d{3})+(?!\d))/g,',');
function basis(eye,center,up){
const z=nrm(sub(eye,center));let x=cross(up,z);
if(len(x)<1e-9)x=cross([0,0,-1],z);
x=nrm(x);return{x,y:cross(z,x),z};
}
function quatOf(B0,B1){
const R=[[0,0,0],[0,0,0],[0,0,0]];
for(const k of['x','y','z'])for(let i=0;i<3;i++)for(let j=0;j<3;j++)R[i][j]+=B1[k][i]*B0[k][j];
const tr=R[0][0]+ R[1][1]+ R[2][2];let w,x,y,z,S;
if(tr>0){S=Math.sqrt(tr + 1)*2;w=0.25*S;x=(R[2][1]- R[1][2])/ S;y=(R[0][2]- R[2][0])/ S;z=(R[1][0]- R[0][1])/ S;}
else if(R[0][0]>R[1][1]&&R[0][0]>R[2][2]){S=Math.sqrt(1 + R[0][0]- R[1][1]- R[2][2])*2;w=(R[2][1]- R[1][2])/ S;x=0.25*S;y=(R[0][1]+ R[1][0])/ S;z=(R[0][2]+ R[2][0])/ S;}
else if(R[1][1]>R[2][2]){S=Math.sqrt(1 + R[1][1]- R[0][0]- R[2][2])*2;w=(R[0][2]- R[2][0])/ S;x=(R[0][1]+ R[1][0])/ S;y=0.25*S;z=(R[1][2]+ R[2][1])/ S;}
else{S=Math.sqrt(1 + R[2][2]- R[0][0]- R[1][1])*2;w=(R[1][0]- R[0][1])/ S;x=(R[0][2]+ R[2][0])/ S;y=(R[1][2]+ R[2][1])/ S;z=0.25*S;}
return w<0?[-w,-x,-y,-z]:[w,x,y,z];
}
function rotate(v,k,a){
const c=Math.cos(a),s=Math.sin(a),kv=cross(k,v),kd=dot(k,v)*(1 - c);
return[v[0]*c + kv[0]*s + k[0]*kd,v[1]*c + kv[1]*s + k[1]*kd,v[2]*c + kv[2]*s + k[2]*kd];
}
function scalars(a,b,s){
return{fov:2*Math.atan(geo(Math.tan(a.fov / 2),Math.tan(b.fov / 2),s)),zoom:geo(a.zoom,b.zoom,s),focus:geo(a.focus,b.focus,s),aperture:lerp(a.aperture,b.aperture,s)};
}
function slerpPose(a,b,s){
const d0=len(sub(a.eye,a.center)),d1=len(sub(b.eye,b.center)),u=geo(d0,d1,s);
const l=sub(a.eye,b.eye),c=add(sub(l,a.center),b.center),cc=dot(c,c);
const d=cc>1e-6?clamp(dot(l,c)/ cc):1;
const f=mix(mix(a.eye,a.center,d),mix(b.eye,b.center,d),s);
const B0=basis(a.eye,a.center,a.up),B1=basis(b.eye,b.center,b.up),q=quatOf(B0,B1);
const half=Math.acos(clamp(q[0],-1,1)),sh=Math.sin(half);let z,y;
if(sh<1e-7){z=nrm(mix(B0.z,B1.z,s));y=nrm(mix(B0.y,B1.y,s));}
else{const k=[q[1]/ sh,q[2]/ sh,q[3]/ sh],ang=2*half*s;z=rotate(B0.z,k,ang);y=rotate(B0.y,k,ang);}
return Object.assign({eye:add(f,mul(z,d*u)),center:add(f,mul(z,(d - 1)*u)),up:y,pivot:d},scalars(a,b,s));
}
function trackPose(a,b,s){return Object.assign({eye:mix(a.eye,b.eye,s),center:mix(a.center,b.center,s),up:nrm(mix(a.up,b.up,s))},scalars(a,b,s));}
const sph=(az,el,r)=>[r*Math.cos(el)*Math.sin(az),-r*Math.sin(el),r*Math.cos(el)*Math.cos(az)];
function sphOf(eye,c){const v=sub(eye,c),r=len(v)||1;return{r,az:Math.atan2(v[0],v[2]),el:Math.asin(clamp(-v[1]/ r,-1,1))};}
function orbitPose(a,b,s,o){
const center=mix(o.c0,o.c1,s),eye=add(center,sph(o.az0 + o.daz*s,lerp(o.el0,o.el1,s),geo(o.r0,o.r1,s)));
return Object.assign({eye,center,up:a.up},scalars(a,b,s));
}
function resolveIdx(spec,scene){
const N=scene&&scene.points?scene.points.length:0;if(!N)return -1;
if(typeof spec==='number')return Math.round(clamp(spec,0,N - 1));
const ord=scene.order||scene.points.map((_,i)=>i);
if(spec==='max')return ord[0];if(spec==='min')return ord[ord.length - 1];if(spec==='median')return ord[Math.floor(ord.length / 2)];
return -1;
}
function resolvePt(spec,scene){
if(Array.isArray(spec))return spec.slice(0,3);
const i=resolveIdx(spec,scene);return i<0?null:scene.points[i].slice(0,3);
}
const depthOf=(pt,pose)=>dot(sub(pt,pose.eye),nrm(sub(pose.center,pose.eye)));
const SCHEME={orbit:'orbit',crane:'track',cut:'cut',dolly:'slerp',lookat:'slerp',focus:'slerp',key:'slerp'};
function endPose(P,m,scene){
const Q={eye:P.eye.slice(),center:P.center.slice(),up:P.up.slice(),fov:P.fov,zoom:P.zoom,focus:P.focus,aperture:P.aperture};
let orbit=null,target=null;
if(m.move==='orbit'){
const c1=m.around!=null?resolvePt(m.around,scene)||P.center:P.center,o=sphOf(P.eye,P.center);
const el1=m.el!=null?clamp(m.el,-89,89)*D2R:o.el,r1=o.r*(m.r==null?1:m.r);
orbit={c0:P.center.slice(),c1,az0:o.az,daz:(m.az||0)*D2R,el0:o.el,el1,r0:o.r,r1};
Q.center=c1.slice();Q.eye=add(c1,sph(o.az + orbit.daz,el1,r1));
}else if(m.move==='dolly'){
const dir=nrm(sub(P.eye,P.center)),d0=len(sub(P.eye,P.center)),d1=m.dist!=null?m.dist:d0*(m.factor==null?1:m.factor);
Q.eye=add(P.center,mul(dir,d1));
if(m.vertigo)Q.fov=2*Math.atan(Math.tan(P.fov / 2)*d0 / d1);
}else if(m.move==='crane'){
const rise=m.rise||0,fol=m.follow==null?0:m.follow;
Q.eye=add(P.eye,[0,-rise,0]);Q.center=add(P.center,[0,-rise*fol,0]);
}else if(m.move==='lookat'){
target=resolvePt(m.target,scene);if(!target)throw new Error('gl-camera-rig: lookat ' + m.id + ' has no target');
Q.center=target.slice();
if(m.dist)Q.eye=add(target,mul(nrm(sub(P.eye,target)),m.dist));
}else if(m.move==='focus'){
const pt=m.target!=null?resolvePt(m.target,scene):null;target=pt;
Q.focus=pt?Math.max(1,depthOf(pt,P)):m.dist!=null?m.dist:P.focus;
}else if(m.move==='key'||m.move==='cut'){
if(m.eye)Q.eye=m.eye.slice();if(m.center)Q.center=m.center.slice();if(m.up)Q.up=m.up.slice();
}else throw new Error('gl-camera-rig: unknown move ' + m.move);
if(m.fov!=null&&!m.vertigo)Q.fov=m.fov*D2R;
if(m.zoom!=null)Q.zoom=m.zoom;
if(m.aperture!=null)Q.aperture=m.aperture;
if(m.move!=='focus'){
const f=m.focus;
if(f==null||f==='center')Q.focus=len(sub(Q.eye,Q.center));
else if(typeof f==='number')Q.focus=f;
else if(f!=='hold'){const pt=resolvePt(f,scene);if(pt)Q.focus=Math.max(1,depthOf(pt,Q));}
}
return{Q,orbit,target};
}
function compile(script,scene){
const s0=script.start||{},eye=(s0.eye||[0,0,800]).slice(),center=(s0.center||[0,0,0]).slice();
const P0={eye,center,up:(s0.up||[0,1,0]).slice(),fov:(s0.fov==null?45:s0.fov)*D2R,zoom:s0.zoom==null?1:s0.zoom,
aperture:s0.aperture==null?0:s0.aperture,focus:typeof s0.focus==='number'?s0.focus:len(sub(eye,center))};
if(s0.focusAt!=null){const pt=resolvePt(s0.focusAt,scene);if(pt)P0.focus=Math.max(1,depthOf(pt,P0));}
const moves=(script.moves||[]).map((m,i)=>Object.assign({id:m.move +(i + 1),ease:'inout'},m))
.map((m)=>Object.assign(m,{t1:m.move==='cut'?m.t0:m.t1})).sort((a,b)=>a.t0 - b.t0);
const ids=new Set();
moves.forEach((m,i)=>{
if(ids.has(m.id))throw new Error('gl-camera-rig: move id ' + m.id + ' twice');ids.add(m.id);
if(!(m.t1>=m.t0))throw new Error('gl-camera-rig: move ' + m.id + ' ends before it starts');
if(i&&m.t0<moves[i - 1].t1 - 1e-9)throw new Error('gl-camera-rig: move ' + m.id + ' overlaps ' + moves[i - 1].id);
});
const keys=[Object.assign({t:0,move:'start',id:'start'},P0)];
let P=P0;
for(const m of moves){
const{Q,orbit,target}=endPose(P,m,scene);
keys.push(Object.assign({t:m.t1,t0:m.t0,move:m.move,id:m.id,ease:m.ease,scheme:SCHEME[m.move],orbit,target},Q));
P=Q;
}
return Object.freeze({script,proj:script.proj||'persp',dur:script.dur||12,near:script.near||10,far:script.far||9000,moves,keys});
}
function at(rig,t){
const K=rig.keys,M=rig.moves;let i=-1;
for(let j=0;j<M.length;j++){if(t>=M[j].t0)i=j;else break;}
const meta=(pose,k,u,s)=>Object.assign(pose,{proj:rig.proj,i:k,move:K[k + 1]?K[k + 1].move:'hold',id:K[k + 1]?K[k + 1].id:'',u,s,active:u>0&&u<1});
const copy=(k)=>{const q=K[k];return{eye:q.eye.slice(),center:q.center.slice(),up:q.up.slice(),fov:q.fov,zoom:q.zoom,focus:q.focus,aperture:q.aperture};};
if(i<0)return meta(copy(0),-1,0,0);
const m=M[i],a=K[i],b=K[i + 1];
if(t>=m.t1)return meta(copy(i + 1),i,1,1);
const u=(t - m.t0)/(m.t1 - m.t0),s=easeOf(m.ease)(u);
const pose=b.scheme==='orbit'?orbitPose(a,b,s,b.orbit):b.scheme==='track'?trackPose(a,b,s):b.scheme==='cut'?copy(i + 1):slerpPose(a,b,s);
return meta(pose,i,u,s);
}
function apply(p,cam,pose,rig){
const W=p.width,H=p.height;
cam.camera(pose.eye[0],pose.eye[1],pose.eye[2],pose.center[0],pose.center[1],pose.center[2],pose.up[0],pose.up[1],pose.up[2]);
if(rig.proj==='ortho'){const z=pose.zoom||1;cam.ortho(-W / 2 / z,W / 2 / z,-H / 2 / z,H / 2 / z,0,rig.far);}
else cam.perspective(pose.fov,W / H,rig.near,rig.far);
return cam;
}
function worldToScreen(pose,pt,W,H){
const B=basis(pose.eye,pose.center,pose.up),v=sub(pt,pose.eye);
const cx=dot(v,B.x),cy=dot(v,B.y),depth=-dot(v,B.z);
let x,y;
if(pose.proj==='ortho'){const z=pose.zoom||1;x=W / 2 + cx*z;y=H / 2 + cy*z;}
else{const f=1 / Math.tan(pose.fov / 2);x=W / 2*(1 +(f*H / W)*cx / depth);y=H / 2*(1 + f*cy / depth);}
return{x,y,depth,on:depth>0&&x>=0&&x<=W&&y>=0&&y<=H};
}
function pxPerUnit(pose,depth,H){return pose.proj==='ortho'?pose.zoom||1:(H / 2)/(Math.tan(pose.fov / 2)*Math.max(depth,1e-6));}
function dof(pose,rig){
const n=rig.near,f=rig.far,z=pose.focus;
const buf=rig.proj==='ortho'?clamp(z / f):clamp((f /(f - n))*(1 - n / z));
return{focus:z,aperture:pose.aperture,near:n,far:f,focusDepth01:buf,proj:rig.proj};
}
function sample(rig,n){const out=[];for(let k=0;k<=n;k++){const t=rig.dur*k / n,q=at(rig,t);out.push({t,eye:q.eye,center:q.center});}return out;}
const cap=(s)=>String(s).replace(/[^A-Za-z0-9]+(.)?/g,(_,c)=>(c?c.toUpperCase():'')).replace(/^./,(c)=>c.toUpperCase());
const XYZ=['X','Y','Z'],COORD=[-6000,6000];
const SPEC={
t0:[null,0.1,'start (s)'],t1:[null,0.1,'end (s)'],ease:[EASE_NAMES,null,'ease (arsenal/core/timeline curves)'],
az:[[-720,720],5,'degrees swept round the centre'],el:[[-10,89],1,'end elevation (deg above the centre)'],r:[[0.2,5],0.05,'end radius as a factor of the start'],
dist:[[0,6000],10,'distance to the centre / target (world units; lookat 0 = pan from the eye)'],factor:[[0.05,20],0.05,'distance factor'],
vertigo:[[false,true],null,'dolly zoom: fov compensates so the subject keeps its size'],
rise:[[-3000,3000],10,'eye rise (world units, + = up)'],follow:[[0,1],0.05,'how much of the rise the aim follows (0 = keep the subject)'],
target:[null,1,'data index the camera aims or focuses at'],focusAt:[null,1,'data index the start focus sits on'],aperture:[[0,1],0.05,'focus blur strength (0 = all sharp)'],
focus:[[1,8000],10,'focus distance (world units)'],fov:[[5,120],1,'vertical field of view (deg)'],zoom:[[0.1,10],0.05,'ortho magnification'],
eye:[COORD,10,'eye'],center:[COORD,10,'aim point'],
};
function rows(script,scene,opts){
const pre=(opts&&opts.prefix)||'cam',dur=script.dur||12,N=scene&&scene.points?scene.points.length:0,out=[];
const row=(obj,key,idx,base,label)=>{
const sp=SPEC[key];if(!sp)return;
let v=idx==null?obj[key]:obj[key][idx];
const name=pre + cap(base)+ cap(key)+(idx==null?'':XYZ[idx]);
const r={name,obj,key,idx,step:sp[1],what:label + ': ' + sp[2]+(idx==null?'':' ' + 'xyz'[idx])};
if(key==='t0'||key==='t1')r.range=[0,dur];
else if(key==='target'||key==='focusAt'){const i=resolveIdx(v,scene);if(i<0)return;v=i;r.range=[0,Math.max(0,N - 1)];r.resolved=true;}
else if(key==='focus'&&typeof v!=='number')return;
else if(sp[0]&&typeof sp[0][0]==='number')r.range=sp[0].slice();else r.options=sp[0].slice();
if(r.range){if(typeof v!=='number')return;r.range=[Math.min(r.range[0],v),Math.max(r.range[1],v)];}
r.value=v;out.push(r);
};
const s0=script.start||{};
for(const k of['eye','center'])if(s0[k])for(let j=0;j<3;j++)row(s0,k,j,'start','start pose');
for(const k of['fov','zoom','aperture','focus'])if(s0[k]!=null)row(s0,k,null,'start','start pose');
if(s0.focusAt!=null)row(s0,'focusAt',null,'start','start pose');
(script.moves||[]).forEach((m,i)=>{
const id=m.id||m.move +(i + 1),lab=id + ' (' + m.move + ')';
for(const k of['t0','t1','ease'])if(m[k]!=null||k==='ease'){if(m.move==='cut'&&k==='t1')continue;if(m[k]==null)m[k]='inout';row(m,k,null,id,lab);}
for(const k in m)if(!['id','move','t0','t1','ease','up','around'].includes(k)){
if(Array.isArray(m[k])&&(k==='eye'||k==='center'))for(let j=0;j<3;j++)row(m,k,j,id,lab);
else if(!Array.isArray(m[k]))row(m,k,null,id,lab);
}
});
return out;
}
const clone=(o)=>JSON.parse(JSON.stringify(o));
function toKnobs(script,scene,opts){
const R=rows(clone(script),scene,opts),knobs={},knobs_doc=[];
for(const r of R){
knobs[r.name]=r.value;
const d={name:r.name};if(r.range)d.range=r.range;else d.options=r.options;
if(r.step!=null)d.step=r.step;d.what='camera rig · ' + r.what;knobs_doc.push(d);
}
return{knobs,knobs_doc};
}
function fromKnobs(script,knobs,scene,opts){
const out=clone(script);if(!knobs)return out;
for(const r of rows(out,scene,opts)){
let v=typeof knobs==='function'?knobs(r.name,r.value):knobs[r.name];
if(v===undefined)continue;
if(r.range){if(typeof v!=='number'||!isFinite(v))continue;v=clamp(v,r.range[0],r.range[1]);if(r.key==='target'||r.key==='focusAt')v=Math.round(v);}
else if(!r.options.includes(v))continue;
if(r.idx==null)r.obj[r.key]=v;else r.obj[r.key][r.idx]=v;
}
return out;
}
const rig={compile,at,apply,worldToScreen,pxPerUnit,dof,sample,toKnobs,fromKnobs,rows,basis,slerpPose,eases:EASE_NAMES};
A.patterns['gl-camera-rig']={id:'gl-camera-rig',renderer:'webgl',rig};
})();
/* ── lib/gl-labels.js sha256 3832b197f432f712 (cut) ── */
(function(){
const A=(window.ARSENAL=window.ARSENAL||{patterns:{},structures:{},materials:{},brands:{}});
function mulberry32(a){return function(){a|=0;a=(a + 0x6D2B79F5)|0;let t=Math.imul(a ^(a>>>15),1|a);t=(t + Math.imul(t ^(t>>>7),61|t))^ t;return((t ^(t>>>14))>>>0)/ 4294967296;};}
const clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x));
const smooth=(x)=>{x=clamp(x);return x*x*x*(x*(x*6 - 15)+ 10);};
const lerp=(a,b,u)=>a +(b - a)*u;
const fmt=(n)=>String(n).replace(/\B(?=(\d{3})+(?!\d))/g,',');
const sub=(a,b)=>[a[0]- b[0],a[1]- b[1],a[2]- b[2]];
const dot=(a,b)=>a[0]*b[0]+ a[1]*b[1]+ a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]- a[2]*b[1],a[2]*b[0]- a[0]*b[2],a[0]*b[1]- a[1]*b[0]];
const nrm=(a)=>{const l=Math.hypot(a[0],a[1],a[2])||1;return[a[0]/ l,a[1]/ l,a[2]/ l];};
const ROLES={
result:{size:28,fam:'disp',color:'accent',data:'must-read',sub:'secondary'},
secondary:{size:14,fam:'mono',color:'ink',data:'secondary',sub:'chrome'},
chrome:{size:12,fam:'mono',color:'muted',data:'chrome',sub:'chrome'},
};
const DIRS=[[1,-1],[-1,-1],[1,1],[-1,1],[1,0],[-1,0],[0,-1],[0,1]];
const MULT=[1,2.2,3.4];
const DEF={w:960,h:540,fps:30,hold:8,window:0,leader:20,margin:14,pad:3,dot:3.5,occlusion:true,avoidDots:true,
reserve:[],occluders:null,near:1,maxShown:Infinity,callout:null,measure:null};
function camOf(camera,t){
let c=typeof camera==='function'?camera(t):camera;
if(c&&c.eyeX!=null)c={eye:[c.eyeX,c.eyeY,c.eyeZ],look:[c.centerX,c.centerY,c.centerZ],up:[c.upX,c.upY,c.upZ],fov:c.cameraFOV,aspect:c.aspectRatio};
return c;
}
function basis(c){
const z=nrm(sub(c.eye,c.look)),x=nrm(cross(c.up||[0,1,0],z)),y=cross(z,x);
return{z,x,y};
}
function projector(c,W,H){
const B=basis(c),asp=c.aspect||W / H;
if(c.ortho!=null){
const s=c.ortho||1;
return(P)=>{const r=sub(P,c.eye),xc=dot(r,B.x),yc=dot(r,B.y),d=-dot(r,B.z);return[(1 + xc /(W / 2*s))/ 2*W,(1 + yc /(H / 2*s))/ 2*H,d];};
}
const f=1 / Math.tan((c.fov||0.8)/ 2);
return(P)=>{const r=sub(P,c.eye),xc=dot(r,B.x),yc=dot(r,B.y),d=-dot(r,B.z);return d<=1e-6?[NaN,NaN,d]:[(1 + f / asp*xc / d)/ 2*W,(1 + f*yc / d)/ 2*H,d];};
}
function occludedBy(c,B,P,occ){
const o=c.ortho!=null?(()=>{const d=-dot(sub(P,c.eye),B.z);return[P[0]+ B.z[0]*d,P[1]+ B.z[1]*d,P[2]+ B.z[2]*d];})():c.eye;
const dv=sub(P,o);
for(let i=0;i<occ.length;i++){
const b=occ[i];let t0=0,t1=1 - 1e-3,hit=true;
for(let a=0;a<3;a++){
if(Math.abs(dv[a])<1e-12){if(o[a]<b.min[a]||o[a]>b.max[a]){hit=false;break;}continue;}
let u0=(b.min[a]- o[a])/ dv[a],u1=(b.max[a]- o[a])/ dv[a];if(u0>u1){const s=u0;u0=u1;u1=s;}
if(u0>t0)t0=u0;if(u1<t1)t1=u1;if(t0>t1){hit=false;break;}
}
if(hit)return i;
}
return -1;
}
function styleOf(a,o){
const r=ROLES[a.role]||ROLES.secondary,rs=ROLES[r.sub];
const size=Math.max(r.size,a.size||0),fam=a.fam||r.fam;
const m=o.measure||((s,z,f)=>s.length*z*(f==='disp'?0.46:0.6));
const w1=m(String(a.text),size,fam),w2=a.sub?m(String(a.sub),rs.size,rs.fam):0;
const cap=size*(fam==='disp'?0.74:0.72),h2=a.sub?rs.size*1.25:0,p=o.pad;
return{size,fam,color:a.color||r.color,dataRole:r.data,subSize:rs.size,subFam:rs.fam,subDataRole:rs.data,
w:Math.max(w1,w2)+ 2*p,h:cap + h2 + 2*p,cap,p};
}
function candBox(ax,ay,s,c,L){
const d=DIRS[c%8],m=MULT[Math.floor(c / 8)],k=d[0]&&d[1]?0.72:1,ex=ax + d[0]*L*m*k,ey=ay + d[1]*L*m*k;
const x0=d[0]>0?ex:d[0]<0?ex - s.w:ex - s.w / 2,y0=d[1]>0?ey:d[1]<0?ey - s.h:ey - s.h / 2;
return{x0,y0,x1:x0 + s.w,y1:y0 + s.h,ex,ey};
}
const hit=(a,b)=>a.x0<b.x1&&a.x1>b.x0&&a.y0<b.y1&&a.y1>b.y0;
const free=(b,occ)=>{for(let i=0;i<occ.length;i++)if(hit(b,occ[i]))return false;return true;};
function segHit(x0,y0,x1,y1,r){
let u0=0,u1=1;const dx=x1 - x0,dy=y1 - y0;
for(const[pp,q]of[[-dx,x0 - r.x0],[dx,r.x1 - x0],[-dy,y0 - r.y0],[dy,r.y1 - y0]]){
if(Math.abs(pp)<1e-12){if(q<0)return false;continue;}
const u=q / pp;if(pp<0){if(u>u1)return false;if(u>u0)u0=u;}else{if(u<u0)return false;if(u<u1)u1=u;}
}
return u0<u1;
}
const leadFree=(ax,ay,b,occ,from,leads)=>{
for(let i=from;i<occ.length;i++)if(segHit(ax,ay,b.ex,b.ey,occ[i]))return false;
for(let i=0;i<leads.length;i++)if(segHit(leads[i][0],leads[i][1],leads[i][2],leads[i][3],b))return false;
return true;
};
function frame(t,camera,anchors,o){
const c=camOf(camera,t),W=o.w,H=o.h,pr=projector(c,W,H),B=basis(c);
const list=typeof anchors==='function'?anchors(t):anchors,n=list.length,P=new Array(n);
for(let i=0;i<n;i++){
const a=list[i],q=pr([a.x,a.y,a.z]);
const off=!(q[2]>o.near)||!(q[0]>=0&&q[0]<=W&&q[1]>=0&&q[1]<=H);
const oc=!off&&o.occlusion&&o.occluders&&o.occluders.length?occludedBy(c,B,[a.x,a.y,a.z],o.occluders):-1;
P[i]={i,a,x:q[0],y:q[1],depth:q[2],off,occ:oc>=0,occBy:oc};
}
return{t,c,P};
}
function calloutAt(t,o){
const S=o.callout&&o.callout.schedule;if(!S||!S.length)return null;
let j=-1;for(let i=0;i<S.length;i++)if(S[i].t<=t + 1e-9)j=i;
if(j<0)return null;
const e=S[j];return e.id==null?null:{seg:j,t0:e.t,id:e.id,text:e.text,sub:e.sub,role:e.role||'result',size:e.size||o.callout.size||32,color:e.color||o.callout.color};
}
function makeOcc(o){
const M=o.margin,occ=[{x0:-1e5,y0:-1e5,x1:1e5,y1:M},{x0:-1e5,y0:o.h - M,x1:1e5,y1:1e5},{x0:-1e5,y0:-1e5,x1:M,y1:1e5},{x0:o.w - M,y0:-1e5,x1:1e5,y1:1e5}];
for(const r of o.reserve||[])occ.push({x0:r[0],y0:r[1],x1:r[2],y1:r[3]});
return occ;
}
const dotBox=(x,y,r)=>({x0:x - r,y0:y - r,x1:x + r,y1:y + r});
function greedy(F,order,o,styles,prefs,force,L,extraOcc){
const occ=makeOcc(o).concat(extraOcc||[]),res=new Map(),r=o.dot + 1,leads=[],NM=4 +(o.reserve||[]).length;
let shown=0;
for(const i of order){
const q=F.P[i],s=styles[i];
if(shown>=o.maxShown){res.set(i,{placed:false,why:'cap'});continue;}
const db=dotBox(q.x,q.y,r);
if(!free(db,occ)&&!force(i)){res.set(i,{placed:false,why:'dot'});continue;}
let got=-1,bx=null;
for(const c of prefs(i)){const b=candBox(q.x,q.y,s,c,L(i));if(free(b,occ)&&!hit(b,db)&&leadFree(q.x,q.y,b,occ,NM,leads)){got=c;bx=b;break;}}
let overlap=false;
if(got<0){if(!force(i)){res.set(i,{placed:false,why:'blocked'});continue;}got=prefs(i)[0];bx=candBox(q.x,q.y,s,got,L(i));overlap=true;}
occ.push(bx);if(o.avoidDots)occ.push(db);leads.push([q.x,q.y,bx.ex,bx.ey]);shown++;
res.set(i,{placed:true,c:got,box:bx,overlap});
}
return res;
}
const PREF=Array.from({length:DIRS.length*MULT.length},(_,i)=>i);
function orderOf(F,idx){
return idx.slice().sort((a,b)=>(F.P[b].a.priority||0)-(F.P[a].a.priority||0)||a - b);
}
function rawSample(k,camera,anchors,o,styles,coStyle,prev){
const t=k / o.fps,F=frame(t,camera,anchors,o),n=F.P.length,co=calloutAt(t,o);
const coIdx=co?F.P.findIndex((q)=>q.a.id===co.id):-1;
let extra=[],coRes=null;
if(coIdx>=0&&!F.P[coIdx].off){
const st=coStyle(co,F.P[coIdx].a),sty=styles.slice();sty[coIdx]=st;
const pc=prev&&prev.co&&prev.co.seg===co.seg?prev.co.c:-1;
const r=greedy(F,[coIdx],o,sty,()=>stick(pc),()=>true,()=>(o.callout.leader||52),[]).get(coIdx);
coRes={ok:true,c:r.c,seg:co.seg};extra=[r.box,dotBox(F.P[coIdx].x,F.P[coIdx].y,o.dot + 1)];
}
const idx=[];for(let i=0;i<n;i++)if(i!==coIdx&&!F.P[i].off&&!F.P[i].occ)idx.push(i);
const g=greedy(F,orderOf(F,idx),o,styles,(i)=>stick(prev?prev.cs[i]:-1),()=>false,()=>o.leader,extra);
const ok=new Uint8Array(n),cs=new Int8Array(n).fill(-1),why=new Array(n);
for(let i=0;i<n;i++){const q=F.P[i];why[i]=i===coIdx?'callout':q.off?'off':q.occ?'occluded':'blocked';}
for(const[i,r]of g){if(r.placed){ok[i]=1;cs[i]=r.c;why[i]='shown';}else why[i]=r.why==='dot'?'blocked':r.why;}
return{ok,cs,why,co:coRes};
}
function schmitt(i,k0,hold,get){
let k=k0,v=get(k).ok[i];
for(;;){
let len=0;while(k>=0&&get(k).ok[i]===v){len++;k--;}
if(len>=hold||k<0)return v;
v=get(k).ok[i];
}
}
const STICK=PREF.map((c)=>[c].concat(PREF.filter((x)=>x!==c)));
const stick=(c)=>(c>=0?STICK[c]:PREF);
function debounce(vals,hold,reachesStart,fallback){
let i=0;const n=vals.length;
while(i<n){
let j=i;while(j<n&&vals[j]===vals[i])j++;
if(j - i>=hold||(j===n&&reachesStart))return vals[i];
i=j;
}
return fallback;
}
const MEMO=new WeakMap();
function memoFor(anchors,camera,o){
let m1=MEMO.get(anchors);if(!m1)MEMO.set(anchors,(m1=new WeakMap()));
const ck=typeof camera==='object'||typeof camera==='function'?camera:null;
let m2=ck?m1.get(ck):null;if(!m2){m2=new Map();if(ck)m1.set(ck,m2);}
const key=JSON.stringify([o.w,o.h,o.fps,o.leader,o.margin,o.pad,o.dot,o.occlusion,o.avoidDots,o.reserve,o.near,o.maxShown,o.callout,o.sticky,o.occluders?o.occluders.length:0,o.measureKey||'']);
let m3=m2.get(key);if(!m3){m3=new Map();m2.set(key,m3);}
if(m3.size>40000)m3.clear();
return m3;
}
function solve(t,camera,anchors,opts){
const o=Object.assign({},DEF,opts||{}),list0=typeof anchors==='function'?anchors(t):anchors,n=list0.length;
const styles=list0.map((a)=>styleOf(a,o));
const coStyle=(co,a)=>styleOf({text:co.text!=null?co.text:a.text,sub:co.sub!=null?co.sub:a.sub,role:co.role,size:co.size,color:co.color},o);
const hold=Math.max(0,o.hold|0),M=o.window||Math.max(1,4*hold),memo=memoFor(anchors,camera,o),chain=o.sticky!=='window';
const k0=Math.floor(t*o.fps + 1e-6),co=calloutAt(t,o);
const raw=(k)=>{
let r=memo.get(k);if(r)return r;
if(!chain){r=rawSample(k,camera,anchors,o,styles,coStyle,null);memo.set(k,r);return r;}
let j=k;while(j>0&&!memo.has(j - 1))j--;
for(let m=j;m<=k;m++)memo.set(m,rawSample(m,camera,anchors,o,styles,coStyle,m>0?memo.get(m - 1):null));
return memo.get(k);
};
const ks=[];for(let k=k0;k>k0 - M&&k>=0;k--)ks.push(k);
const reachesStart=ks[ks.length - 1]===0;
const R=hold?ks.map(raw):[raw(k0)];
const vis=new Uint8Array(n),cand=new Int8Array(n).fill(0);
for(let i=0;i<n;i++){
if(chain&&hold){vis[i]=schmitt(i,k0,hold,(k)=>memo.get(k)||raw(k));}
else{const v=R.map((r)=>r.ok[i]);vis[i]=hold?debounce(v,hold,reachesStart,0):v[0];}
const cs=R.map((r)=>r.cs[i]).filter((c)=>c>=0);cand[i]=cs.length?(chain||!hold?cs[0]:debounce(cs,hold,true,cs[0])):0;
}
const F=frame(t,camera,anchors,o),out=[],extra=[];
let coIdx=-1;
if(co){
coIdx=F.P.findIndex((q)=>q.a.id===co.id);
if(coIdx>=0&&!F.P[coIdx].off){
const kc=Math.ceil(co.t0*o.fps - 1e-6),seg=R.filter((r,j)=>ks[j]>=kc&&r.co&&r.co.seg===co.seg).map((r)=>r.co.c);
const c0=seg.length?seg[0]:0,st=coStyle(co,F.P[coIdx].a),sty=styles.slice();sty[coIdx]=st;
const r=greedy(F,[coIdx],o,sty,()=>[c0].concat(PREF.filter((c)=>c!==c0)),()=>true,()=>(o.callout.leader||52),[]).get(coIdx);
extra.push(r.box,dotBox(F.P[coIdx].x,F.P[coIdx].y,o.dot + 1));
out.push(place(F.P[coIdx],st,r,true,co));
}else coIdx=-1;
}
const inc=[];for(let i=0;i<n;i++)if(i!==coIdx&&vis[i]&&!F.P[i].off&&(!co||F.P[i].a.id!==co.id))inc.push(i);
const g=greedy(F,orderOf(F,inc),o,styles,(i)=>[cand[i]].concat(PREF.filter((c)=>c!==cand[i])),()=>true,()=>o.leader,extra);
const placed=[];for(const i of orderOf(F,inc)){const r=g.get(i);if(r&&r.placed)placed.push(place(F.P[i],styles[i],r,false,null));}
out.splice(0,0,...placed.reverse());
const last=raw(k0),cnt={total:n,onscreen:0,occluded:0,shown:out.length,crowded:0,overlap:out.filter((q)=>q.overlap).length,callout:co&&coIdx>=0?co.id:null};
for(let i=0;i<n;i++){const q=F.P[i];if(q.off)continue;cnt.onscreen++;if(q.occ)cnt.occluded++;}
cnt.crowded=Math.max(0,cnt.onscreen - cnt.occluded - cnt.shown);
return{t,placements:out,counts:cnt,why:last.why};
}
function place(q,s,r,isCallout,co){
const a=q.a,b=r.box,d=DIRS[r.c%8],right=d[0]<0;
const text=isCallout&&co.text!=null?co.text:a.text,sb=isCallout&&co.sub!=null?co.sub:a.sub;
const tx=right?b.x1 - s.p:d[0]===0?(b.x0 + b.x1)/ 2:b.x0 + s.p,align=right?'right':d[0]===0?'center':'left';
return{id:a.id,text:String(text),sub:sb!=null?String(sb):null,role:isCallout?co.role:(a.role||'secondary'),
dataRole:s.dataRole,subDataRole:s.subDataRole,size:s.size,fam:s.fam,subSize:s.subSize,subFam:s.subFam,color:s.color,
ax:q.x,ay:q.y,depth:q.depth,occluded:q.occ,box:[b.x0,b.y0,b.x1,b.y1],lead:[q.x,q.y,b.ex,b.ey],cand:r.c,
tx,ty:b.y0 + s.p + s.cap,sy:b.y0 + s.p + s.cap + s.subSize*1.15,align,overlap:!!r.overlap,callout:!!isCallout};
}
function drawGL(p,placements,tk,fonts,hud,look){
look=Object.assign({plate:0.78,leadW:1.25},look||{});
p.push();p.resetMatrix();p.resetShader();p.noLights();if(hud)p.setCamera(hud);p.drawingContext.clear(p.drawingContext.DEPTH_BUFFER_BIT);
const ox=-p.width / 2,oy=-p.height / 2,col=(r)=>tk.color[r]||tk.color.ink;
for(const q of placements){
const c=p.color(col(q.color));
if(look.plate>0){const pc=p.color(tk.color.bg);pc.setAlpha(255*look.plate);p.noStroke();p.fill(pc);p.rect(q.box[0]+ ox,q.box[1]+ oy,q.box[2]- q.box[0],q.box[3]- q.box[1]);}
p.stroke(c);p.strokeWeight(q.callout?1.6:look.leadW);p.line(q.lead[0]+ ox,q.lead[1]+ oy,q.lead[2]+ ox,q.lead[3]+ oy);
p.noStroke();p.fill(c);p.circle(q.ax + ox,q.ay + oy,q.callout?8:6);
if(q.occluded&&q.callout){p.fill(tk.color.bg);p.circle(q.ax + ox,q.ay + oy,4);}
text(p,q.text,q.tx,q.ty,q.size,c,fonts[q.fam]||fonts.disp,q.align,ox,oy);
if(q.sub)text(p,q.sub,q.tx,q.sy,q.subSize,p.color(tk.color.muted),fonts[q.subFam]||fonts.mono,q.align,ox,oy);
}
p.pop();
}
function text(p,s,x,y,size,c,font,al,ox,oy){
if(!font)return;p.noStroke();p.fill(c);p.textFont(font);p.textSize(size);p.textAlign(p.LEFT,p.BASELINE);
const w=p.textWidth(s),x0=al==='right'?x - w:al==='center'?x - w / 2:x;p.text(s,x0 + ox,y + oy,2000);
}
function kit(K,placements,layer){
layer=layer||'labels';const C=K.ROLES||{};
placements.forEach((q,j)=>{
const key='gll.' + q.id +(q.callout?'.co':'');
K.ln(key + '.l',layer,q.lead[0],q.lead[1],q.lead[2],q.lead[3],{stroke:C[q.color]||C.ink,w:q.callout?1.6:1.25});
K.tx(key + '.t',layer,q.tx,q.ty,q.text,{fam:q.fam,size:q.size,anchor:q.align==='right'?'end':q.align==='center'?'middle':'start',fill:C[q.color]||C.ink,role:q.dataRole});
if(q.sub)K.tx(key + '.s',layer,q.tx,q.sy,q.sub,{fam:q.subFam,size:q.subSize,anchor:q.align==='right'?'end':q.align==='center'?'middle':'start',fill:C.muted,role:q.subDataRole});
});
}
A.patterns['gl-labels']={id:'gl-labels',renderer:'webgl',ROLES,solve,drawGL,kit,project:(cam,W,H)=>projector(cam,W,H)};
})();
/* pass-every-time · draft A "the test floor" · lib/film.src.js (the film; ../film.js is GENERATED by lib/assemble.py)
   115 tasks x 4 tries as a flat field of cubes seen from above, lit 60 % (CASE). One clock: render(t) draws frame t from t alone.
   The camera lowers to the side and the SAME 460 cubes re-stack into one column per task (M1, plan to side); the columns re-sort
   by passes (M2); a cut plane rises to the all-four bar and only the 44 fully lit columns stay bright (M3); then 296 PRs
   re-partition into merged / not merged (M4) and the horizon is two columns of minutes (27 and 289). No simulated eight-try
   readout is drawn (brief, director's choices): the paper's own eight-try sentence is a caption and one attributed plate.
   Brand: midnight-ink via the film-local copy <draft>/brand.midnight-ink.json (Newsreader 600 display, DM Mono numbers).
   Chain (narrowed, see NOTES.md): gl-camera-rig (every camera key, a script compiled from knobs) + gl-labels (every pin and the
   hard-cut callout, solved in screen space). The cubes are this film's own baked geometry with TWO-THREE homes per cube (as
   gl-stack-city does: the module gl-instances has no second layout, and 1,187 marks need no instancing); the cut plane follows
   gl-volume's rule (it dims, never removes; the count snaps to a column edge) but is drawn here.
   Every tunable is a knob (film.json knobs_doc). Every digit is a film.json param that is a claim value. */
(function () {
'use strict';
const F = window.FILM, P = F.params, A = window.ARSENAL;
const RIG = A.patterns['gl-camera-rig'].rig, GLL = A.patterns['gl-labels'];
const KN = {};
(F.knobs_doc || []).forEach((d) => { KN[d.name] = window.KIT.knob(d.name, undefined); });

const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
const seg = (t, a, b) => clamp((t - a) / Math.max(1e-6, b - a));
const sm = (x) => { x = clamp(x); return x * x * x * (x * (x * 6 - 15) + 10); };
const lerp = (a, b, u) => a + (b - a) * u;
const win = (t, a0, a1, b0, b1) => sm(seg(t, a0, a1)) * (1 - sm(seg(t, b0, b1)));   // in a0..a1, out b0..b1
const D2R = Math.PI / 180;
const pc1 = (v) => v.toFixed(1) + ' %';

/* ── world (y is down in p5: a cube stands at negative y). One cube edge E, pitch PC, a task tile 2 x 2 cubes ── */
const E = KN.cubeEdge, PC = E * (1 + KN.cubeGap), TH = 0.14 * E, TW = 2 * PC + 0.12 * E, TP = 2 * PC + KN.tileGap * E;
const NT = P.tasks, COLS = KN.gridCols, ROWS = Math.ceil(NT / COLS), HW = COLS * TP / 2, HD = ROWS * TP / 2;
const PRC = KN.prCols, PRR = Math.ceil(P.prs / PRC), BW = KN.barCols, ZP = KN.prZ, XM = KN.minX;
const CTAU = [0, -5, KN.camLookZ], CSIDE = [0, -5, KN.camSideLookZ];
const CPR = [0, -2, ZP + KN.camPrLookZ];
const CMIN = [XM, -KN.camMinLookY, 0];
const sph = (c, az, el, r) => [c[0] + r * Math.cos(el * D2R) * Math.sin(az * D2R), c[1] - r * Math.sin(el * D2R), c[2] + r * Math.cos(el * D2R) * Math.cos(az * D2R)];

/* ── data: per-task outcomes of the four published trials (bit s = try s passed); counts are asserted against the claims ── */
const TR = P.trial, bits = (m) => [m & 1, (m >> 1) & 1, (m >> 2) & 1, (m >> 3) & 1];
const QS = TR.map((m) => bits(m).reduce((a, b) => a + b, 0));
{
  const hist = [0, 0, 0, 0, 0]; QS.forEach((q) => hist[q]++);
  if (TR.length !== NT || hist.join() !== [P.n0, P.n1, P.n2, P.n3, P.n4].join() || QS.reduce((a, b) => a + b, 0) !== P.passed || NT * P.triesPer !== P.tries)
    throw new Error('pass-every-time: trial table disagrees with the claims ' + hist.join('/'));
}
const ORDER = TR.map((_, i) => i).sort((a, b) => QS[b] - QS[a] || a - b);   // M2: passes 4,3,2,1,0, stable by task id
const SRANK = []; ORDER.forEach((id, j) => { SRANK[id] = j; });
const posId = (i) => [(i % COLS - (COLS - 1) / 2) * TP, (Math.floor(i / COLS) - (ROWS - 1) / 2) * TP];
/* M2 layout (tier-2 revision): one band per number of tries passed (4, 3, 2, 1, 0) left to right, each band SR columns deep and
   filled front to back, an aisle between bands; with SR = 11 the 44 full columns are one 4 x 11 block of their own */
const SR = KN.sortRows, AIS = KN.sortAisle * TP, SD = SR * TP / 2, SLOT = [];
let SW = 0;
{
  const live = [4, 3, 2, 1, 0].map((q) => QS.filter((x) => x === q).length).filter((n) => n > 0);
  const NS = live.reduce((a, n) => a + Math.ceil(n / SR), 0), WT = NS * TP + (live.length - 1) * AIS;
  let j = 0, s0 = 0, bi = 0;
  for (const n of live) { for (let k = 0; k < n; k++) SLOT[j++] = [-WT / 2 + TP / 2 + (s0 + Math.floor(k / SR)) * TP + bi * AIS, ((SR - 1) / 2 - (k % SR)) * TP]; s0 += Math.ceil(n / SR); bi++; }
  SW = WT / 2;
}
const posSorted = (j) => SLOT[j];
const topY = -(TH + 3 * PC + E);                                              // top face of a four-cube column
const colTop = (id, sorted) => { const q = sorted ? posSorted(SRANK[id]) : posId(id); return [q[0], topY, q[1] + 0.0]; };

/* ── the baked geometry: kind 0 tile · 1 tau cube · 2 PR cube · 3 minute (27) · 4 minute (289) ── */
let GEO = null, SH = null, CAM = null, RIGC = null, CAMFN = null, NCUBE = 0;
const KINDN = [0, 0, 0, 0, 0];
function bake(p, K) {
  const R = [], rn = K.mulberry32(KN.seedLit), rk = K.mulberry32(KN.seedLit + 11), rs = K.mulberry32(KN.seedMerge);
  const litRank = K.shuffle(Array.from({ length: P.passed }, (_, i) => i), KN.seedLit);    // seeded order the passes light in
  let li = 0;
  const col = TR.map(() => rk());
  for (let i = 0; i < NT; i++) {
    const a = posId(i), c = posSorted(SRANK[i]);
    R.push({ kind: 0, cls: 3, ar: i / NT, lr: -1, A: [a[0], -TH / 2, a[1]], B: [a[0], -TH / 2, a[1]], C: [c[0], -TH / 2, c[1]], q: QS[i], st: 0, side: 0, rn: col[i] });
  }
  for (let i = 0; i < NT; i++) {
    const b = bits(TR[i]), a = posId(i), c = posSorted(SRANK[i]); let nl = 0, nu = 0;
    for (let s = 0; s < 4; s++) {
      const slot = b[s] ? nl++ : QS[i] + nu++;
      const y = -(TH + slot * PC + E / 2);
      R.push({ kind: 1, cls: b[s] ? 1 : 0, ar: (i + s / 4) / NT, lr: b[s] ? (litRank[li++] + 0.5) / P.passed : 2,
        A: [a[0] + (s % 2 - 0.5) * PC, -(TH + E / 2), a[1] + (Math.floor(s / 2) - 0.5) * PC], B: [a[0], y, a[1]], C: [c[0], y, c[1]], q: QS[i], st: slot / 3, side: 0, rn: col[i] });
    }
  }
  const side = K.shuffle(Array.from({ length: P.prs }, (_, i) => (i < P.prs / 2 ? 0 : 1)), KN.seedMerge), cnt = [0, 0], hg = KN.prGap * PC / 2;
  for (let i = 0; i < P.prs; i++) {
    const c = i % PRC, r = Math.floor(i / PRC), s = side[i], k = cnt[s]++, c2 = k % PRC, r2 = Math.floor(k / PRC), half = PRR / 2;
    const z2 = s === 0 ? -(hg + PC / 2 + (half - 1 - r2) * PC) : (hg + PC / 2 + r2 * PC);
    R.push({ kind: 2, cls: 1, ar: i / P.prs, lr: -1, A: [(c - (PRC - 1) / 2) * PC, -E / 2, ZP + (r - (PRR - 1) / 2) * PC],
      B: [(c2 - (PRC - 1) / 2) * PC, -E / 2, ZP + z2], C: [0, 0, 0], q: 9, st: rs() * 0 + (c + r) / (PRC + PRR), side: s, rn: rn() });
  }
  const bar = (n, k, cx, cls) => { for (let i = 0; i < n; i++) { const a = [cx + (i % BW - (BW - 1) / 2) * PC, -(E / 2 + Math.floor(i / BW) * PC), 0];
    R.push({ kind: k, cls, ar: i / n, lr: -1, A: a, B: a, C: a, q: 9, st: 0, side: 0, rn: 0 }); } };
  const bx = (BW * PC + KN.barGap * PC) / 2;
  bar(P.h80, 3, XM - bx, 1); bar(P.h50, 4, XM + bx, 2);
  NCUBE = R.length; R.forEach((r) => { KINDN[r.kind]++; });
  // five faces per cube (the bottom is never seen), homes and data as per-vertex properties (the technique of gl-stack-city)
  const FACES = [[[0, -1, 0], [[-1, -1, -1], [1, -1, -1], [1, -1, 1], [-1, -1, 1]]], [[0, 0, 1], [[-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1]]],
    [[0, 0, -1], [[1, -1, -1], [-1, -1, -1], [-1, 1, -1], [1, 1, -1]]], [[1, 0, 0], [[1, -1, 1], [1, -1, -1], [1, 1, -1], [1, 1, 1]]], [[-1, 0, 0], [[-1, -1, -1], [-1, -1, 1], [-1, 1, 1], [-1, 1, -1]]]];
  const N = R.length, V = N * 20, vs = new Array(V), ns = new Array(V), faces = new Array(N * 10);
  const aA = new Float32Array(V * 3), aB = new Float32Array(V * 3), aC = new Float32Array(V * 3), aI = new Float32Array(V * 4), aJ = new Float32Array(V * 4);
  const nv = FACES.map((f) => new p5.Vector(...f[0]));
  let v = 0, f = 0;
  for (let i = 0; i < N; i++) {
    const b = R[i];
    for (let q = 0; q < 5; q++) {
      const base = v;
      for (const cr of FACES[q][1]) {
        vs[v] = new p5.Vector(cr[0] * 0.5, cr[1] * 0.5, cr[2] * 0.5); ns[v] = nv[q];
        aA.set(b.A, v * 3); aB.set(b.B, v * 3); aC.set(b.C, v * 3);
        aI[v * 4] = b.kind; aI[v * 4 + 1] = b.cls; aI[v * 4 + 2] = b.ar; aI[v * 4 + 3] = b.lr;
        aJ[v * 4] = b.q; aJ[v * 4 + 1] = b.st; aJ[v * 4 + 2] = b.side; aJ[v * 4 + 3] = b.rn;
        v++;
      }
      faces[f++] = [base, base + 1, base + 2]; faces[f++] = [base, base + 2, base + 3];
    }
  }
  const geo = new p5.Geometry(1, 1);
  geo.vertices = vs; geo.vertexNormals = ns; geo.faces = faces;
  const prop = (name, arr, size) => { geo._userVertexPropertyHelper(name, [], size); geo[name + 'Src'] = Array.from(arr); };
  prop('aA', aA, 3); prop('aB', aB, 3); prop('aC', aC, 3); prop('aInfo', aI, 4); prop('aInfo2', aJ, 4);
  geo.gid = 'pass-every-time-cubes';
  return geo;
}

const VERT = `precision highp float;
attribute vec3 aPosition; attribute vec3 aNormal; attribute vec3 aA; attribute vec3 aB; attribute vec3 aC; attribute vec4 aInfo; attribute vec4 aInfo2;
uniform mat4 uModelViewMatrix; uniform mat4 uProjectionMatrix;
uniform float uArr[5]; uniform float uMa[5]; uniform float uMb[5]; uniform float uBk[5]; uniform vec3 uSz[5]; uniform vec3 uCol[20]; uniform vec3 uBg;
uniform float uArrW, uDrop, uLift, uLift2, uStag, uLitP, uCut, uCutDim, uGhost, uGlobal;
varying vec3 vCol;
float ez(float u){ return u * u * u * (u * (u * 6.0 - 15.0) + 10.0); }
void main(){
  int kind = int(aInfo.x + 0.5);
  float a = clamp((uArr[kind] - aInfo.z) / uArrW, 0.0, 1.0);
  float u1 = clamp(uMa[kind] * (1.0 + uStag) - aInfo2.y * uStag, 0.0, 1.0);
  float u2 = clamp(uMb[kind] * (1.0 + uStag) - aInfo2.w * uStag, 0.0, 1.0);
  float u3 = clamp(uBk[kind] * (1.0 + uStag) - aInfo2.w * uStag, 0.0, 1.0);
  vec3 c = mix(mix(mix(aA, aB, ez(u1)), aC, ez(u2)), aA, ez(u3));
  c.y -= sin(3.14159265 * u1) * uLift + (sin(3.14159265 * u2) + sin(3.14159265 * u3)) * uLift2 * (0.4 + 0.6 * aInfo2.w) + (1.0 - a) * (1.0 - a) * uDrop;
  vec3 pos = c + aPosition * uSz[kind] * (0.35 + 0.65 * a);
  int fi = aNormal.y < -0.5 ? 0 : (aNormal.z > 0.5 ? 1 : (aNormal.z < -0.5 ? 2 : (aNormal.x > 0.5 ? 3 : 4)));
  float cls = aInfo.y;
  if (kind == 1 && cls > 0.5) cls = step(aInfo.w, uLitP);
  vec3 col = uCol[int(cls + 0.5) * 5 + fi];
  if (kind == 2) col = mix(col, uCol[fi], uGhost * aInfo2.z);
  if (kind < 2) col = mix(col, uBg, uCutDim * ez(clamp((uCut - aInfo2.x - 0.15) / 0.6, 0.0, 1.0)));
  vCol = mix(col, uBg, uGlobal);
  gl_Position = (a <= 0.0) ? vec4(3.0, 3.0, 3.0, 1.0) : uProjectionMatrix * uModelViewMatrix * vec4(pos, 1.0);
}`;
const FRAG = 'precision highp float; varying vec3 vCol; void main(){ gl_FragColor = vec4(vCol, 1.0); }';

/* ── palette (sRGB, from the brand roles only) ── */
let PAL = null, FLOORC = null, GRIDC = null, PLANEC = null, BGC = null, KH = null;
function palette(K) {
  const C = K.C, rgb = (h) => K.hexRgb(h).map((x) => x / 255), mixc = (a, b, u) => a.map((x, i) => x + (b[i] - x) * u);
  const bg = rgb(C.paper), ink = rgb(C.ink), gold = rgb(C.accent), blue = rgb(C.soft), muted = rgb(C.muted), panel = rgb(C.panel);
  const sh = [1.0, KN.shadeFront, KN.shadeBack, KN.shadeRight, KN.shadeLeft];
  const ghost = mixc(bg, muted, KN.ghostMix), plate = mixc(bg, muted, KN.plateMix);
  PAL = []; [ghost, gold, blue, plate].forEach((c) => sh.forEach((f) => PAL.push(...c.map((x) => Math.min(1, x * f)))));
  BGC = bg; FLOORC = mixc(bg, panel, KN.floorMix).map((x) => x * 255); GRIDC = ink.map((x) => x * 255); PLANEC = gold.map((x) => x * 255);
}

/* ── camera: rig script from knobs; ambient yaw drift about the aim point; labels read the same function ── */
function rigScript() {
  const el = KN.camPlanEl, d0 = KN.camPlanDist, side = [KN.camSideAz, KN.camSideEl, d0 * KN.camSideR];
  return { proj: 'persp', dur: 153, near: 10, far: 9000, start: { eye: sph(CTAU, 0, el, d0), center: CTAU, fov: KN.camFov },
    moves: [
      { id: 'm1', move: 'orbit', t0: KN.m1T0, t1: KN.m1T1, az: KN.camSideAz, el: KN.camSideEl, r: KN.camSideR, ease: 'inout', around: CSIDE },
      { id: 'toPR', move: 'cut', t0: KN.prCut, eye: sph(CPR, 0, el, KN.camPrDist), center: CPR },
      { id: 'toMin', move: 'cut', t0: KN.minCut, eye: sph(CMIN, KN.camMinAz, KN.camMinEl, KN.camMinDist), center: CMIN },
      { id: 'toTau', move: 'cut', t0: KN.tauCut, eye: sph(CSIDE, side[0], side[1], side[2]), center: CSIDE },
      { id: 'book', move: 'orbit', t0: KN.bookT0, t1: KN.bookT1, az: -KN.camSideAz, el: KN.camPlanEl, r: 1 / KN.camSideR, ease: 'inout', around: CTAU },
    ] };
}
function poseAt(t) { return RIG.at(RIGC, t); }
function camAt(t, still) {
  const q = poseAt(t), d = still ? 0 : KN.driftDeg * D2R * Math.sin(2 * Math.PI * t / KN.driftPeriod), c = q.center;
  const dx = q.eye[0] - c[0], dz = q.eye[2] - c[2], cs = Math.cos(d), sn = Math.sin(d);
  return { eye: [c[0] + dx * cs + dz * sn, q.eye[1], c[2] - dx * sn + dz * cs], look: c, up: q.up, fov: q.fov };
}

/* the screen rectangle of a world box under the pose at tRest (no drift): labels keep out of the marks they name */
function rectOf(tRest, x0, x1, y0, y1, z0, z1, pad) {
  const pose = poseAt(tRest); let a = 1e9, b = 1e9, c = -1e9, d = -1e9;
  for (const x of [x0, x1]) for (const y of [y0, y1]) for (const z of [z0, z1]) { const s = RIG.worldToScreen(pose, [x, y, z], 960, 540); a = Math.min(a, s.x); b = Math.min(b, s.y); c = Math.max(c, s.x); d = Math.max(d, s.y); }
  return [Math.round(a - pad), Math.round(b - pad), Math.round(c + pad), Math.round(d + pad)];
}

/* ── scenes: tau [0, prCut) and [tauCut, end) · pr · min ── */
const sceneAt = (t) => (t >= KN.minCut && t < KN.tauCut ? 'min' : t >= KN.prCut && t < KN.minCut ? 'pr' : 'tau');
const ORIGIN = { tau: [0, 0], pr: [0, ZP], min: [XM, 0] };

function floorDraw(p, sc) {
  const o = ORIGIN[sc], step = KN.gridStep * TP, n = Math.ceil(KN.floorSize / 2 / step);
  p.resetShader(); p.noStroke(); p.fill(FLOORC[0], FLOORC[1], FLOORC[2]);
  p.push(); p.translate(o[0], 0.5, o[1]); p.rotateX(Math.PI / 2); p.plane(KN.floorSize, KN.floorSize); p.pop();
  p.stroke(GRIDC[0], GRIDC[1], GRIDC[2], KN.gridAlpha * 255); p.strokeWeight(1);
  const h = KN.floorSize / 2;
  for (let i = -n; i <= n; i++) { p.line(o[0] + i * step, 0.2, o[1] - h, o[0] + i * step, 0.2, o[1] + h); p.line(o[0] - h, 0.2, o[1] + i * step, o[0] + h, 0.2, o[1] + i * step); }
  p.noStroke();
}
const cutLevel = (t) => P.triesPer * sm(seg(t, KN.m3T0, KN.m3T1));
function planeDraw(p, t) {
  const op = win(t, KN.m3T0 - 0.3, KN.m3T0 + 0.4, KN.planeOut, KN.planeOut + 0.8); if (op <= 0.01) return;
  const y = -(TH + cutLevel(t) * PC - 0.6), w = SW + KN.planeMargin, d = SD + KN.planeMargin;
  p.resetShader(); p.noStroke(); p.fill(PLANEC[0], PLANEC[1], PLANEC[2], 255 * KN.planeAlpha * op);
  p.push(); p.translate(0, y, 0); p.rotateX(Math.PI / 2); p.plane(2 * w, 2 * d); p.pop();
  p.stroke(PLANEC[0], PLANEC[1], PLANEC[2], 255 * op); p.strokeWeight(1.6);
  p.line(-w, y, -d, w, y, -d); p.line(w, y, -d, w, y, d); p.line(w, y, d, -w, y, d); p.line(-w, y, d, -w, y, -d); p.noStroke();
}
function cubesDraw(p, t) {
  const U = (n, v) => SH.setUniform(n, v), W = KN.arrW, ap = (a, b) => seg(t, a, b) * (1 + W);
  p.shader(SH); p.noStroke(); p.fill(255);
  const m1 = seg(t, KN.m1T0, KN.m1T1), m2 = seg(t, KN.m2T0, KN.m2T1), m4 = seg(t, KN.m4T0, KN.m4T1);
  U('uArr', [ap(KN.tileT0, KN.tileT1), ap(KN.cubeT0, KN.cubeT1), ap(KN.prT0, KN.prT1), ap(KN.min27T0, KN.min27T1), ap(KN.min289T0, KN.min289T1)]);
  const bk = seg(t, KN.bookT0, KN.bookT1);
  U('uMa', [0, m1, m4, 0, 0]); U('uMb', [m2, m2, 0, 0, 0]); U('uBk', [bk, bk, 0, 0, 0]);
  U('uSz', [TW, TH, TW, E, E, E, E, E, E, E, E, E, E, E, E]);
  U('uCol', PAL); U('uBg', BGC); U('uArrW', W); U('uDrop', KN.drop); U('uLift', KN.lift1); U('uLift2', KN.lift2); U('uStag', KN.stagger);
  U('uLitP', seg(t, KN.litT0, KN.litT1)); U('uCut', cutLevel(t)); U('uCutDim', KN.cutDim);
  U('uGhost', sm(seg(t, KN.ghost0, KN.ghost1))); U('uGlobal', KN.mondayDim * sm(seg(t, KN.dimT0, KN.dimT0 + 1.0)));
  p.model(GEO); p.resetShader();
}

/* ── labels: gl-labels placements -> kit2 SVG (roles carried) ── */
function drawPl(K, key, sol, op, keep) {
  const C = K.ROLES;
  for (const q of sol.placements) {
    if (keep && !keep(q)) continue;
    const o = op; if (o <= 0.01) continue;
    const kk = key + q.id + (q.callout ? '.co' : ''), col = C[q.color] || C.ink, b = q.box;
    K.rc(kk + '.p', 'labels', b[0], b[1], b[2] - b[0], b[3] - b[1] + (q.sub ? KN.subGap : 0), { fill: C.paper, fo: KN.plate, op: o });
    K.ln(kk + '.l', 'labels', q.lead[0], q.lead[1], q.lead[2], q.lead[3], { stroke: q.callout ? col : C.muted, w: q.callout ? 1.6 : 1, op: o });
    K.rc(kk + '.d', 'labels', q.ax - 2.5, q.ay - 2.5, 5, 5, { fill: col, op: o });
    const an = q.align === 'right' ? 'end' : q.align === 'center' ? 'middle' : 'start';
    K.tx(kk + '.t', 'labels', q.tx, q.ty, q.text, { fam: q.fam, size: q.size, fill: col, role: q.dataRole, anchor: an, op: o });
    if (q.sub) K.tx(kk + '.s', 'labels', q.tx, q.sy + KN.subGap, q.sub, { fam: q.subFam, size: q.subSize, fill: C.muted, role: q.subDataRole, anchor: an, op: o });
  }
}
let MEAS = null, AN = null, OPT = null, RECT = null;
const topOfBar = (cx, n) => [cx, -(Math.ceil(n / BW) * PC + 9), 0];

function setupLabels() {
  MEAS = (s, size, fam) => String(s).length * size * (fam === 'disp' ? KN.dispAdv : 0.6);
  const tPlan = (KN.cTasks + KN.cPctEnd) / 2, tSide = (KN.cAll + KN.cNone) / 2, tPr = KN.cPrs + 1, tMin = KN.cMin27 + 1;
  const ym = -(TH + 4 * PC), hgp = KN.prGap * PC / 2;
  RECT = {
    plan: rectOf(tPlan, -HW, HW, -(TH + E), 0, -HD, HD, 6),
    side: rectOf(tSide, -HW, HW, ym, 0, -HD, HD, 6),
    sorted: rectOf(KN.c44, -SW, SW, ym, 0, -SD, SD, 6),
    pr: rectOf(tPr, -(PRC * PC) / 2, (PRC * PC) / 2, -E, 0, ZP - (PRR * PC) / 2, ZP + (PRR * PC) / 2, 8),
    prA: rectOf(tPr, -(PRC * PC) / 2, (PRC * PC) / 2, -E, 0, ZP - hgp - PRR * PC / 2, ZP - hgp, 6),
    prB: rectOf(tPr, -(PRC * PC) / 2, (PRC * PC) / 2, -E, 0, ZP + hgp, ZP + hgp + PRR * PC / 2, 6),
    minA: rectOf(tMin, XM - BW * PC - KN.barGap * PC / 2, XM - KN.barGap * PC / 2, -(Math.ceil(P.h80 / BW) * PC), 0, -E, E, 0),
    minB: rectOf(tMin, XM + KN.barGap * PC / 2, XM + KN.barGap * PC / 2 + BW * PC, -(Math.ceil(P.h50 / BW) * PC), 0, -E, E, 0),
  };
  const mk = (id, x, y, z, text, sub, role, pr, sty) => Object.assign({ id, x, y, z, text, sub, role: role || 'secondary', size: role === 'result' ? KN.calloutSize : 0, priority: pr || 0 }, sty || {});
  const yTop = -(TH + E) / 2;
    const back = (q) => { for (let c = COLS - 1; c >= 0; c--) if (QS[c] === q) return c; return 0; };
  const ca = colTop(back(4), false), cn = colTop(back(0), false), sf = colTop(ORDER[Math.min(P.n4, 4 * SR) - 1], true), sn = colTop(ORDER[NT - P.n0 + Math.min(P.n0, SR) - 1], true);
  const LST = {
    case: [mk('a.tasks', HW + 6, yTop, -HD * 0.5, '', '', 'result'), mk('a.tries', HW + 6, yTop, -HD * 0.05, '', '', 'result'), mk('a.pass', HW + 6, yTop, HD * 0.4, '', '', 'result'), mk('a.pct', HW + 6, yTop, HD * 0.85, '', '', 'result')],
    side: [mk('c.all', ca[0], ca[1], ca[2], '', '', 'result'), mk('c.none', cn[0], cn[1], cn[2], '', '', 'result'), mk('s.full', sf[0], sf[1], sf[2], '', '', 'result'), mk('s.none', sn[0], sn[1], sn[2], '', '', 'result')],
    pr: [mk('r.prs', (PRC * PC) / 2, -E / 2, ZP - (PRR * PC) / 2, '', '', 'result'), mk('r.swe', -(PRC * PC) / 2, -E / 2, ZP - (PRR * PC) / 2, '', '', 'result')],
    prB: [mk('r.half', (PRC * PC) / 4, -E / 2, ZP + hgp + PC / 2, '', '', 'result')],
  };
  AN = {
    bar: [mk('p.bar', SW + KN.planeMargin, ym, SD + KN.planeMargin, 'THE ALL-FOUR BAR', null, 'secondary', 1)],
    min: [mk('m.27', ...topOfBar(XM - (BW * PC + KN.barGap * PC) / 2, P.h80), P.h80 + ' min', null, 'secondary', 1, { fam: 'disp', size: KN.refPinSize, color: 'accent' }), mk('m.289', ...topOfBar(XM + (BW * PC + KN.barGap * PC) / 2, P.h50), P.h50h + ' h ' + P.h50m + ' min', null, 'secondary', 1)],
  };
  // callout-only scenes: the anchor list is a function of t that returns just the anchor the callout follows (an ordinary label for it is suppressed
  // by gl-labels while the callout is on it, and no other anchor exists), so nothing but the callout is ever drawn
  const only = (list, sched) => { const by = {}; list.forEach((a) => { by[a.id] = [a]; }); const none = [];
    return (t) => { let id = null; for (const e of sched) if (e.t <= t + 1e-9) id = e.id; return (id && by[id]) || none; }; };
  const SCH_ = {
    case: [[0, null], [KN.cTasks, 'a.tasks'], [KN.cTries, 'a.tries'], [KN.cPass, 'a.pass'], [KN.cPct, 'a.pct'], [KN.cPctEnd, null]],
    side: [[0, null], [KN.cAll, 'c.all'], [KN.cNone, 'c.none'], [KN.cNoneEnd, null], [KN.c44, 's.full'], [KN.c22, 's.none'], [KN.c22End, null], [KN.c44of, 's.full'], [KN.c383, 's.full'], [KN.c383End, null]],
    pr: [[0, null], [KN.cPrs, 'r.prs'], [KN.cSwe, 'r.swe'], [KN.cSweEnd, null]],
    prB: [[0, null], [KN.cHalf, 'r.half'], [KN.cHalfEnd, null]],
  };
  Object.keys(SCH_).forEach((k) => { AN[k] = only(LST[k], SCH_[k].map((e) => ({ t: e[0], id: e[1] }))); });
  const base = { w: 960, h: 540, fps: 30, hold: KN.hold, leader: KN.leader, margin: 14, occlusion: false, maxShown: KN.maxShown, sticky: 'window', measure: MEAS, measureKey: 'pet-a' };
  const BAND = [0, 0, 960, 46], CAP = [0, 418, 960, 540], LEG = [30, 50, 312, 132], SCH = [620, 50, 930, 74];
  const co = (sched) => ({ leader: KN.calloutLeader, size: KN.calloutSize, schedule: sched });
  const S = (t, id, text, sub) => ({ t, id, text, sub });
  OPT = {
    case: Object.assign({}, base, { reserve: [BAND, CAP, LEG, RECT.plan], callout: co([S(0, null),
      S(KN.cTasks, 'a.tasks', '' + P.tasks, 'TASKS · ONE TILE EACH'), S(KN.cTries, 'a.tries', '' + P.tries, 'TRIES · ONE CUBE EACH'),
      S(KN.cPass, 'a.pass', '' + P.passed, 'PASSED · A LIT CUBE'), S(KN.cPct, 'a.pct', pc1(P.pass1), 'OF TRIES PASS'), S(KN.cPctEnd, null)]) }),
    side: Object.assign({}, base, { reserve: [BAND, CAP, LEG, RECT.side, RECT.sorted], callout: co([S(0, null),
      S(KN.cAll, 'c.all', 'All four lit', 'ONE TASK · FOUR TRIES'), S(KN.cNone, 'c.none', 'None lit', 'ONE TASK · NONE PASSED'), S(KN.cNoneEnd, null),
      S(KN.c44, 's.full', '' + P.n4, 'TASKS PASS ALL FOUR TRIES'), S(KN.c22, 's.none', '' + P.n0, 'TASKS NEVER PASS'), S(KN.c22End, null),
      S(KN.c44of, 's.full', P.n4 + ' of ' + P.tasks, 'COLUMNS LIT ALL THE WAY'), S(KN.c383, 's.full', pc1(P.pass4), 'PASS ALL FOUR TRIES'), S(KN.c383End, null)]) }),
    bar: Object.assign({}, base, { reserve: [BAND, CAP, LEG, [150, 56, 810, 126], RECT.side, RECT.sorted], callout: null }),
    pr: Object.assign({}, base, { reserve: [BAND, CAP, LEG, SCH, RECT.pr], callout: co([S(0, null),
      S(KN.cPrs, 'r.prs', '' + P.prs, 'PULL REQUESTS PASS THE TESTS'), S(KN.cSwe, 'r.swe', pc1(P.swe), 'TOP SWE-BENCH VERIFIED SCORE'), S(KN.cSweEnd, null)]) }),
    prB: Object.assign({}, base, { reserve: [BAND, CAP, LEG, SCH, RECT.prA, RECT.prB], callout: co([S(0, null),
      S(KN.cHalf, 'r.half', 'About half', 'WOULD NOT BE MERGED'), S(KN.cHalfEnd, null)]) }),
    min: Object.assign({}, base, { reserve: [BAND, CAP, LEG, RECT.minA, RECT.minB], callout: co([S(0, null),
      S(KN.cMin27, 'm.27', P.h80 + ' min', 'AT THE ' + P.r80 + ' % BAR'), S(KN.cMin27End, null),
      S(KN.cMin289, 'm.289', P.h50h + ' h ' + P.h50m + ' min', 'AT THE ' + P.r50 + ' % BAR'), S(KN.cRatio, 'm.289', 'about ' + P.horizonRatio + 'x', 'LONGER THAN AT THE ' + P.r80 + ' % BAR'), S(KN.cRatioEnd, null)]) }),
  };
}

/* ── text over the scene (all SVG with data-role; nothing here enters the caption band, y >= 418) ── */
function stageText(K, t) {
  const C = K.ROLES, sc = sceneAt(t);
  // header: film name left, the operation right (T7: say which operation it is)
  K.tx('hd.l', 'chrome', 40, 30, 'PASS EVERY TIME · THE TEST FLOOR', { size: 12, fill: C.muted, role: 'chrome', ls: 1.5 });
  const ph = t < KN.tileT0 ? 'THE BELIEF' : t < KN.m1T0 ? 'THE FIELD, SEEN FROM ABOVE' : t < KN.m1T1 ? 'TURNING THE FIELD TO THE SIDE' : t < KN.m2T0 ? 'ONE COLUMN PER TASK'
    : t < KN.m2T1 ? 'SORTED BY TRIES PASSED' : t < KN.m3T0 ? 'THE SAME COLUMNS, IN ORDER' : t < KN.m3T1 ? 'CUT AT THE ALL-FOUR BAR' : t < KN.prCut ? 'ONLY COLUMNS LIT ALL THE WAY STAY BRIGHT'
    : t < KN.m4T0 ? 'ONE SHEET OF PULL REQUESTS' : t < KN.ghost0 ? 'SPLIT BY WHAT A MAINTAINER WOULD MERGE' : t < KN.minCut ? 'MERGED AND NOT MERGED' : t < KN.tauCut ? 'TASK LENGTH, ONE CUBE A MINUTE'
    : t < KN.bookT1 ? 'BACK TO THE FIELD' : 'MONDAY';
  K.tx('hd.r', 'chrome', 920, 30, ph, { size: 12, fill: C.muted, role: 'chrome', anchor: 'end', ls: 1.5 });
  K.ln('hd.rule', 'chrome', 40, 40, 920, 40, { stroke: C.line, w: 0.75, op: 0.8 });

  // HOOK: the belief, then the doubt, as set type over the empty floor (no digit, no cube)
  const h1 = win(t, KN.hook1In, KN.hook1In + 0.6, KN.hook1Out, KN.hook1Out + 0.5), h2 = win(t, KN.hook2In, KN.hook2In + 0.6, KN.hook2Out, KN.hook2Out + 0.6);
  if (h1 > 0.01) {
    K.tx('hk.e1', 'labels', 480, 168, 'THE BELIEF', { size: 12, fill: C.muted, role: 'chrome', anchor: 'middle', ls: 3, op: h1 });
    K.tx('hk.a1', 'labels', 480, 224, 'Usually right', { fam: 'disp', size: KN.hookSize, fill: C.ink, role: 'must-read', anchor: 'middle', op: h1 });
    K.tx('hk.a2', 'labels', 480, 224 + KN.hookSize * 1.15, 'means mostly done.', { fam: 'disp', size: KN.hookSize, fill: C.accent, role: 'must-read', anchor: 'middle', op: h1 });
  }
  if (h2 > 0.01) {
    K.tx('hk.e2', 'labels', 480, 190, 'COUNT EVERY TRY', { size: 12, fill: C.muted, role: 'chrome', anchor: 'middle', ls: 3, op: h2 });
    K.tx('hk.b', 'labels', 480, 262, 'Does it?', { fam: 'disp', size: KN.hookSize * 1.4, fill: C.ink, role: 'must-read', anchor: 'middle', op: h2 });
  }

  // legend (units, words only): what one tile and one cube are
  const lg = (key, y, s, t0, tEnd) => { const o = win(t, t0, t0 + 0.5, tEnd, tEnd + 0.6); if (o > 0.01) K.tx(key, 'labels', 40, y, s, { size: 14, fill: C.ink, role: 'secondary', op: o }); };
  if (t >= KN.tileT0 - 0.5 && t < KN.prCut) {
    const e = KN.legOut;
    lg('lg.m', 62, 'GPT-4o · tau-bench retail · 2024', KN.tileT0 - 0.4, e);
    lg('lg.1', 84, 'ONE TILE = ONE TASK', KN.cTasks - 0.3, e); lg('lg.2', 104, 'ONE CUBE = ONE TRY', KN.cTries - 0.3, e); lg('lg.3', 124, 'GOLD = THE TRY PASSED', KN.litT0, e);
  }
  if (t >= KN.prCut && t < KN.minCut) lg('lg.pr', 62, 'ONE CUBE = ONE PULL REQUEST', KN.prCut - 0.5, KN.minCut - 0.6);
  if (t >= KN.minCut && t < KN.tauCut) lg('lg.mi', 62, 'ONE CUBE = ONE MINUTE', KN.minCut - 0.5, KN.tauCut - 0.6);
  if (t >= KN.bookT1) {   // the bookend: the opening frame, read again (same legend corner, the new meaning of gold)
    lg('lg.cm', 62, 'GPT-4o · tau-bench retail · 2024', KN.bookT1, KN.qOut); lg('lg.c1', 84, 'ONE TILE = ONE TASK', KN.bookT1, KN.qOut);
    lg('lg.c2', 104, 'GOLD = PASSED ALL FOUR TRIES', KN.bookT1, KN.qOut);
  }

  // callouts and pins through gl-labels (screen space, hysteresis, hard cuts; labels are off while a move runs)
  const keepAll = null;
  if (sc === 'tau' && t >= KN.cTasks - 0.2 && t < KN.m1T0) drawPl(K, 'cs.', GLL.solve(t, CAMFN, AN.case, OPT.case), 1, keepAll);
  if (sc === 'tau' && t >= KN.m1T1 && t < KN.prCut) {
    const sol = GLL.solve(t, CAMFN, AN.side, OPT.side);
    drawPl(K, 'sd.', sol, 1, keepAll);
    const pb = win(t, KN.m3T1 + 0.2, KN.m3T1 + 0.8, KN.planeOut - 0.2, KN.planeOut + 0.6);
    if (pb > 0.01) drawPl(K, 'bar.', GLL.solve(t, CAMFN, AN.bar, OPT.bar), pb, keepAll);
  }
  if (sc === 'pr') drawPl(K, 'pr.', t < KN.m4T0 ? GLL.solve(t, CAMFN, AN.pr, OPT.pr) : GLL.solve(t, CAMFN, AN.prB, OPT.prB), 1, keepAll);
  if (sc === 'min') {
    const sol = GLL.solve(t, CAMFN, AN.min, OPT.min);
    drawPl(K, 'mn.', sol, 1, (q) => q.callout || (q.id === 'm.27' ? t >= KN.min27T1 : t >= KN.cMin289));
  }

  // COUNT: the ladder (one row of ratios, each after the counts it comes from) and the paper's own sentence
  const lad = [['ONE TRY · ' + P.passed + ' OF ' + P.tries + ' TRIES', pc1(P.pass1), KN.lad1, KN.ladXL, C.ink], ['EVERY TRY · ' + P.n4 + ' OF ' + P.tasks + ' TASKS', pc1(P.pass4), KN.lad4, KN.ladXR, C.accent]];
  lad.forEach((r, i) => {
    const ok = win(t, r[2], r[2] + 0.5, KN.ladOut, KN.ladOut + 0.5), ov = win(t, r[2] + KN.ladLead, r[2] + KN.ladLead + 0.5, KN.ladOut, KN.ladOut + 0.5);
    if (ov > 0.01) K.tx('ld.v' + i, 'labels', r[3], 86, r[1], { fam: 'disp', size: KN.ladSize, fill: r[4], role: 'must-read', anchor: 'middle', op: ov });
    if (ok > 0.01) K.tx('ld.k' + i, 'labels', r[3], 106, r[0], { size: 14, fill: C.muted, role: 'secondary', anchor: 'middle', ls: 0.5, op: ok });
  });
  const pp = win(t, KN.paperIn, KN.paperIn + 0.6, KN.paperOut, KN.paperOut + 0.6);
  if (pp > 0.01) {
    K.tx('pp.v', 'labels', 480, 88, 'under ' + P.paperPass8Upper + ' %', { fam: 'disp', size: KN.plateSize, fill: C.accent, role: 'must-read', anchor: 'middle', op: pp });
    K.tx('pp.k', 'labels', 480, 109, 'THE PAPER’S OWN RUN · ALL EIGHT TRIES PASS · NOT THESE CUBES', { size: 14, fill: C.muted, role: 'secondary', anchor: 'middle', ls: 1, op: pp });
  }

  // M4: "schematic" tag while the PRs travel (the split is two equal blocks, not a count)
  const sch = win(t, KN.m4T0, KN.m4T0 + 0.6, KN.cHalfEnd - 0.4, KN.cHalfEnd);
  if (sch > 0.01) K.tx('sc.t', 'labels', 920, 62, 'SCHEMATIC SPLIT · TWO EQUAL BLOCKS', { size: 14, fill: C.muted, role: 'secondary', anchor: 'end', op: sch });

  // MONDAY: the question, then the one honest line, both as set type in the free top band
  const q = win(t, KN.qIn, KN.qIn + 0.7, KN.qOut, KN.qOut + 0.5), xl = 40, xr = RECT.plan[2] + KN.colPad, wl = RECT.plan[0] - KN.colPad - xl, wr = 920 - xr;
  if (q > 0.01) {
    K.tx('mo.e', 'labels', xl, KN.monY - 40, 'MONDAY', { size: 12, fill: C.muted, role: 'chrome', ls: 3, op: q });
    K.wrap('How often does it pass when it has to pass every time, and who checks the merge?', wl, KN.mondaySize, 'disp').forEach((s, i) => K.tx('mo.q' + i, 'labels', xl, KN.monY + i * KN.mondaySize * 1.2, s, { fam: 'disp', size: KN.mondaySize, fill: C.ink, role: 'must-read', op: q }));
  }
  const hn = win(t, KN.honestIn, KN.honestIn + 0.8, KN.qOut, KN.qOut + 0.5);
  if (hn > 0.01) {
    K.tx('mo.h', 'labels', xr, KN.monY - 40, 'ONE LIMIT', { size: 12, fill: C.muted, role: 'chrome', ls: 3, op: hn });
    K.wrap('One ' + P.year + ' model, and agents that could not revise: newer ones may do better.', wr, KN.honestSize, 'disp').forEach((s, i) => K.tx('mo.h' + i, 'labels', xr, KN.monY + i * KN.honestSize * 1.2, s, { fam: 'disp', size: KN.honestSize, fill: C.accent, role: 'must-read', op: hn }));
  }
}

window.FILM_RENDER = {
  async setup(p, K) {
    palette(K);
    GEO = bake(p, K);
    SH = p.createShader(VERT, FRAG);
    CAM = p.createCamera();
    RIGC = RIG.compile(rigScript(), null);
    CAMFN = (t) => camAt(t);
    setupLabels();
    p.setCamera(K.cam0);
    // exact counts at any t, for the evaluator and the gate: marks drawn per kind (the arrival rule of the shader)
    const W = KN.arrW;
    window.__pet = { n: NCUBE, kinds: KINDN.slice(), cam: camAt, poseAt, rect: RECT, order: ORDER, qs: QS,
      count: (t) => { const f = (a, b, n) => { const pr = seg(t, a, b) * (1 + W); let k = 0; for (let i = 0; i < n; i++) if ((pr - i / n) / W > 0) k++; return k; };
        return { tiles: f(KN.tileT0, KN.tileT1, NT), tries: f(KN.cubeT0, KN.cubeT1, NT * 4), prs: f(KN.prT0, KN.prT1, P.prs), m27: f(KN.min27T0, KN.min27T1, P.h80), m289: f(KN.min289T0, KN.min289T1, P.h50) }; },
      sol: (w, t) => { const r = GLL.solve(t, CAMFN, AN[w], OPT[w]); return r.placements.map((q) => [q.id, q.callout, Math.round(q.box[0]), Math.round(q.box[1]), Math.round(q.box[2]), Math.round(q.box[3])]); } };
  },

  render(t, s, K) {
    const p = K.p, cam = camAt(t);
    CAM.camera(cam.eye[0], cam.eye[1], cam.eye[2], cam.look[0], cam.look[1], cam.look[2], cam.up[0], cam.up[1], cam.up[2]);
    CAM.perspective(cam.fov, 960 / 540, RIGC.near, RIGC.far);
    p.setCamera(CAM); p.noLights();
    floorDraw(p, sceneAt(t));
    cubesDraw(p, t);
    planeDraw(p, t);
    stageText(K, t);
  },
};
})();

