#!/usr/bin/env python3
"""lib/assemble.py (noether-frontier draft B, "the laboratory bench") · writes ../film.js = lib/gl-pointcloud.js (PATCHED copy of Part 1's patched copy)
+ lib/film.src.js, comments and indentation stripped. lib/data.js (made by lib/mkdata.py) is NOT in film.js: film.json "libs" inlines it, so the
data counts toward the page size (G8) but not toward film code. Deterministic: run twice, diff."""
import os, re, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
MODS = ["gl-pointcloud.js"]

def strip(src):
    out, i, n = [], 0, len(src)
    prev = ""
    while i < n:
        c = src[i]; d = src[i + 1] if i + 1 < n else ""
        if c in "'\"`":
            j = i + 1
            while j < n and src[j] != c:
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1]); prev = c; i = j + 1; continue
        if c == "/" and d == "*":
            j = src.find("*/", i + 2); i = n if j < 0 else j + 2; out.append(" "); continue
        if c == "/" and d == "/":
            j = src.find("\n", i); i = n if j < 0 else j; continue
        if c == "/" and (prev == "" or prev in "(,=:[!&|?{};+-*%<>~^" or re.search(r"\breturn\s*$", "".join(out[-3:]))):
            j, cls = i + 1, False
            while j < n:
                if src[j] == "\\": j += 2; continue
                if src[j] == "[": cls = True
                elif src[j] == "]": cls = False
                elif src[j] == "/" and not cls: break
                j += 1
            j += 1
            while j < n and src[j].isalpha(): j += 1
            out.append(src[i:j]); prev = "/"; i = j; continue
        if c in " \t":
            nxt = src[i + 1] if i + 1 < n else ""
            if (out and out[-1] in (" ", "\t", "\n")) or (out and out[-1] in "{}();,=:?[]<>!&|*%") or nxt in "{}();,=:?[]<>!&|*%":
                i += 1; continue
        out.append(c)
        if not c.isspace(): prev = c
        i += 1
    lines = [l.strip() for l in "".join(out).split("\n")]
    return "\n".join(l for l in lines if l)

def main():
    parts = ["/* noether-frontier draft B · film.js is GENERATED by lib/assemble.py; edit lib/film.src.js. Inlined (comment-stripped): lib/gl-pointcloud.js (patched copy). "
             "Data: lib/data.js through film.json libs. */",
             "window.ARSENAL = window.ARSENAL || {}; ['patterns','structures','materials','brands','core','post'].forEach(function (k) { window.ARSENAL[k] = window.ARSENAL[k] || {}; });"]
    for m in MODS:
        src = open(os.path.join(HERE, m), encoding="utf-8").read()
        parts.append("/* lib/%s sha256 %s */\n" % (m, hashlib.sha256(src.encode()).hexdigest()[:16]) + strip(src))
    parts.append(strip(open(os.path.join(HERE, "film.src.js"), encoding="utf-8").read()))
    out = "\n".join(parts) + "\n"
    with open(os.path.join(HERE, "..", "film.js"), "w", encoding="utf-8") as f:
        f.write(out)
    print("film.js %d bytes" % len(out.encode()))

if __name__ == "__main__":
    main()
