#!/usr/bin/env python3
"""lib/assemble.py · writes ../film.js = camera (api only), morph-type (+P.kit), the headline font, exhibit.js, then lib/film.src.js (the film).
Comments and indentation are stripped so the film code stays under the 120 KB gate budget. webgl-scene.js and shader.js stay in lib/ as the provenance of the techniques exhibit.js adapts; they are not assembled.
kit2 inlines only film.js, so this concatenation is how the arsenal reaches the page. Deterministic."""
import os, re, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
MODS = ["camera.js", "morph-type.js", "headline-font.js", "exhibit.js"]   # arsenal/patterns/camera (api only), arsenal/patterns/morph-type (+P.kit), the subset headline font, the gallery

def strip(src):
    out, i, n = [], 0, len(src)
    prev = ""                          # last significant char, to tell a regex literal from a division
    while i < n:
        c = src[i]; d = src[i + 1] if i + 1 < n else ""
        if c in "'\"`":
            j = i + 1
            while j < n and src[j] != c:
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1]); prev = c; i = j + 1; continue
        if c == "/" and d == "*":
            j = src.find("*/", i + 2); i = n if j < 0 else j + 2; out.append(" "); continue
        if c == "/" and d == "/":
            j = src.find("\n", i); i = n if j < 0 else j; continue
        if c == "/" and (prev == "" or prev in "(,=:[!&|?{};+-*%<>~^" or re.search(r"\breturn\s*$", "".join(out[-3:]))):
            j, cls = i + 1, False
            while j < n:
                if src[j] == "\\": j += 2; continue
                if src[j] == "[": cls = True
                elif src[j] == "]": cls = False
                elif src[j] == "/" and not cls: break
                j += 1
            j += 1
            while j < n and src[j].isalpha(): j += 1
            out.append(src[i:j]); prev = "/"; i = j; continue
        if c in " \t":
            nxt = src[i + 1] if i + 1 < n else ""
            if (out and out[-1] in (" ", "\t", "\n")) or (out and out[-1] in "{}();,=:?[]<>!&|*%") or nxt in "{}();,=:?[]<>!&|*%":
                i += 1; continue
        out.append(c)
        if not c.isspace(): prev = c
        i += 1
    lines = [l.strip() for l in "".join(out).split("\n")]
    return "\n".join(l for l in lines if l)

# Top-level demo blocks the film never calls, cut from the assembled copy only (lib/*.js stay verbatim); each cut is
# [start regex, end regex): the block from the first matching line up to, not including, the end anchor. A single
# regex drops that one line. node --check and the gate's G1 load then prove the remainder still parses and runs.
CUTS = {
    "camera.js": [(r"^  const SCENES = \{\};", r"^  const P_ = \{"),                        # demo scenes map/timeline/grid
                  (r"^  const P_ = \{", r"^  window\.ARSENAL\.patterns\.camera = P_;",      # demo setup/draw; the api object is kept
                   "  const P_ = { id: 'camera', api: { sample, worldToScreen, screenToWorld, toCuts, EASE } };")],
}

def cut(src, rules):
    lines = src.split("\n")
    for rule in rules:
        start, end, rep = (rule + (None,))[:3]
        i = next(k for k, l in enumerate(lines) if re.match(start, l))
        j = i + 1 if end is None else next(k for k, l in enumerate(lines) if k > i and re.match(end, l))
        lines[i:j] = ["/* [cut by lib/assemble.py: %d lines the film never calls] */" % (j - i)] + ([rep] if rep else [])
    return "\n".join(lines)

def main():
    parts = ["/* simpsons-3d / draft B · film.js is GENERATED by lib/assemble.py; edit lib/film.src.js.\n"
             "   Arsenal modules inlined (comment-stripped copies of lib/*.js): " + ", ".join(MODS) + " */",
             "window.ARSENAL = window.ARSENAL || {}; ['patterns','structures','materials','brands','core'].forEach(function (k) { window.ARSENAL[k] = window.ARSENAL[k] || {}; });"]
    for m in MODS:
        src = open(os.path.join(HERE, m), encoding="utf-8").read()
        body = cut(src, CUTS[m]) if m in CUTS else src
        parts.append("/* ── lib/%s sha256 %s%s ── */\n" % (m, hashlib.sha256(src.encode()).hexdigest()[:16], " (cut)" if m in CUTS else "") + strip(body))
    parts.append(open(os.path.join(HERE, "film.src.js"), encoding="utf-8").read())
    out = "\n".join(parts) + "\n"
    with open(os.path.join(HERE, "..", "film.js"), "w", encoding="utf-8") as f:
        f.write(out)
    print("film.js %d bytes" % len(out.encode()))

if __name__ == "__main__":
    main()
