/* simpsons-3d / draft B · "the exhibit" · film source. film.js is GENERATED by lib/assemble.py (edit this file, not film.js).
   Dark gallery, two sculptures of boxes (one box = one applicant) lit from one side; a dolly along a rail turns the
   pooled towers into six department pairs. Pure: render(t, state, K) draws frame t from t, state.answer and film.json knobs only. */
(function () {
'use strict';
const F = window.FILM, PR = F.params, EX = window.EXHIBIT;
const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
const lerp = (a, b, u) => a + (b - a) * u;
const sstep = (a, b, x) => { const u = clamp((x - a) / (b - a)); return u * u * (3 - 2 * u); };
const fmt = (n) => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const sum = (a) => a.reduce((x, y) => x + y, 0);
const D6 = EX.D6;
const SEX = { m: { n: D6.map((d) => PR['m' + d]), a: D6.map((d) => PR['m' + d + 'a']) }, w: { n: D6.map((d) => PR['w' + d]), a: D6.map((d) => PR['w' + d + 'a']) } };
const RATE = { m: SEX.m.n.map((n, i) => Math.round(100 * SEX.m.a[i] / n)), w: SEX.w.n.map((n, i) => Math.round(100 * SEX.w.a[i] / n)) };
const POOL = { m: Math.round(100 * sum(SEX.m.a) / sum(SEX.m.n)), w: Math.round(100 * sum(SEX.w.a) / sum(SEX.w.n)) };
const HIGHER = D6.map((_, i) => (SEX.w.a[i] / SEX.w.n[i] > SEX.m.a[i] / SEX.m.n[i] ? 'w' : 'm'));
const WORDS = { m: [POOL.m].concat(RATE.m).map((v) => v + '%'), w: [POOL.w].concat(RATE.w).map((v) => v + '%') };

let S = null, HF = null, NUM = null;

/* ───────── headline numerals: contour morph (arsenal/patterns/morph-type kernel) drawn into a p2d layer, shown as a flat image ───────── */
function makeNumerals(p, K, kn) {
  const MT = window.ARSENAL.patterns['morph-type'].kit, size = kn('headSize', 84), S0 = 200;
  p.textFont(HF); p.textSize(S0);
  const shapeOf = (s) => MT.makeShape(HF.textToContours(s, 0, 0, { sampleFactor: 1 }));
  const capH0 = -shapeOf('0').y0, k = size / capH0;
  const out = { size, w: Math.round(size * 3.6), h: Math.round(size * 1.5), plans: {} };
  for (const sx of ['m', 'w']) {
    const shapes = WORDS[sx].map((s) => { const sh = shapeOf(s); return MT.xform(sh, k, -((sh.x0 + sh.x1) / 2) * k, 0); });
    out.plans[sx] = [];
    for (let i = 0; i < shapes.length - 1; i++) out.plans[sx].push(MT.buildPlan(shapes[i], shapes[i + 1], 3, size * 1.3));
    out.plans[sx].push(MT.buildPlan(shapes[shapes.length - 1], shapes[shapes.length - 1], 3, size * 1.3));
  }
  out.g = { m: p.createGraphics(out.w, out.h), w: p.createGraphics(out.w, out.h) };
  out.g.m.pixelDensity(2); out.g.w.pixelDensity(2);
  return out;
}
function morphAt(kn, t) {      // which word -> word morph is running: {i, u}
  const tD1 = kn('tDollyEnd', 46.0), tr0 = kn('trackStart', 46.2), step = kn('pairStep', 1.9), md = kn('morphDur', 0.7), lead = kn('morphLead', 0.45);
  const trans = D6.map((_, i) => (i === 0 ? tD1 : tr0 + i * step) - lead);
  let i = -1; for (let j = 0; j < trans.length; j++) if (t >= trans[j]) i = j;
  if (i < 0) return { i: 0, u: 0 };
  return { i, u: clamp((t - trans[i]) / md) };
}
function paintNumeral(p, sx, t, kn, colHex, alpha) {
  const N = NUM, MT = window.ARSENAL.patterns['morph-type'].kit, g = N.g[sx], ctx = g.drawingContext, m = morphAt(kn, t);
  g.clear();
  ctx.save();
  const o = { stagger: 0.35, lift: 8, ease: 'cubic', render: 'fill', dotEvery: 3, ink: colHex, lineCol: colHex };
  const j = m.i, plan = N.plans[sx][j];
  MT.paint(ctx, plan, m.u, N.w / 2, N.h * 0.78, o, colHex, colHex, 0);
  ctx.restore();
  return g;
}

/* ───────── setup ───────── */
async function setup(p, K) {
  HF = await p.loadFont(window.EXH_HEAD_FONT);
  const kn = K.knob;
  S = EX.make(p, K, PR, kn);
  NUM = makeNumerals(p, K, kn);
}

/* ───────── helpers for the frame ───────── */
const topOf = (S_, sx, kn) => S_.lay[sx].H * EX.CELL + EX.PAD;
function towerBuild(kn, t) {      // visible layers per tower: same layers per second for both, so the men's column is taller
  const rate = kn('buildRate', 5.8), t0 = kn('tBuild0', 17.0);
  const layers = Math.max(0, Math.floor(rate * (t - t0)));
  return layers;
}

function render(t, s, K) {
  const p = K.p, kn = K.knob, C = K.C, seg = K.seg;
  const guess = typeof (s && s.answer) === 'number' ? s.answer : null;
  const tx = (key, x, y, str, o) => K.tx(key, 'labels', x, y, str, o);
  const bgHex = C.paper;

  /* ── build / admit / unstack state, all from t ── */
  const layers = towerBuild(kn, t), lay = S.lay;
  const hM = Math.min(layers, lay.m.H), hW = Math.min(layers, lay.w.H);
  const mClip = t < kn('tUnstack0', 40) ? (hM >= lay.m.H ? 1e6 : hM * EX.CELL + EX.PAD + 0.01) : 1e6;
  const wClip = t < kn('tUnstack0', 40) ? (hW >= lay.w.H ? 1e6 : hW * EX.CELL + EX.PAD + 0.01) : 1e6;
  const hidden = t < kn('tBuild0', 17.0) ? 0 : 1;
  const tA0 = kn('tAdmit0', 24.8), tAd = kn('tAdmitDur', 3.2);
  const maxH = Math.max(lay.m.H, lay.w.H) * EX.CELL + EX.PAD;
  const admitY = t < tA0 ? -60 : (t >= tA0 + tAd ? 1e6 : lerp(-40, maxH + 60, EX.eio(clamp((t - tA0) / tAd))));
  const admitAmt = sstep(tA0 + tAd * 0.3, tA0 + tAd + 1.0, t);
  const tD0 = kn('tDollyStart', 40.0), tD1 = kn('tDollyEnd', 46.0), tW0 = kn('tWide', 57.0), tW1 = kn('tWideEnd', 59.0);
  const focusAmt = sstep(tD0 + 2.0, tD1, t) * (1 - sstep(tW0, tW1, t));
  const railAmt = sstep(tD0 + 1.0, tD1, t) * (1 - sstep(tW0 - 1.0, tW0 + 0.5, t));
  // the reveal: the four pairs where women are higher glow harder, the two where men are higher recede
  const rv = sstep(kn('tReveal', 57.2), kn('tReveal', 57.2) + 1.0, t) * (1 - sstep(62.0, 63.0, t));
  const boost = { m: D6.map((_, d) => 1 + rv * (HIGHER[d] === 'm' ? 0.4 : -0.35)), w: D6.map((_, d) => 1 + rv * (HIGHER[d] === 'w' ? 0.4 : -0.35)) };
  // the gallery lights go down when the process is killed, back up for the commit
  const keyMul = 1 - 0.78 * sstep(4.4, 5.3, t) * (1 - sstep(8.0, 9.2, t));

  // before the build there is nothing on the pads: clip everything to the pads
  const bm = hidden ? mClip : EX.PAD - 1, bw = hidden ? wClip : EX.PAD - 1;
  const info = EX.draw(p, S, t, { build: { mClip: bm, wClip: bw }, admit: { y: admitY, amt: admitAmt }, focusAmt, railAmt, boost, bgHex, menHex: C.soft, womHex: C.accent, keyMul });
  const rig = info.rig;

  /* ── world → sheet pins (camera is still current) ── */
  const pin = (x, y, z) => { const v = p.worldToScreen(new p5.Vector(x, y, z)); return [v.x, v.y]; };
  const gal = (key, wx, wy, wz, str, o) => { const q = pin(wx, wy, wz); if (q[0] < -50 || q[0] > 1010 || q[1] < -50 || q[1] > 590) return; tx(key, q[0] + (o.dx || 0), q[1] + (o.dy || 0), str, o); };

  const MX = kn('towerX', 85), SX = kn('splitX', 62), P = kn('slabGap', 170);
  const eAll = EX.eSlab(kn, t, 0);
  const pooledPhase = t < tD0 + 1.2;
  const mixM = C.soft, mixW = C.accent;

  /* HOOK: the review sheet (silent, no digits) */
  if (t < 8.6) {
    const op = (1 - seg(t, 8.0, 8.6));
    tx('hk.e', 64, 74, 'SALES REVIEW', { size: 14, ls: '0.2em', weight: 500, op: op * seg(t, 0.3, 0.7), role: 'secondary', fill: C.muted });
    tx('hk.h', 64, 132, K.typed('New sales process', t, 0.6, 30), { fam: 'disp', size: 48, op, role: 'must-read' });
    tx('hk.v', 64, 176, K.typed('Converts worse overall.', t, 1.4, 30), { fam: 'sans', size: 28, weight: 500, op, role: 'must-read', fill: C.ink });
    if (t >= 4.4) { const k = K.eout(seg(t, 4.4, 4.65)); K.stamp('hk.st', 'marks', 420, 172, lerp(1.15, 1, k), 'KILLED', { op: op * seg(t, 4.4, 4.5), rim: C.accent, rot: -6, fs: 30, h: 48 }); }
  }
  /* COMMIT */
  if (t >= F.commit.at - 1.2 && t < 16.6) K.commitBox(t, s, { title: F.commit.title, prompt: 'OF 6 DEPARTMENTS', out: 16.0 });

  /* sex names on the pads from the Berkeley caption on */
  const nameOp = seg(t, 8.3, 9.0) * (1 - seg(t, tD0 + 0.2, tD0 + 1.2));
  if (nameOp > 0.01) {
    gal('nm.m', -MX, -2, 78, 'MEN', { size: 14, ls: '0.2em', weight: 500, anchor: 'middle', fill: mixM, op: nameOp, role: 'secondary', fam: 'mono' });
    gal('nm.w', MX, -2, 78, 'WOMEN', { size: 14, ls: '0.2em', weight: 500, anchor: 'middle', fill: mixW, op: nameOp, role: 'secondary', fam: 'mono' });
  }

  /* CASE: counters ride the top of each tower; after the sweep they read admitted / applied */
  if (t >= kn('tBuild0', 17.0) && t < 36.2) {
    const op = 1 - seg(t, 35.2, 36.1);
    for (const sx of ['m', 'w']) {
      const L = lay[sx], h = Math.min(layers, L.H), shown = L.cum[h], full = h >= L.H;
      const sgn = sx === 'm' ? -1 : 1, topY = -(h * EX.CELL + EX.PAD) - 8;
      const ad = t >= tA0 + tAd * 0.5, lab = ad ? fmt(sum(SEX[sx].a)) + ' / ' + fmt(L.N) : fmt(shown);
      const colr = sx === 'm' ? mixM : mixW;
      gal('ct.' + sx, sgn * (MX + 58), topY, 0, lab, { size: 28, weight: 500, anchor: sgn < 0 ? 'end' : 'start', fill: colr, op, role: 'must-read', dx: sgn * 6, dy: 0 });
      if (full) gal('cs.' + sx, sgn * (MX + 58), topY, 0, ad ? 'ADMITTED / APPLIED' : (sx === 'm' ? 'MEN APPLIED' : 'WOMEN APPLIED'), { size: 14, ls: '0.12em', anchor: sgn < 0 ? 'end' : 'start', fill: C.muted, op: op * 0.95, role: 'secondary', dx: sgn * 6, dy: 20 });
    }
  }

  const later = [];
  /* COUNT: headline numerals (morph) on both flanks, counts under them */
  const numOp = seg(t, 36.0, 36.9) * (1 - seg(t, tW0 - 0.2, tW0 + 0.6));
  if (numOp > 0.01) {
    const hy = kn('headY', 36), mxp = kn('headX', 22);
    for (const sx of ['m', 'w']) {
      const g = paintNumeral(p, sx, t, kn, sx === 'm' ? mixM : mixW, numOp);
      const x0 = sx === 'm' ? mxp : 960 - mxp - NUM.w;
      later.push(() => { p.resetShader(); p.tint(255, 255 * numOp); p.imageMode(p.CORNER); p.image(g, x0, hy, NUM.w, NUM.h); p.noTint(); });
      const m = morphAt(kn, t), idx = m.u > 0.5 ? m.i + 1 : m.i;
      const sub = idx === 0 ? (sx === 'm' ? 'OF MEN ADMITTED' : 'OF WOMEN ADMITTED') : (sx === 'm' ? 'MEN · DEPT ' : 'WOMEN · DEPT ') + D6[idx - 1];
      tx('hn.' + sx, x0 + NUM.w / 2, hy + NUM.h + 8, sub, { size: 14, ls: '0.14em', weight: 500, anchor: 'middle', fill: C.muted, op: numOp, role: 'secondary' });
      if (idx === 0 && t >= 36.2) tx('hr.' + sx, x0 + NUM.w / 2, hy + NUM.h + 30, fmt(sum(SEX[sx].a)) + ' ÷ ' + fmt(sum(SEX[sx].n)), { size: 14, weight: 500, anchor: 'middle', fill: C.ink, op: numOp * seg(t, 36.2, 36.8), role: 'secondary' });
    }
  }

  /* split: department letters on the floor, counts over the active pair, verdict tags at the wide shot */
  if (t >= tD0 + 2.0) {
    const lo = seg(t, tD0 + 2.0, tD0 + 3.2);
    for (let d = 0; d < 6; d++) {
      const zc = EX.pairZ(kn, d), near = clamp(1 - Math.abs(rig.tz - zc) / (P * 0.7)), wideK = sstep(tW0, tW1, t);
      const act = Math.max(near * (1 - wideK), wideK * 0.9 + 0.1);
      gal('dl.' + d, -(SX + 80), -2, zc, D6[d], { fam: 'disp', size: 28, anchor: 'middle', fill: C.ink, op: lo * (0.35 + 0.65 * act), role: 'must-read', dy: 8 });
      const showCounts = near * (1 - wideK) * seg(t, tD1 - 0.8, tD1 + 0.2);
      if (showCounts > 0.02) {
        for (const sx of ['m', 'w']) {
          const sl = lay[sx].slabs[d], sg = sx === 'm' ? -1 : 1, zb = zc + (sx === 'm' ? 36 : -36), hh = sl.L * EX.CELL + EX.PAD;
          gal('pc.' + sx + d, sg * SX, -hh - 12, zb, sl.a + ' ÷ ' + sl.n, { size: 14, weight: 500, anchor: 'middle', fill: sx === 'm' ? mixM : mixW, op: showCounts, role: 'secondary' });
        }
      }
      if (wideK > 0.02) {
        const hi = HIGHER[d], sg = hi === 'm' ? -1 : 1, sl = lay[hi].slabs[d], zb = zc + (hi === 'm' ? 36 : -36), hh = sl.L * EX.CELL + EX.PAD;
        gal('hi.' + d, sg * SX, -hh - 34, zb, hi === 'w' ? 'WOMEN' : 'MEN', { size: 14, ls: '0.12em', weight: 500, anchor: 'middle', fill: hi === 'w' ? mixW : mixM, op: wideK * seg(t, kn('tReveal', 57.2), kn('tReveal', 57.2) + 0.9) * (1 - seg(t, 62.0, 62.6)), role: 'secondary' });
      }
    }
  }

  /* the reveal: tally + the committed number against the truth */
  const tr = seg(t, kn('tReveal', 57.2) + 0.2, kn('tReveal', 57.2) + 1.0) * (1 - seg(t, 62.0, 62.6));
  if (tr > 0.01) {
    tx('rv.h', 480, 74, 'WOMEN HIGHER IN ' + sum(HIGHER.map((h) => (h === 'w' ? 1 : 0))) + ' OF 6', { size: 28, weight: 500, anchor: 'middle', fill: C.ink, op: tr, role: 'must-read' });
    // strip 0..6 : TRUTH (worse in) vs YOU
    const truth = sum(HIGHER.map((h) => (h === 'm' ? 1 : 0))), bx = 640, by = 436, pitch = 40;
    tx('rv.s', bx, by - 36, 'WOMEN WORSE IN', { size: 14, ls: '0.14em', weight: 500, fill: C.muted, op: tr, role: 'secondary' });
    for (let k = 0; k <= 6; k++) tx('rv.n' + k, bx + pitch * k, by, String(k), { size: 16, weight: 500, anchor: 'middle', fill: k === truth ? C.ink : C.muted, op: tr, role: 'secondary' });
    K.rc('rv.t', 'marks', bx + pitch * truth - 12, by - 18, 24, 24, { stroke: C.ink, w: 1.6, rx: 12, op: tr });
    tx('rv.tl', bx + pitch * truth, by + 22, 'TRUTH', { size: 14, ls: '0.1em', weight: 500, anchor: 'middle', fill: C.ink, op: tr, role: 'secondary' });
    if (guess != null) {
      K.rc('rv.g', 'marks', bx + pitch * guess - 15, by - 21, 30, 30, { stroke: C.soft, w: 1.8, rx: 15, op: tr * seg(t, kn('tReveal', 57.2) + 0.6, kn('tReveal', 57.2) + 1.2) });
      tx('rv.gl', bx + pitch * guess, by + 22, 'YOU', { size: 14, ls: '0.1em', weight: 500, anchor: 'middle', fill: C.soft, op: tr * seg(t, kn('tReveal', 57.2) + 0.6, kn('tReveal', 57.2) + 1.2), role: 'secondary' });
    }
  }

  /* MONDAY */
  if (t >= 62.0) {
    const op = seg(t, 62.0, 62.8);
    tx('mo.q', 64, 112, K.typed('Same mix of leads?', t, 63.0, 26), { fam: 'disp', size: 48, fill: C.ink, op, role: 'must-read' });
    tx('mo.s', 64, 156, K.typed('Split by segment. Then compare.', t, 64.4, 34), { fam: 'sans', size: 28, weight: 500, fill: C.ink, op, role: 'must-read' });
  }

  if (later.length) K.flat(() => later.forEach((f) => f()));   // flat HUD last: K.flat swaps the camera, every worldToScreen pin above needed the gallery camera

  /* neon post: the reveal frame only (a bump around tReveal), skipped everywhere else so the cost is paid once */
  const nT0 = kn('neonT0', 57.4), nT1 = kn('neonT1', 60.6), ns = kn('neonStrength', 1.0);
  const nk = ns * sstep(nT0, nT0 + 0.5, t) * (1 - sstep(nT1 - 0.8, nT1, t));
  if (nk > 0.01 && S.neon) {
    const sh = S.neon;
    sh.setUniform('uRes', [960, 540]); sh.setUniform('uRadius', kn('neonRadius', 16)); sh.setUniform('uGain', nk * 0.04);
    sh.setUniform('uThresh', kn('neonThresh', 0.42)); sh.setUniform('uCore', kn('neonCore', 0.5)); sh.setUniform('uTint', [1, 1, 1]);
    p.filter(sh);
  }
  K.info = { rig, nk, layers };
}

window.FILM_RENDER = { setup, render, ground: false };
})();
