#!/usr/bin/env python3
"""lib/bake_glyphs.py · bakes the outlines of 0-9 and % from the brand display face (Fraunces 300 italic, vendor/fonts)
into lib/glyphs.js, so morph-type needs no runtime font (p.loadFont / textToContours) in the WEBGL page.
Quadratic curves flattened to polylines (7 steps), integer font units, y down. Deterministic."""
import json, os, sys
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import DecomposingRecordingPen
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.abspath(os.path.join(HERE, *[".."] * 6))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "vendor", "fonts", "fraunces-latin-300-italic.woff2")
CHARS = "0123456789%"
f = TTFont(SRC); gs = f.getGlyphSet(); cm = f.getBestCmap(); upm = f["head"].unitsPerEm
def flat(rec):
    out, cur, start = [], None, None
    def q(p0, p1, p2, n=7):
        return [((1 - u) ** 2 * p0[0] + 2 * (1 - u) * u * p1[0] + u * u * p2[0], (1 - u) ** 2 * p0[1] + 2 * (1 - u) * u * p1[1] + u * u * p2[1]) for u in [i / n for i in range(1, n + 1)]]
    pts = []
    for op, args in rec:
        if op == "moveTo": pts = [args[0]]; cur = args[0]
        elif op == "lineTo": pts.append(args[0]); cur = args[0]
        elif op == "qCurveTo":
            a = list(args)
            if a[-1] is None:                       # closed contour made only of off-curve points
                raise SystemExit("implied-start contour not handled")
            offs, end = a[:-1], a[-1]
            for i, o in enumerate(offs):
                nxt = end if i == len(offs) - 1 else ((o[0] + offs[i + 1][0]) / 2, (o[1] + offs[i + 1][1]) / 2)
                pts += q(cur, o, nxt); cur = nxt
        elif op == "curveTo":
            p1, p2, p3 = args
            for u in [i / 8 for i in range(1, 9)]:
                pts.append(((1 - u) ** 3 * cur[0] + 3 * (1 - u) ** 2 * u * p1[0] + 3 * (1 - u) * u * u * p2[0] + u ** 3 * p3[0],
                            (1 - u) ** 3 * cur[1] + 3 * (1 - u) ** 2 * u * p1[1] + 3 * (1 - u) * u * u * p2[1] + u ** 3 * p3[1]))
            cur = p3
        elif op in ("closePath", "endPath"):
            if len(pts) > 2:
                if abs(pts[0][0] - pts[-1][0]) < 1e-6 and abs(pts[0][1] - pts[-1][1]) < 1e-6: pts.pop()
                out.append(pts)
            pts = []
    return out
def rdp(pts, eps=2.2):
    """Douglas-Peucker on a closed polyline (split at the farthest pair of anchors), tolerance in font units."""
    def seg(a, b):
        if len(a) < 3: return a
        (x0, y0), (x1, y1) = a[0], a[-1]; dx, dy = x1 - x0, y1 - y0; L = (dx * dx + dy * dy) ** .5 or 1e-9
        d = [abs(dy * (p[0] - x0) - dx * (p[1] - y0)) / L for p in a[1:-1]]; m = max(d)
        if m <= eps: return [a[0], a[-1]]
        i = d.index(m) + 1; return seg(a[:i + 1], 0)[:-1] + seg(a[i:], 0)
    n = len(pts); j = max(range(n), key=lambda k: (pts[k][0] - pts[0][0]) ** 2 + (pts[k][1] - pts[0][1]) ** 2)
    a = seg(pts[:j + 1], 0); b = seg(pts[j:] + [pts[0]], 0)
    return a[:-1] + b[:-1]
G = {}
for ch in CHARS:
    name = cm[ord(ch)]; pen = DecomposingRecordingPen(gs); gs[name].draw(pen)
    cs = [[int(round(v)) for p in rdp(c) for v in (p[0], -p[1])] for c in flat(pen.value)]
    G[ch] = {"a": f["hmtx"][name][0], "c": cs}
cap = f["OS/2"].sCapHeight if hasattr(f["OS/2"], "sCapHeight") else 700
body = "/* lib/glyphs.js · generated by lib/bake_glyphs.py from %s · outlines of 0-9 and %% */\nwindow.FILM_GLYPHS=%s;\n" % (
    os.path.basename(SRC), json.dumps({"upm": upm, "cap": cap, "g": G}, separators=(",", ":")))
open(os.path.join(HERE, "glyphs.js"), "w").write(body); print("glyphs.js", len(body), "bytes", {c: len(G[c]['c']) for c in CHARS})
