#!/usr/bin/env python3
"""Derive compact single-line glyph data for THE MARGIN from EMS single-stroke SVG fonts (SIL OFL).
   EMS Allure (S. B. Michaels, after Allura by R. Leuschke) -> hand A (author, ink)
   EMS Felix  (S. B. Michaels, after Felipa by Fontstage)    -> hand B (viewer, pencil)
   Curves flattened, RDP-simplified, quantised to 1/4 unit, y flipped (y down, baseline 0).
   Usage: python3 -I extract_glyphs.py <svg_fonts_dir> <out.js>"""
import re, sys, html, json, math

def parse(path):
    s = open(path, encoding='utf-8').read()
    dflt = float(re.search(r'<font [^>]*horiz-adv-x="([\d.]+)"', s).group(1))
    g = {}
    for m in re.finditer(r'<glyph\b([^>]*)/?>', s):
        a = m.group(1); u = re.search(r'unicode="([^"]*)"', a)
        if not u: continue
        ch = html.unescape(u.group(1))
        if len(ch) != 1: continue
        adv = re.search(r'horiz-adv-x="([-\d.]+)"', a); d = re.search(r'\sd="([^"]*)"', a)
        g[ch] = (float(adv.group(1)) if adv else dflt, d.group(1) if d else '')
    return g

def flatten(d, seg=10):
    t = re.findall(r'[MLCZmlcz]|-?\d*\.?\d+(?:[eE][-+]?\d+)?', d); i = 0; out = []; cur = None; cmd = None; x = y = 0
    def num():
        nonlocal i; v = float(t[i]); i += 1; return v
    while i < len(t):
        if re.match(r'[A-Za-z]', t[i]): cmd = t[i]; i += 1
        if cmd == 'M': x, y = num(), num(); cur = [(x, y)]; out.append(cur); cmd = 'L'
        elif cmd == 'L': x, y = num(), num(); cur.append((x, y))
        elif cmd == 'C':
            x1, y1, x2, y2, x3, y3 = [num() for _ in range(6)]; x0, y0 = x, y
            n = max(2, min(seg, int(math.hypot(x3 - x0, y3 - y0) / 18) + 2))
            for k in range(1, n + 1):
                u = k / n; a = (1-u)**3; b = 3*(1-u)**2*u; c = 3*(1-u)*u*u; e = u**3
                cur.append((a*x0+b*x1+c*x2+e*x3, a*y0+b*y1+c*y2+e*y3))
            x, y = x3, y3
        elif cmd in 'Zz':
            if cur: cur.append(cur[0])
            cmd = None
        else: raise ValueError(cmd)
    return [s for s in out if len(s) > 1]

def rdp(pts, eps):
    if len(pts) < 3: return pts
    (x0, y0), (x1, y1) = pts[0], pts[-1]; dx, dy = x1 - x0, y1 - y0; L = math.hypot(dx, dy) or 1e-9
    dmax, idx = 0, 0
    for i in range(1, len(pts) - 1):
        px, py = pts[i]; dd = abs(dy * px - dx * py + x1 * y0 - y1 * x0) / L if math.hypot(dx, dy) > 1e-9 else math.hypot(px - x0, py - y0)
        if dd > dmax: dmax, idx = dd, i
    if dmax > eps: return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]

CHARS = [chr(c) for c in range(32, 127)] + list('±×²³—–“”°·')

def build(path, eps=2.2):
    g = parse(path); out = {}
    for ch in CHARS:
        if ch not in g: continue
        adv, d = g[ch]; strokes = []
        for st in flatten(d):
            st = rdp(st, eps)
            q = []
            for x, y in st: q += [round(x / 4), round(-y / 4)]
            # drop consecutive duplicates
            dd = q[:2]
            for i in range(2, len(q), 2):
                if q[i] != dd[-2] or q[i + 1] != dd[-1]: dd += q[i:i + 2]
            if len(dd) >= 4: strokes.append(dd)
        out[ch] = [round(adv / 4)] + strokes
    # metrics in quarter units (y down): x-height from 'x', cap from 'H'
    def top(ch): return min(v for s in out[ch][1:] for v in s[1::2])
    met = {'xh': -top('x'), 'cap': -top('H'), 'asc': -top('l'), 'desc': max(v for s in out['g'][1:] for v in s[1::2])}
    return {'m': met, 'g': out}

if __name__ == '__main__':
    src, dst = sys.argv[1], sys.argv[2]
    A = build(src + '/EMSAllure.svg'); B = build(src + '/EMSFelix.svg')
    js = ('/* THE MARGIN — single-line glyph data (generated by tools/extract_glyphs.py; do not edit).\n'
          '   Hand A derived from EMS Allure (Sheldon B. Michaels, after Allura by Rob Leuschke, TypeSETit) and hand B from\n'
          '   EMS Felix (Sheldon B. Michaels, after Felipa by Fontstage); both SIL Open Font License 1.1; SVG conversion\n'
          '   Windell H. Oskay / Evil Mad Scientist. Format: char -> [advance, stroke, …], stroke = flat [x,y,…] in\n'
          '   quarter-units (em = 250), y down, baseline 0. */\n'
          'const MARGIN_GLYPHS = ' + json.dumps({'A': A, 'B': B}, separators=(',', ':')) + ';\n')
    open(dst, 'w').write(js)
    print('A', A['m'], len(A['g']), 'B', B['m'], len(B['g']), 'bytes', len(js))
