/* a-bell-from-dice draft B · film.js is GENERATED by lib/assemble.py from lib/film.src.js (edit that file). */
/* a-bell-from-dice · draft B · register "the rain"
   100,000 rolls of five dice (mulberry32 seed 1733, one stream, die j of roll i = draw 5i+j) fall as marks from above
   into six flat bins by the first die; the camera cranes to a plan view and the SAME marks travel (route a: each mark
   carries two homes in the data texture, from = its first-die slot, to = its sum slot, a layer stagger between) into
   26 columns by sum; the camera comes down a quarter turn and the bell rises like a skyline; it pushes into the tail,
   the last lit street. Then the sums as counted cells (gl-volume, x = sum, z = first die) with a cut that counts as it
   travels to the 25 | 26 edge, and the exact bell as a glass outline the counted bars fill (flat inset, SVG).
   One clock: render(t) is a pure function of t; every order and slot is built once in setup from the seed. */
(function () {
'use strict';
const F = window.FILM, P = F.params, A = window.ARSENAL, K0 = window.KIT;
const GI = A.patterns['gl-instances'].api, RIG = A.patterns['gl-camera-rig'].rig, VOL = A.patterns['gl-volume'], LAB = A.patterns['gl-labels'];
const kn = (n, f) => K0.knob(n, f);
const KN = {
  rainT0: kn('rainT0', 12.4), rainT1: kn('rainT1', 23.6), rainWin: kn('rainWin', 0.02), rainDrop: kn('rainDrop', 420),
  landAt: kn('landAt', 24), cube: kn('cube', 1.6), pitch: kn('pitch', 2),
  binFX: kn('binFX', 16), binFZ: kn('binFZ', 12), binGap: kn('binGap', 100), colFX: kn('colFX', 10), colFZ: kn('colFZ', 10), colGap: kn('colGap', 10),
  facesAt: kn('facesAt', 28.6), pinFirstAt: kn('pinFirstAt', 34), pinFirstOut: kn('pinFirstOut', 40),
  sortT0: kn('sortT0', 44), sortT1: kn('sortT1', 47), sortStagger: kn('sortStagger', 0.55), sortLift: kn('sortLift', 40),
  beliefAt: kn('beliefAt', 47), beliefOut: kn('beliefOut', 58), pinColAt: kn('pinColAt', 55.2), pinColOut: kn('pinColOut', 58),
  tailLitAt: kn('tailLitAt', 58.4), pinTailAt: kn('pinTailAt', 61), pinTailOut: kn('pinTailOut', 65.4),
  stackOut0: kn('stackOut0', 65.4), stackOut1: kn('stackOut1', 66.2),
  volBuild0: kn('volBuild0', 66.6), volBuild1: kn('volBuild1', 70), volCutIn: kn('volCutIn', 70), volCutEnd: kn('volCutEnd', 76),
  volCutTo: kn('volCutTo', 0.8065), volTail: kn('volTail', 25.5), volCutDim: kn('volCutDim', 0.35),
  volH: kn('volH', 210), volZ: kn('volZ', 200), volGap: kn('volGap', 0.16), volAlpha: kn('volAlpha', 0.55),
  ratioAt: kn('ratioAt', 82), insetAt: kn('insetAt', 86), glassT0: kn('glassT0', 92), glassT1: kn('glassT1', 94),
  fillT0: kn('fillT0', 94), fillT1: kn('fillT1', 96.5), waysAt: kn('waysAt', 96), expTailAt: kn('expTailAt', 98), agreeAt: kn('agreeAt', 102),
  volOut0: kn('volOut0', 107), volOut1: kn('volOut1', 108.2),
  diceAt: kn('diceAt', 2), sumAt: kn('sumAt', 4.2), hookLineAt: kn('hookLineAt', 8.2), hookOut: kn('hookOut', 11.6), mondayAt: kn('mondayAt', 108.3),
  countSize: kn('countSize', 56), pinSize: kn('pinSize', 28), subSize: kn('subSize', 14), noteSize: kn('noteSize', 16),
  insetX: kn('insetX', 576), insetW: kn('insetW', 352), insetY: kn('insetY', 100), insetH: kn('insetH', 316),
  labHold: kn('labHold', 4), labLeader: kn('labLeader', 20), litAmb: kn('litAmb', 0.55), litKey: kn('litKey', 0.45),
};
const DUR = F.dur, N = P.rolls, SUMS = 26, S0 = P.dice, TAILCUT = P.tailCut;
const fmt = (n) => String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
const seg = (t, a, b) => clamp((t - a) / (b - a));
const sm = (u) => { u = clamp(u); return u * u * (3 - 2 * u); };
const win = (t, a, b, f = 0.4) => sm(seg(t, a - f, a)) * (1 - sm(seg(t, b - f, b)));   // fade in before a, out before b

/* the two-home vertex shader: texel 0 = first-die slot (xyz) + re-sort delay; texel 1 = sum slot (xyz) + tail flag.
   Rows are in arrival order (roll index), so the count-in is the instance range: model(geom, ceil(k / chunk)). */
const VERT = `#version 300 es
precision highp float; precision highp int;
in vec3 aPosition; in vec3 aNormal; in vec2 aTexCoord;
uniform mat4 uModelViewMatrix; uniform mat4 uProjectionMatrix;
uniform sampler2D uData; uniform int uTexW; uniform int uChunk; uniform float uStep;
uniform float uKc; uniform float uFront; uniform float uWin; uniform float uSize; uniform float uDrop;
uniform float uMove; uniform float uStag; uniform float uLift; uniform float uTail; uniform float uFade;
uniform vec3 uInk; uniform vec3 uAcc; uniform vec3 uHot; uniform vec3 uBg;
out vec3 vN; out vec2 vUV; out vec4 vCol;
vec4 fetch(int j){ return texelFetch(uData, ivec2(j % uTexW, j / uTexW), 0); }
void main(){
  float j = floor(aPosition.x / uStep + 0.5); vec3 q = vec3(aPosition.x - j * uStep, aPosition.yz);
  int id = gl_InstanceID * uChunk + int(j);
  vN = aNormal; vUV = aTexCoord;
  if (float(id) >= uKc) { gl_Position = vec4(2.0, 2.0, 2.0, 1.0); vCol = vec4(0.0); return; }
  vec4 a = fetch(2 * id), b = fetch(2 * id + 1);
  float age = clamp((uFront - float(id)) / uWin, 0.0, 1.0);
  vec3 pa = a.xyz - vec3(0.0, uDrop * (1.0 - age * age), 0.0);
  float m = clamp((uMove - a.w * uStag) / max(1e-4, 1.0 - uStag), 0.0, 1.0); m = m * m * (3.0 - 2.0 * m);
  vec3 pos = mix(pa, b.xyz, m) - vec3(0.0, uLift * sin(3.14159265 * m), 0.0);
  vec3 col = mix(uInk, uAcc, uTail * b.w);
  col = mix(uHot, col, smoothstep(0.0, 1.0, age));
  vCol = vec4(mix(uBg, col, uFade), 1.0);
  gl_Position = uProjectionMatrix * uModelViewMatrix * vec4(pos + q * uSize, 1.0);
}`;

let S = null;   // everything built once in setup

/* the generator, exactly as brief.md: one stream, die j of roll i = draw 5i + j, face = 1 + floor(u * 6) */
function mulberry32(a) { return function () { a |= 0; a = a + 0x6D2B79F5 | 0;
  let t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
  return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
function roll() {
  const rnd = mulberry32(P.seed), first = new Uint8Array(N), sum = new Uint8Array(N);
  for (let i = 0; i < N; i++) { let s = 0; for (let j = 0; j < S0; j++) { const f = 1 + Math.floor(rnd() * P.faces); if (j === 0) first[i] = f; s += f; } sum[i] = s; }
  // in-film assertion: the stream must reproduce the claims count for count, and the checkpoints at their k
  const bySum = new Array(31).fill(0), byFirst = new Array(7).fill(0), mat = Array.from({ length: SUMS }, () => new Array(6).fill(0));
  const ck = (F.checks && F.checks.at) || {}, bad = [];
  let tail = 0, f6 = 0, ss = 0;
  for (let i = 0; i < N; i++) {
    bySum[sum[i]]++; byFirst[first[i]]++; mat[sum[i] - 5][first[i] - 1]++;
    if (sum[i] > TAILCUT) tail++; if (first[i] === 6) f6++; ss += sum[i];
    const c = ck[String(i + 1)]; if (c && (c.tail !== tail || c.first6 !== f6 || c.sumOfSums !== ss)) bad.push('checkpoint ' + (i + 1));
  }
  for (let s = 5; s <= 30; s++) if (bySum[s] !== P['sim' + s]) bad.push('sim' + s);
  for (let f = 1; f <= 6; f++) if (byFirst[f] !== P['first' + f]) bad.push('first' + f);
  if (sum[0] !== P.roll0Sum) bad.push('roll0Sum');
  if (bad.length) throw new Error('a-bell-from-dice: the generator does not reproduce the claims: ' + bad.join(', '));
  window.__bell = { ok: true, tail, first6: f6, sumOfSums: ss };
  return { first, sum, bySum, byFirst, mat };
}

/* slots: a stack fills bottom-up by arrival rank inside its category; footprint fx * fz cubes per layer */
function stackGeom(nCat, fx, fz, gap, c) {
  const w = fx * c, pitch = w + gap, L = fx * fz;
  return { w, pitch, L, cx: (k) => (k - (nCat - 1) / 2) * pitch, top: (n) => -Math.ceil(n / L) * c, c, fx, fz };
}
function slot(G, k, j, out, o) {
  const layer = Math.floor(j / G.L), cell = j % G.L, cx = cell % G.fx, cz = Math.floor(cell / G.fx);
  out[o] = G.cx(k) - G.w / 2 + (cx + 0.5) * G.c; out[o + 1] = -(layer + 0.5) * G.c; out[o + 2] = (cz - (G.fz - 1) / 2) * G.c;
  return layer;
}

/* SVG: one die face with its pips (no digits) */
const PIPS = { 1: [[0, 0]], 2: [[-1, -1], [1, 1]], 3: [[-1, -1], [0, 0], [1, 1]], 4: [[-1, -1], [1, -1], [-1, 1], [1, 1]],
  5: [[-1, -1], [1, -1], [0, 0], [-1, 1], [1, 1]], 6: [[-1, -1], [1, -1], [-1, 0], [1, 0], [-1, 1], [1, 1]] };
function die(K, key, cx, cy, s, v, op, col) {
  if (op <= 0.01) return;
  K.rc(key + 'f', 'marks', cx - s / 2, cy - s / 2, s, s, { stroke: col || K.C.ink, w: Math.max(1.2, s / 28), rx: s * 0.16, op });
  PIPS[v].forEach((q, i) => K.E(key + 'p' + i, 'circle', 'marks', { cx: (cx + q[0] * s * 0.27).toFixed(1), cy: (cy + q[1] * s * 0.27).toFixed(1), r: (s * 0.085).toFixed(2), fill: col || K.C.ink, opacity: op.toFixed(3) }));
}

/* labels: gl-labels solves placement (pure of t, debounced); the film emits K.ln / K.tx with roles */
function pins(K, t, key, anchors, op, reserve) {
  if (op <= 0.01) return;
  const r = LAB.solve(t, S.camFn, anchors, { hold: KN.labHold, leader: KN.labLeader, sticky: 'window', occlusion: false, reserve,
    measure: S.measure, measureKey: 'k2' });
  for (const q of r.placements) {
    const k = key + q.id, fill = K.C[q.color] || K.C.ink, anc = q.align === 'right' ? 'end' : q.align === 'center' ? 'middle' : 'start';
    K.rc(k + 'b', 'labels', q.box[0], q.box[1], q.box[2] - q.box[0], q.box[3] - q.box[1], { fill: K.C.paper, fo: 0.72, op });
    K.ln(k + 'l', 'labels', q.lead[0], q.lead[1], q.lead[2], q.lead[3], { stroke: fill, w: 1.2, op });
    K.E(k + 'd', 'circle', 'labels', { cx: q.ax.toFixed(1), cy: q.ay.toFixed(1), r: 2.6, fill, opacity: op.toFixed(3) });
    K.tx(k + 't', 'labels', q.tx, q.ty, q.text, { fam: q.fam, size: q.size, anchor: anc, fill, op, role: q.dataRole });
    if (q.sub) K.tx(k + 's', 'labels', q.tx, q.sy, q.sub, { fam: q.subFam, size: Math.max(q.subSize, 14), anchor: anc, fill: K.C.muted, op, role: q.subDataRole === 'chrome' ? 'secondary' : q.subDataRole });
  }
}

window.FILM_RENDER = {
  ground: false,
  async setup(p, K) {
    const R = roll(), c = KN.pitch;
    const GA = stackGeom(6, KN.binFX, KN.binFZ, KN.binGap, c), GB = stackGeom(SUMS, KN.colFX, KN.colFZ, KN.colGap, c);
    // data texture: 2 texels (8 floats) per mark, in arrival order
    const TEXW = GI.TEXW, TH = Math.ceil(2 * N / TEXW), buf = new Float32Array(TEXW * TH * 4);
    const fillA = new Array(6).fill(0), fillB = new Array(SUMS).fill(0), layB = new Uint16Array(N);
    let maxLayB = 1;
    for (let i = 0; i < N; i++) {
      const o = i * 8, f = R.first[i] - 1, s = R.sum[i] - 5;
      slot(GA, f, fillA[f]++, buf, o);
      layB[i] = slot(GB, s, fillB[s]++, buf, o + 4); maxLayB = Math.max(maxLayB, layB[i]);
      buf[o + 7] = R.sum[i] > TAILCUT ? 1 : 0;
    }
    for (let i = 0; i < N; i++) buf[i * 8 + 3] = layB[i] / maxLayB;   // re-sort delay: bottom layers travel first
    const st = { N, buf, fb: p.createFramebuffer({ width: TEXW, height: TH, density: 1, format: p.FLOAT, channels: p.RGBA, antialias: false, depth: false, textureFiltering: p.NEAREST }) };
    GI.upload(p, st);
    st.chunk = 256;
    const faces = ['-y', '+z'];   // top + front only (bars-100k: 6 s -> 1.0 s); the camera never sees a back or a bottom
    st.geom = p.buildGeometry(() => { p.noStroke(); for (let j = 0; j < st.chunk; j++) { p.push(); p.translate(j * GI.STEP, 0, 0);
      for (const fc of faces) { p.push(); GI.FACE[fc](p); p.plane(1, 1); p.pop(); } p.pop(); } });
    st.sh = p.createShader(VERT, GI.FRAG);
    // the camera rig: scene points = the 26 column tops (data targets for lookat), script from film.json, keys from knobs
    const colTop = (s) => GB.top(R.bySum[s]);
    const scene = { points: Array.from({ length: SUMS }, (_, i) => [GB.cx(i), colTop(i + 5), 0]) };
    const script = RIG.fromKnobs(F.rig, (name, cur) => K.knob(name, cur), scene);
    const rig = RIG.compile(script, scene);
    const cam = p.createCamera();
    // tokens for the arsenal modules (pack roles, never hex literals)
    const BC = K.BRAND.color, TOK = { id: K.BRAND.id, color: { bg: BC.bg, ink: BC.ink, accent: BC.accent, accent2: BC.accent2 || BC.muted, muted: BC.muted,
      line: BC.line || BC.muted, chalk: BC.chalk || BC.ink, panel: BC.panel || BC.bg }, type: K.BRAND.type };
    const rgb = (h) => GI.rgb(p, h), mixc = (a, b, u) => rgb(p.lerpColor(p.color(a), p.color(b), u));
    // the volume: the 26 sums x 6 first-die faces as counted cells (counts from the same stream)
    const VP = Object.assign({}, VOL.params, {
      dur: DUR, data: R.mat, dataKind: 'counts', range: [[4.5, 30.5], [0.5, 6.5]], axisNames: ['SUM', 'FIRST DIE'],
      size: [SUMS * GB.pitch, KN.volH, KN.volZ], gap: KN.volGap, alpha: [KN.volAlpha, KN.volAlpha], tail: KN.volTail, tailAxis: 'x',
      tailIn: [KN.volCutEnd / DUR, (KN.volCutEnd + 0.6) / DUR], build: [KN.volBuild0 / DUR, KN.volBuild1 / DUR], stagger: 0.35,
      cutIn: [KN.volCutIn / DUR, KN.volCutEnd / DUR], cutFrom: 0, cutTo: KN.volCutTo, cutDim: KN.volCutDim, cutX: true, pin: false,
      camAt: (u) => { const q = RIG.at(rig, u * DUR); return { eye: q.eye, apply: (cm) => RIG.apply(p, cm, q, rig) }; },
    });
    const VST = await VOL.setup(p, { seed: F.seed, tokens: TOK }, VP);
    const camFn = (t) => { const q = RIG.at(rig, t); return { eye: q.eye, look: q.center, up: q.up, fov: q.fov, aspect: K.W / K.H }; };
    const measure = (s, z, f) => String(s).length * z * (f === 'disp' ? K.ADV.disp : K.ADV.mono);
    // pin anchors (one stable array per window: the solver memoises by identity)
    const yA = (f) => GA.top(R.byFirst[f + 1]) - 3, yB = (s) => GB.top(R.bySum[s]) - 3;
    const an = (id, x, y, text, color, sub, pr) => ({ id, x, y, z: 0, text, sub: sub || null, role: 'result', color, priority: pr || 1, size: KN.pinSize });
    const AN = {
      bins: [0, 1, 2, 3, 4, 5].map((f) => an('f' + (f + 1), GA.cx(f), yA(f), fmt(P['first' + (f + 1)]), 'ink', null, 6 - f)),
      cols: [an('s17', GB.cx(12), yB(17), fmt(P.sim17), 'ink', 'SUM ' + P.modeLo, 4), an('s18', GB.cx(13), yB(18), fmt(P.sim18), 'ink', 'SUM ' + P.modeHi, 4),
        an('s5', GB.cx(0), yB(5), fmt(P.sim5), 'ink', 'SUM ' + P.sumMin, 2), an('s30', GB.cx(25), yB(30), fmt(P.sim30), 'ink', 'SUM ' + P.sumMax, 2)],
      tail: [26, 27, 28, 29, 30].map((s) => an('t' + s, GB.cx(s - 5), yB(s), fmt(P['sim' + s]), 'accent', null, 31 - s)),
    };
    S = { R, GA, GB, st, rig, cam, TOK, VP, VST, camFn, measure, AN, rgb, mixc, colTop,
      IP: { dur: DUR, countIn: [KN.rainT0 / DUR, KN.rainT1 / DUR], win: KN.rainWin, countEase: 'smooth' },
      floorW: Math.max(6 * GA.pitch, SUMS * GB.pitch) + 40, floorD: Math.max(GA.fz, GB.fz) * c + 40 };
    p.setCamera(K.cam0);
  },

  render(t, s, K) {
    const p = K.p, C = K.C, B = S.TOK.color;
    const ch = K.chapterAt(t);
    if (ch) K.tx('eb', 'labels', 40, 50, ch.eyebrow, { size: 12, fill: C.muted, ls: '0.14em', role: 'chrome' });
    const pose = RIG.at(S.rig, t), W2S = (x, y, z) => RIG.worldToScreen(pose, [x, y, z], K.W, K.H);
    const capBand = [0, 440, 960, 540];

    /* ── HOOK · the throw (flat SVG): roll 0 is 2-3-2-5-6 ───────────────────────────────────────────────── */
    const hookOp = 1 - sm(seg(t, KN.hookOut, KN.hookOut + 0.6));
    if (t < KN.hookOut + 0.7) {
      const f0 = (F.checks && F.checks.first10 && F.checks.first10[0].faces) || [2, 3, 2, 5, 6];
      for (let j = 0; j < 5; j++) {
        const u = K.eout(seg(t, KN.diceAt + 0.4 * j, KN.diceAt + 0.4 * j + 0.45));
        die(K, 'hd' + j, 300 + j * 90, 170 - 40 * (1 - u), 62, f0[j], u * hookOp);
      }
      const su = sm(seg(t, KN.sumAt, KN.sumAt + 0.5)) * hookOp;
      if (su > 0) {
        K.tx('hs', 'labels', 480, 300, String(P.roll0Sum), { fam: 'disp', size: 76, anchor: 'middle', op: su, role: 'must-read' });
        K.tx('hs2', 'labels', 480, 330, 'THE SUM OF ONE ROLL OF FIVE DICE', { size: 14, anchor: 'middle', fill: C.muted, op: su, ls: '0.1em', role: 'secondary' });
      }
      const bu = sm(seg(t, KN.hookLineAt, KN.hookLineAt + 0.8)) * hookOp;
      if (bu > 0) {
        const x0 = 230, x1 = 730, y = 404, dx = (x1 - x0) / (SUMS - 1);
        K.ln('ha', 'marks', x0 - 8, y, x1 + 8, y, { stroke: C.ink, w: 1, op: bu });
        for (let i = 0; i < SUMS; i++) K.ln('ht' + i, 'marks', x0 + i * dx, y, x0 + i * dx, y + 5, { stroke: C.muted, w: 1, op: bu });
        K.tx('hl5', 'labels', x0, y + 24, String(P.sumMin), { size: 14, anchor: 'middle', fill: C.muted, op: bu, role: 'secondary' });
        K.tx('hl30', 'labels', x1, y + 24, String(P.sumMax), { size: 14, anchor: 'middle', fill: C.muted, op: bu, role: 'secondary' });
        const lu = sm(seg(t, KN.hookLineAt + 0.6, KN.hookLineAt + 1.6)) * hookOp;
        K.ln('hb', 'marks', x0, 372, x0 + (x1 - x0) * lu, 372, { stroke: C.muted, w: 2.5, op: bu, dash: '6 5' });
        K.tx('hbl', 'labels', x1 + 14, 377, 'ANYTHING CAN HAPPEN?', { size: 14, fill: C.muted, op: lu, role: 'secondary' });
      }
    }

    /* ── CASE + COUNT (12–66) · the 100,000 marks under the rig ───────────────────────────────────────── */
    const fade = 1 - sm(seg(t, KN.stackOut0, KN.stackOut1));
    if (t >= KN.rainT0 - 0.4 && fade > 0.01) {
      const k = GI.countAt(S.IP, N, t), front = GI.frontAt(S.IP, N, t);
      RIG.apply(p, S.cam, pose, S.rig); p.setCamera(S.cam); p.noLights();
      p.push(); p.noStroke(); p.fill(p.lerpColor(p.color(B.bg), p.color(B.panel), 0.9 * fade)); p.translate(0, 1.2, 0); p.box(S.floorW, 2, S.floorD); p.pop();
      if (k > 0) {
        const sh = S.st.sh, move = sm(seg(t, KN.sortT0, KN.sortT1));
        p.shader(sh);
        sh.setUniform('uData', S.st.fb); sh.setUniform('uTexW', GI.TEXW); sh.setUniform('uChunk', S.st.chunk); sh.setUniform('uStep', GI.STEP);
        sh.setUniform('uKc', k); sh.setUniform('uFront', front); sh.setUniform('uWin', Math.max(1, N * KN.rainWin)); sh.setUniform('uSize', KN.cube);
        sh.setUniform('uDrop', KN.rainDrop); sh.setUniform('uMove', move); sh.setUniform('uStag', KN.sortStagger); sh.setUniform('uLift', KN.sortLift);
        sh.setUniform('uTail', sm(seg(t, KN.tailLitAt, KN.tailLitAt + 0.8))); sh.setUniform('uFade', fade);
        sh.setUniform('uInk', S.rgb(B.ink)); sh.setUniform('uAcc', S.rgb(B.accent)); sh.setUniform('uHot', S.rgb(B.chalk)); sh.setUniform('uBg', S.rgb(B.bg));
        sh.setUniform('uMark', 1); sh.setUniform('uWeight', 0);
        sh.setUniform('uAmb', [KN.litAmb, KN.litAmb, KN.litAmb]); sh.setUniform('uKey', S.rgb(B.chalk).map((x) => x * KN.litKey));
        sh.setUniform('uRim', S.mixc(B.bg, B.accent2, 0.35)); sh.setUniform('uKeyDir', GI.norm([-0.45, 0.8, -0.4])); sh.setUniform('uRimDir', GI.norm([0.7, 0.3, 0.6]));
        p.noStroke();
        GI.drawMarks(p, S.st, { mark: 'box', drawOrder: 'arrival' }, k);
      }
      // reference lines in the world: a sixth of the rolls per bin (CASE), equal odds per sum (the belief)
      const GA = S.GA, GB = S.GB, c = KN.pitch;
      const l1 = win(t, KN.pinFirstAt, KN.pinFirstOut) * fade, l2 = win(t, KN.beliefAt, KN.beliefOut) * fade;
      if (l1 > 0.01) { const y = -(P.firstExpect / GA.L) * c, z = GA.fz * c / 2 + 3, col = p.color(B.muted); col.setAlpha(255 * l1);
        p.stroke(col); p.strokeWeight(1.6); p.line(GA.cx(0) - GA.w / 2 - 10, y, z, GA.cx(5) + GA.w / 2 + 10, y, z); }
      if (l2 > 0.01) { const y = -(P.beliefEach / GB.L) * c, z = GB.fz * c / 2 + 3, col = p.color(B.muted); col.setAlpha(255 * l2);
        p.stroke(col); p.strokeWeight(1.6); p.line(GB.cx(0) - GB.w / 2 - 10, y, z, GB.cx(SUMS - 1) + GB.w / 2 + 10, y, z); }
      p.noStroke(); p.setCamera(K.cam0);

      // readouts: the running count (counts in progress), then the count that lands at landAt
      const cop = sm(seg(t, KN.rainT0 - 0.2, KN.rainT0 + 0.3)) * (1 - sm(seg(t, 39.6, 40.2)));
      if (cop > 0.01) {
        const landed = t >= KN.landAt;
        K.tx('cnt', 'labels', 48, 112, landed ? fmt(N) + ' ROLLS' : fmt(k), { fam: 'disp', size: KN.countSize, op: cop, role: 'must-read' });
        K.tx('cnt2', 'labels', 50, 138, landed ? 'ONE MARK EACH · NOTHING SMOOTHED' : 'ROLLS THROWN · ONE MARK EACH', { size: KN.subSize, fill: C.muted, op: cop, ls: '0.08em', role: 'secondary' });
      }
      // the first-die bins: pips under each bin, the counted piles pinned
      const dop = win(t, KN.facesAt, KN.pinFirstOut) * fade;
      for (let f = 0; f < 6; f++) { const v = W2S(GA.cx(f), 0, GA.fz * c / 2 + 26); if (dop > 0.01 && v.on) die(K, 'bd' + f, v.x, v.y + 8, 22, f + 1, dop); }
      pins(K, t, 'pf', S.AN.bins, win(t, KN.pinFirstAt, KN.pinFirstOut) * fade, [capBand, [40, 80, 470, 150]]);
      if (l1 > 0.01) { const v = W2S(0, 0, GA.fz * c / 2 + 26);
        K.ln('fes', 'labels', 480 - 190, v.y + 44, 480 - 166, v.y + 44, { stroke: C.muted, w: 2, op: l1 });
        K.tx('fe', 'labels', 480 - 158, v.y + 49, 'THE LINE: A SIXTH OF ' + fmt(N) + ', ' + fmt(P.firstExpect), { size: KN.subSize, fill: C.muted, op: l1, role: 'secondary' }); }
      if (l2 > 0.01) { K.ln('bes', 'labels', 48, 107, 72, 107, { stroke: C.muted, w: 2, op: l2 });
        K.tx('be', 'labels', 80, 112, 'THE LINE: EQUAL ODDS, ' + fmt(P.beliefEach) + ' PER SUM', { size: KN.subSize, fill: C.muted, op: l2, role: 'secondary' }); }
      pins(K, t, 'pc', S.AN.cols, win(t, KN.pinColAt, KN.pinColOut) * fade, [capBand]);
      const tp = win(t, KN.pinTailAt, KN.pinTailOut) * fade;
      pins(K, t, 'pt', S.AN.tail, tp, [capBand]);
      if (tp > 0.01) { const v = W2S((GB.cx(21) + GB.cx(25)) / 2, 0, GB.fz * c / 2 + 30);
        if (v.on) K.tx('tg', 'labels', v.x, Math.min(v.y + 40, 430), 'SUMS ' + P.nSums + ' TO ' + P.sumMax + ' · FIVE THIN PILES', { size: KN.subSize, anchor: 'middle', fill: C.accent, op: tp, role: 'secondary' }); }
    }

    /* ── COUNT (66–108) · the sums as counted cells, the cut, the tail; the glass bell in the inset ─────── */
    if (t >= KN.stackOut1 - 0.05 && t < KN.volOut1 + 0.1) {
      const cnt = VOL.draw(p, t, S.VST, S.VP, S.TOK);
      p.setCamera(K.cam0);
      const vo = 1 - sm(seg(t, KN.volOut0, KN.volOut1));
      if (vo < 0.999) K.flat((q) => { const col = q.color(B.bg); col.setAlpha(255 * (1 - vo)); q.noStroke(); q.fill(col); q.rect(-2, -2, 964, 544); });
      const GB = S.GB, c = KN.pitch;
      // axis words on the floor (projected): 5 and 30 at the ends, the tail edge
      const ao = sm(seg(t, KN.volBuild0, KN.volBuild0 + 0.6)) * vo, zf = KN.volZ / 2 + 22;
      if (ao > 0.01) {
        const a5 = W2S(GB.cx(0), 0, zf), a30 = W2S(GB.cx(25), 0, zf);
        K.tx('va5', 'labels', a5.x, a5.y + 14, 'SUM ' + P.sumMin, { size: 14, anchor: 'middle', fill: C.muted, op: ao, role: 'secondary' });
        K.tx('va30', 'labels', a30.x, a30.y + 14, String(P.sumMax), { size: 14, anchor: 'middle', fill: C.muted, op: ao, role: 'secondary' });
        const zd = W2S(GB.cx(25) + GB.pitch, 0, 0);
        K.tx('vaz', 'labels', zd.x + 8, zd.y + 4, 'ROWS BY FIRST DIE', { size: 14, fill: C.muted, op: ao, role: 'secondary' });
      }
      // the cut counts as it travels; RIGHT of the cut lands on the tail count at volCutEnd
      const cutOp = sm(seg(t, KN.volCutIn - 0.3, KN.volCutIn + 0.2)) * vo;
      if (cutOp > 0.01) {
        let right = 0; for (let i = cnt.slice + 1; i < SUMS; i++) right += P['sim' + (i + 5)];
        const landed = t >= KN.volCutEnd, n = landed ? cnt.tailSamples : right;
        K.tx('vc', 'labels', 48, 120, fmt(n), { fam: 'disp', size: KN.countSize, fill: landed ? C.accent : C.ink, op: cutOp, role: 'must-read' });
        K.tx('vc2', 'labels', 50, 146, landed ? 'ROLLS ABOVE ' + TAILCUT + ' · OF ' + fmt(N) : 'ROLLS RIGHT OF THE CUT', { size: KN.subSize, fill: C.ink, op: cutOp, ls: '0.06em', role: 'secondary' });
        const cx5 = seg(t, KN.volCutIn, KN.volCutEnd), cs = KN.volCutTo * cx5 * cx5 * cx5 * (cx5 * (cx5 * 6 - 15) + 10);   // the module's quintic
        const ce = W2S(-S.VP.size[0] / 2 + cs * S.VP.size[0], -KN.volH * 1.04 - 6, -KN.volZ / 2);
        if (!landed && ce.on) K.tx('vcl', 'labels', ce.x + 6, ce.y - 6, 'THE CUT', { size: 14, fill: C.soft, op: cutOp, role: 'secondary' });
      }
      const ro = sm(seg(t, KN.ratioAt, KN.ratioAt + 0.5)) * vo;
      const rx = 48 + fmt(P.simTail).length * KN.countSize * K.ADV.disp + 20;
      if (ro > 0.01) K.tx('vr', 'labels', rx, 120, '= ' + P.tailPctSim.toFixed(1) + ' %', { fam: 'disp', size: 30, fill: C.accent, op: ro, role: 'must-read' });
      // the left column: the exact count of ways against the counted tail, then the agreement
      const eo = sm(seg(t, KN.expTailAt, KN.expTailAt + 0.5)) * vo, go = sm(seg(t, KN.agreeAt, KN.agreeAt + 0.5)) * vo;
      if (eo > 0.01) K.rc('vnp', 'marks', 40, 156, 430, go > 0.01 ? 116 : 46, { fill: C.paper, fo: 0.7, op: eo });
      if (eo > 0.01) {
        K.tx('ve1', 'labels', 50, 172, P.waysTail + ' OF ' + fmt(P.outcomes) + ' WAYS LAND ABOVE ' + TAILCUT, { size: KN.noteSize, fill: C.soft, op: eo, role: 'secondary' });
        K.tx('ve2', 'labels', 50, 194, 'EXPECTED ' + fmt(P.expTailRound) + ' · COUNTED ' + fmt(P.simTail), { size: KN.noteSize, fill: C.ink, op: eo, role: 'secondary' });
      }
      if (go > 0.01) {
        K.tx('vg1', 'labels', 50, 222, 'LARGEST GAP ' + P.maxGapPts.toFixed(2) + ' POINTS (SUM ' + P.maxGapSum + ')', { size: KN.noteSize, fill: C.ink, op: go, role: 'secondary' });
        K.tx('vg2', 'labels', 50, 244, 'MEAN ' + P.meanExact + ' · COUNTED ' + P.simMean.toFixed(2), { size: KN.noteSize, fill: C.ink, op: go, role: 'secondary' });
        K.tx('vg3', 'labels', 50, 266, 'SD ' + P.sdExact.toFixed(2) + ' · COUNTED ' + P.simSd.toFixed(2), { size: KN.noteSize, fill: C.ink, op: go, role: 'secondary' });
      }
      // the inset: equal odds, then the exact bell as glass, then the counted bars fill it
      const io = sm(seg(t, KN.insetAt, KN.insetAt + 0.6)) * vo;
      if (io > 0.01) {
        const x0 = KN.insetX, y0 = KN.insetY, w = KN.insetW, h = KN.insetH, gx = x0 + 16, gw = w - 32, bw = gw / SUMS, gb = y0 + h - 58, ph = gb - (y0 + 78);
        const top = P.sim18, Y = (v) => gb - ph * v / top;
        K.rc('ib', 'marks', x0, y0, w, h, { fill: C.panel, fo: 0.92, op: io });
        K.tx('ih', 'labels', x0 + 16, y0 + 26, 'THE ' + P.nSums + ' SUMS', { size: 14, fill: C.ink, ls: '0.1em', op: io, role: 'secondary' });
        K.ln('iax', 'marks', gx, gb, gx + gw, gb, { stroke: C.ink, w: 1.2, op: io });
        K.tx('ix5', 'labels', gx + bw / 2, gb + 40, String(P.sumMin), { size: 14, anchor: 'middle', fill: C.muted, op: io, role: 'secondary' });
        K.tx('ix30', 'labels', gx + gw - bw / 2, gb + 40, String(P.sumMax), { size: 14, anchor: 'middle', fill: C.muted, op: io, role: 'secondary' });
        // equal odds: a flat line at 3,846 and the 19,231 rolls it would put above 25
        const yb = Y(P.beliefEach), bo = io * (1 - 0.6 * sm(seg(t, KN.glassT0, KN.glassT1))), bw2 = io * (1 - sm(seg(t, KN.glassT0, KN.glassT0 + 0.8)));
        K.ln('ibl', 'marks', gx, yb, gx + gw, yb, { stroke: C.muted, w: 2, dash: '6 4', op: bo });
        K.rc('ibt', 'marks', gx + 21 * bw, yb, 5 * bw, gb - yb, { stroke: C.muted, w: 1.2, dash: '3 3', fill: C.muted, fo: 0.12, op: bo });
        K.tx('ibx1', 'labels', gx + gw, yb - 30, 'EQUAL ODDS: ' + fmt(P.beliefTail) + ' ABOVE ' + TAILCUT, { size: 14, anchor: 'end', fill: C.muted, op: bw2, role: 'secondary' });
        K.tx('ibx2', 'labels', gx + gw, yb - 12, 'ABOUT ' + P.beliefTimes + ' TIMES TOO MANY', { size: 14, anchor: 'end', fill: C.muted, op: bw2, role: 'secondary' });
        // the counted bars rise into the glass
        const fu = sm(seg(t, KN.fillT0, KN.fillT1));
        if (fu > 0) for (let i = 0; i < SUMS; i++) {
          const v = P['sim' + (i + 5)] * fu, y = Y(v), tail = i + 5 > TAILCUT;
          K.rc('ic' + i, 'marks', gx + i * bw + 1.5, y, bw - 3, gb - y, { fill: tail ? C.accent : C.ink, fo: 0.85, op: io });
        }
        // the exact bell: a step outline of 100,000 x ways / 7,776, drawn left to right, glass over the count
        const gu = seg(t, KN.glassT0, KN.glassT1), nb = gu * SUMS;
        if (gu > 0) {
          let d = 'M' + gx.toFixed(1) + ' ' + gb.toFixed(1);
          for (let i = 0; i < Math.ceil(nb); i++) { const e = P.rolls * P['ways' + (i + 5)] / P.outcomes, y = Y(e).toFixed(1), xa = gx + i * bw, xb = gx + Math.min(i + 1, nb) * bw;
            d += ' L' + xa.toFixed(1) + ' ' + y + ' L' + xb.toFixed(1) + ' ' + y; }
          const xe = gx + nb * bw; d += ' L' + xe.toFixed(1) + ' ' + gb.toFixed(1) + ' Z';
          K.E('ig', 'path', 'marks', { d, fill: C.soft, 'fill-opacity': 0.16, stroke: C.soft, 'stroke-width': 1.6, opacity: (io * 0.9).toFixed(3) });
          K.tx('igl', 'labels', x0 + 16, y0 + 46, 'GLASS: THE EXACT COUNT OF WAYS', { size: 14, fill: C.soft, op: io * sm(gu * 3), role: 'secondary' });
        }
        const wo = sm(seg(t, KN.waysAt, KN.waysAt + 0.5)) * io;
        if (wo > 0.01) {
          K.tx('iw1', 'labels', x0 + 16, y0 + 64, 'WAYS OF ' + fmt(P.outcomes) + ' OUTCOMES', { size: 14, fill: C.soft, op: wo, role: 'secondary' });
          K.tx('iw2', 'labels', gx + gw / 2, gb + 20, [P.ways5, P.ways6, P.ways7].join(' · ') + ' … ' + P.ways17 + ' · ' + P.ways18 + ' … ' + [P.ways28, P.ways29, P.ways30].join(' · '),
            { size: 14, anchor: 'middle', fill: C.soft, op: wo, role: 'secondary' });
        }
        // mean line and the one-sd band under the bars
        if (go > 0.01) {
          const xm = gx + (P.meanExact - 4.5) * bw, xl = gx + (P.meanExact - P.sdExact - 4.5) * bw, xr = gx + (P.meanExact + P.sdExact - 4.5) * bw;
          K.ln('imn', 'marks', xm, y0 + 74, xm, gb, { stroke: C.ink, w: 1.4, dash: '2 3', op: go });
          K.dim('isd', 'marks', xl, xr, gb + 4, null, go, { stroke: C.ink });
        }
      }
    }

    /* ── MONDAY (108–120) · the throw again, and the one picture to keep ───────────────────────────────── */
    const mo = sm(seg(t, KN.mondayAt, KN.mondayAt + 0.7));
    if (mo > 0.01) {
      const f0 = (F.checks && F.checks.first10 && F.checks.first10[0].faces) || [2, 3, 2, 5, 6];
      for (let j = 0; j < 5; j++) die(K, 'md' + j, 120 + j * 70, 200, 50, f0[j], mo);
      K.tx('mds', 'labels', 260, 270, 'ONE ROLL: ' + P.roll0Sum, { fam: 'disp', size: 30, anchor: 'middle', op: mo, role: 'must-read' });
      const x0 = 520, y1 = 330, bw = 14, ph = 170;
      for (let i = 0; i < SUMS; i++) {
        const sv = i + 5, band = sv >= P.midLo && sv <= P.midHi, hgt = ph * P['sim' + sv] / P.sim18;
        K.rc('mb' + i, 'marks', x0 + i * bw + 1, y1 - hgt, bw - 2, hgt, { fill: band ? C.ink : C.muted, fo: band ? 0.95 : 0.35, op: mo });
      }
      K.ln('mba', 'marks', x0, y1, x0 + SUMS * bw, y1, { stroke: C.ink, w: 1, op: mo });
      K.tx('mbt', 'labels', x0 + (P.midLo - 5) * bw, y1 + 22, 'SUMS ' + P.midLo + ' TO ' + P.midHi, { size: 14, fill: C.ink, op: mo, role: 'secondary' });
      K.tx('mbp', 'labels', x0 + (P.midLo - 5) * bw, y1 + 58, P.simMidPct.toFixed(1) + ' % OF ROLLS', { fam: 'disp', size: 30, op: mo, role: 'must-read' });
    }
  },
};
})();
