#!/usr/bin/env python3
"""lib/mkfilm.py (noether-applied draft A, "two planets") -> ../film.json. The knob table is the single source: every KN.name film.src.js reads must be in it
(checked here). Captions are the beat table's, re-worded where noted in NOTES.md; digits only from claims.json."""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
claims = json.load(open(os.path.join(HERE, "..", "claims.json")))
K = [  # name, default, lo, hi, step, what
 ("sP1", 118, 60, 180, 2, "world units per orbit unit: radius of the planets' ring (the position view)"),
 ("zDec", 32, 20, 40, 1, "world units per tenfold of steps: the height of the column (each decade of steps is one band)"),
 ("sT", 150, 60, 220, 5, "radius of the fully stretched energy drift (the sorted view of the two steppers)"),
 ("errFloor", -5, -7, -3, 0.25, "log10 of the smallest energy drift that shows: the stretch of the error, a look, never a number"),
 ("farSqueeze", 0.03, 0, 0.15, 0.01, "how far the thrown-out planets are drawn from the ring in the position view (log squeeze)"),
 ("sW", 58, 30, 90, 2, "world units per unit of the weight picture (the network, before its sort)"),
 ("sC", 140, 80, 200, 5, "world units per unit of the layer gap: the radius of the network's shells"),
 ("sQ", 140, 80, 200, 5, "world units per unit of the spring's position and momentum (the toy pair's ring)"),
 ("zStep2", 1.4, 0.8, 2.0, 0.1, "world units between two snapshots of the toy pair (the height of its column)"),
 ("driftGain", 3, 1, 6, 0.25, "how much the toy networks' energy drift is stretched for the eye (a look, said in words)"),
 ("sK", 125, 60, 140, 5, "world units per unit of the air: the size of the stirred loop"),
 ("hz", 42, 25, 60, 1, "world units of height per unit of simulated time: how tall the ribbons rise"),
 ("chainR", 130, 60, 160, 5, "radius of the stand-in chain (world units)"),
 ("arrowLen", 24, 6, 30, 1, "length of the longest answer arrow on the chain (world units)"),
 ("arrowEvery", 36, 8, 60, 1, "one answer arrow per this many residues"),
 ("turnAx", 0.35, -1, 1, 0.05, "tilt of the turning axis, x part (the chain turns about (x, 1, z))"),
 ("turnAz", 0.2, -1, 1, 0.05, "tilt of the turning axis, z part"),
 ("turns", 1, 0.5, 2, 0.5, "how many full turns the chain makes"),
 ("dotR1", 1.3, 0.8, 2.5, 0.05, "dot radius of the 2,000 planet snapshots (world units, before the depth cue)"),
 ("dotR2", 1.6, 0.8, 2.5, 0.05, "dot radius of the 10,000 network dots"),
 ("dotR3", 2.0, 0.8, 4, 0.1, "dot radius of the 400 toy-network dots"),
 ("dotR4", 1.4, 0.8, 3, 0.05, "dot radius of the stirred loop's parcels"),
 ("dotR5", 1.3, 0.8, 3, 0.05, "dot radius of the stand-in chain's residues"),
 ("dotRW", 2.2, 1, 4, 0.1, "dot radius in the wide frame (the four small clouds)"),
 ("planetR", 4.2, 2, 8, 0.2, "radius of the two planets drawn as single dots"),
 ("wireR", 1.1, 0.6, 2, 0.1, "radius of the faint orbit's dots"),
 ("followGrow", 1.2, 0, 3, 0.1, "how much bigger the two followed dots are drawn (0 = same size)"),
 ("followK", 870, 0, 999, 1, "which snapshot of the keeper is followed (0 = the first, 999 = the last)"),
 ("followRun", 37, 0, 99, 1, "which of the 100 training runs is followed (drawn brighter)"),
 ("runDim", 0.4, 0, 0.8, 0.05, "how far the other 99 runs sink once one run is followed (0 = not at all)"),
 ("sizeCue", 0.5, 0, 1, 0.05, "depth size cue: nearer dots drawn bigger (0 = none)"),
 ("fog", 0.25, 0, 0.6, 0.05, "fog toward the far side (0 = none)"),
 ("stag", 0.18, 0, 0.25, 0.01, "stagger of the re-plot: how much each dot's start is delayed (the same dots, never fewer)"),
 ("ghostDim", 0.45, 0, 0.8, 0.05, "how far the ghost clouds sink toward the ground (the wide frame, the first pose)"),
 ("bandA", 0.14, 0, 0.4, 0.02, "opacity of the ribbon bands"),
 ("strandA", 0.5, 0, 1, 0.05, "opacity of the 25 strands"),
 ("strandW", 1.2, 0.5, 3, 0.1, "line width of the strands"),
 ("perS", 5.0, 3, 10, 0.5, "seconds per lap of the two planets in the first 26 seconds"),
 ("fov", 30, 20, 50, 1, "camera field of view (degrees)"),
 ("lensX", 0.44, 0, 0.6, 0.02, "lens shift that keeps the cloud in the left two thirds (0 = centred)"),
 ("lensY", 0.03, -0.2, 0.2, 0.01, "lens shift, vertical"),
 ("lensXWide", 0, 0, 0.6, 0.02, "lens shift in the wide frame (the wide frame looks from behind, so left and right are mirrored: the clouds are placed to read planets, network, air, chain left to right)"),
 ("lensYWide", 0, -0.2, 0.2, 0.01, "lens shift in the wide frame, vertical"),
 ("camHookAz", 137.5, -360, 360, 0.5, "hook camera azimuth: the planets' ring (degrees)"),
 ("camHookEl", 58, 10, 85, 1, "hook camera elevation (degrees)"),
 ("camHookDist", 640, 300, 1400, 10, "hook camera distance"),
 ("camS1Az", 137.5, -360, 360, 0.5, "azimuth of the planet column before the re-plot (chosen so the thrown-out planets, which all leave in one direction, end on the right)"),
 ("camS1El", 50, 10, 85, 1, "elevation of the planet column before the re-plot: the belief, from above"),
 ("camS1Dist", 1150, 600, 2200, 10, "distance to the planet column"),
 ("camM1Az", 60, 0, 90, 1, "how far the camera orbits during the first re-plot (degrees)"),
 ("camM1Dist", 900, 500, 2000, 10, "distance the first re-plot lands on (the camera moves in a little)"),
 ("camM1El", 14, 2, 60, 1, "elevation the first re-plot lands on: from the side"),
 ("camS2Az", 20, -90, 90, 1, "azimuth of the network cloud"),
 ("camS2El", 24, 4, 80, 1, "elevation of the network cloud"),
 ("camS2Dist", 1050, 600, 2200, 10, "distance to the network cloud"),
 ("camM3Az", 60, 0, 90, 1, "how far the camera orbits during the network re-plot (degrees)"),
 ("camS2bAz", 20, -90, 90, 1, "azimuth of the two toy networks"),
 ("camS2bEl", 24, 4, 80, 1, "elevation of the two toy networks"),
 ("camS2bDist", 1150, 600, 2200, 10, "distance to the two toy networks"),
 ("camS3Az", 15, -90, 90, 1, "azimuth of the stirred loop"),
 ("camS3El0", 70, 10, 85, 1, "elevation over the flat ring at the start of the loop"),
 ("camS3Dist0", 760, 300, 1600, 10, "distance to the flat ring"),
 ("camS3El1", 26, 5, 80, 1, "elevation at the end of the crane over the loop"),
 ("camS3Dist1", 1100, 500, 2000, 10, "distance at the end of the crane"),
 ("camM4Az", 25, 0, 90, 1, "how far the camera swings during the crane (degrees)"),
 ("camS4Az", 30, -90, 90, 1, "azimuth of the chain"),
 ("camS4El", 22, 4, 80, 1, "elevation of the chain"),
 ("camS4Dist", 780, 300, 1600, 10, "distance to the chain"),
 ("camWideAz", 197.5, -360, 360, 0.5, "azimuth of the wide frame"),
 ("camWideEl", 12, 0, 60, 1, "elevation of the wide frame"),
 ("camWideDist", 1750, 900, 3000, 10, "distance of the wide frame"),
 ("camWideCY", 40, -200, 200, 5, "height the wide frame looks at"),
 ("wideOff", 340, 250, 450, 5, "spacing of the four small clouds in the wide frame"),
 ("pX", 652, 600, 720, 2, "left edge of the readout panel (sheet units)"),
 ("honestY", 392, 340, 410, 2, "top line of the honest line (sheet units)"),
 ("tQ", 6.0, 3, 10, 0.2, "when the question comes up (seconds)"),
 ("tTwo", 14.0, 10, 20, 0.5, "when the second planet appears (seconds)"),
 ("cin1T0", 14.0, 12, 20, 0.5, "the planets' snapshots start to arrive (seconds)"),
 ("cin1T1", 26.0, 22, 30, 0.5, "all 1,000 snapshots of each stepper are there (seconds)"),
 ("m1T0", 34.0, 30, 40, 0.5, "first re-plot starts: place -> what should stay (seconds)"),
 ("m1T1", 42.0, 38, 48, 0.5, "first re-plot ends (seconds)"),
 ("tS2a", 62.0, 58, 66, 0.5, "cut to the network (seconds)"),
 ("cin2T0", 64.0, 62, 70, 0.5, "the network's dots start to arrive (seconds)"),
 ("cin2T1", 72.0, 68, 76, 0.5, "all the network's dots are there (seconds)"),
 ("m3T0", 74.5, 72, 80, 0.5, "network re-plot starts (seconds)"),
 ("m3T1", 81.5, 78, 86, 0.5, "network re-plot ends (seconds)"),
 ("tS2b", 89.0, 86, 92, 0.5, "cut to the two toy networks (seconds)"),
 ("cin3T0", 91.0, 89, 94, 0.5, "the toy networks' dots start to arrive (seconds)"),
 ("cin3T1", 97.0, 94, 100, 0.5, "all 400 toy-network dots are there (seconds)"),
 ("tS3", 110.0, 107, 114, 0.5, "cut to the stirred loop (seconds)"),
 ("m4T0", 113.0, 111, 118, 0.5, "crane over the loop starts; the ribbons start to rise (seconds)"),
 ("m4T1", 121.0, 117, 122, 0.5, "crane ends: the loop at the end, the ribbons under it (seconds)"),
 ("tS4", 122.5, 120, 126, 0.5, "cut to the chain (seconds)"),
 ("cin4T0", 123.0, 122, 126, 0.25, "the chain's dots start to arrive (seconds)"),
 ("cin4T1", 124.5, 123, 127, 0.25, "all the chain's dots are there (seconds)"),
 ("m5T0", 127.5, 125, 131, 0.5, "the chain starts to turn (seconds)"),
 ("m5T1", 134.5, 131, 135, 0.5, "the chain has turned once (seconds)"),
 ("tWide", 135.0, 133, 138, 0.5, "cut to the wide frame (seconds)"),
 ("tHonest", 141.5, 138, 146, 0.5, "the honest line comes up (seconds)"),
 ("pinA0", 44.5, 42, 48, 0.5, "first pin (the keeper's dot) comes up (seconds)"),
 ("pinB0", 53.5, 50, 58, 0.5, "second pin (the plain planet's dot) replaces it (seconds)"),
 ("pinB1", 61.5, 58, 62, 0.5, "the pin goes (seconds)"),
 ("pinN0", 81.8, 80, 86, 0.2, "the network's shell pin comes up (seconds)"),
 ("pinN1", 89.0, 86, 89, 0.5, "the network's pin goes (seconds)"),
 ("pinR0", 100.0, 97, 104, 0.5, "the starting-ring pin comes up (seconds)"),
 ("pinR1", 110.0, 106, 110, 0.5, "the starting-ring pin goes (seconds)"),
 ("pinRAz", 20, -90, 90, 5, "where on the starting ring the pin points (degrees round the ring)"),
]
import sys
src = open(os.path.join(HERE, "film.src.js"), encoding="utf-8").read()
if "--regenerate" not in sys.argv:
    # tier 2 (2026-10-10): film.json is the SOURCE now (rounds 1-2 and the tier-2 revision edited it in place); this script only CHECKS it.
    # --regenerate rewrites film.json from the stale tables below and would undo those edits: never run it from build.sh.
    fj = json.load(open(os.path.join(HERE, "..", "film.json"), encoding="utf-8"))
    names = set(fj["knobs"]); doc = {d["name"] for d in fj["knobs_doc"]}
    used = set(re.findall(r"\bT\.(\w+)", src)) | set(re.findall(r"KN\.(\w+)", src)) | set(re.findall(r"\bK\.(\w+)", src[src.index("function shots"):src.index("function poseAt")]))
    assert names == doc, "film.json knobs vs knobs_doc differ: %s" % sorted(names ^ doc)
    miss = sorted(used - names); assert not miss, "knobs used but not in film.json: %s" % miss
    extra = sorted(names - used)
    if extra: print("knobs in film.json but unused:", extra)
    print("film.json checked (not written): %d knobs, %d captions" % (len(names), len(fj["captions"])))
    sys.exit(0)
names = {k[0] for k in K}
used = set(re.findall(r"\bT\.(\w+)", src)) | set(re.findall(r"KN\.(\w+)", src)) | set(re.findall(r"\bK\.(\w+)", src[src.index("function shots"):src.index("function poseAt")]))
miss = sorted(used - names)
extra = sorted(names - used)
assert not miss, "knobs used but undocumented: %s" % miss
if extra: print("knobs documented but unused:", extra)
caps = [
 [0.8, 5.8, "Last time: a number that never changes."],
 [6.2, 11.6, "Where is that used today, outside quantum physics?"],
 [12.4, 19.8, "First: a computer moves a planet in tiny steps."],
 [20.0, 25.8, "Each dot is a snapshot of that planet."],
 [26.0, 28.4, "1,000 snapshots from each of two ways of stepping."],
 [28.6, 31.0, "1,000,000,000 tiny steps each."],
 [31.4, 33.8, "From above: two rings round the sun."],
 [34.2, 41.8, "Now sort by the number that should stay."],
 [42.2, 44.3, "One stays on its shell. The other leaves."],
 [44.5, 46.8, "The energy-keeper never strays more than 0.007 %."],
 [47.0, 49.3, "The plain way: 1.9 % off after 10,000,000 steps."],
 [51.0, 53.3, "About 270 times more error."],
 [53.5, 55.8, "Then it is thrown out: by 65 million steps."],
 [56.0, 58.3, "The spin number stays right to 11 places."],
 [58.7, 61.8, "Astronomers run whole solar systems this way."],
 [62.4, 71.8, "Next: machines that learn. Each dot is one step."],
 [72.0, 74.4, "10,000 steps from 100 training runs."],
 [74.8, 81.2, "Sort by the gap between two layers."],
 [83.0, 85.4, "The weights travelled 0.24."],
 [86.0, 88.4, "The gap between layers moved 0.00095."],
 [89.4, 96.8, "Teach two networks a swinging spring."],
 [97.0, 99.4, "Same size: 200 units, 2,000 training steps."],
 [100.0, 102.3, "The plain network, energy error: 170."],
 [102.5, 104.8, "The energy-keeping network: 0.38."],
 [106.5, 108.9, "About 450 times lower."],
 [112.2, 116.2, "Weather: tag a loop of air and follow it."],
 [116.4, 119.2, "The loop stretches and folds."],
 [119.4, 122.4, "The swirl around it stays the same."],
 [124.5, 126.9, "One dot per residue: 2,180 in one chain."],
 [127.6, 131.2, "Turn the protein. The answer turns with it."],
 [131.6, 134.8, "What stays is its shape, not a saved number."],
 [135.3, 140.8, "Monday: what must never change in your system?"],
]
src_keys = {"S1": "NASA NSSDC Earth fact sheet: eccentricity 0.0167 (the shape of both steppers' orbit). https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html",
 "S2": "topic folder verlet_vs_rk4.c + data/trace.c + recompute.py (gcc, seed 20261010): velocity Verlet vs classical RK4, 100 steps per lap, 1,000,000,000 steps. Derived.",
 "S3": "Wisdom and Holman, Astron. J. 102, 1528 (1991); Hairer, Lubich, Wanner, Acta Numerica 2003; Laskar and Gastineau, Nature 459, 817 (2009).",
 "S4": "Large or variable steps break the symplectic guarantee: arXiv 2111.08835 (honest line).",
 "S5": "Greydanus, Dzamba, Yosinski, Hamiltonian Neural Networks, NeurIPS 2019, arXiv 1906.01563, Table 1: 170 vs 0.38 (units 1e-3).",
 "S6": "Du, Hu, Lee, Algorithmic regularization in learning deep homogeneous models, NeurIPS 2018, arXiv 1806.00900.",
 "S7": "Kunin et al., Neural mechanics, ICLR 2021, arXiv 2012.04728: finite learning rates break the conservation (honest line).",
 "S8": "Part 1 (noether-symmetry) recompute v2, seed 20261010: 100 runs x 100 steps, weights travel 0.2378, the sum 0.000952. MODEL.",
 "S9": "Kelvin 1869; Salmon, Annu. Rev. Fluid Mech. 20 (1988); the loop is our own point-vortex model (recompute.py C). MODEL.",
 "S10": "Jumper et al., Nature 596, 583 (2021), Fig. 1d: CASP14 target T1044, 2,180 residues. The chain drawn is a seeded stand-in, not the fold."}
params = dict(claims["params"]); params.update({"ecc": 0.0167, "kelvinT": 6.0, "steps": 1000000000})
film = {"id": "noether-applied", "title": "Noether applied",
 "eyebrow": "CETI · AI-STORIES · Noether applied · part 2",
 "lede": "Where is a number that never changes used today? The same move four times, sorted by what stays: two ways of stepping a planet for a billion steps, a network told about energy, a loop of stirred air, a protein chain that turns with its input. Part 2 of 3.",
 "format": "feature-long", "renderer": "webgl", "level": "manager", "dur": 153, "seed": 20261010,
 "look": {"brand": "ceti-coastal-dark", "chrome": "none", "material": "ink"}, "params": params, "commit": {"enabled": False}, "count": {"at": 26.0},
 "chapters": [
  {"id": "hook", "beat": "HOOK", "t0": 0, "t1": 12, "eyebrow": "NOETHER APPLIED · HOOK", "title": "Where is this used today?"},
  {"id": "case", "beat": "CASE", "t0": 12, "t1": 62, "eyebrow": "NOETHER APPLIED · CASE", "title": "Two planets, one billion steps"},
  {"id": "count", "beat": "COUNT", "t0": 62, "t1": 135, "eyebrow": "NOETHER APPLIED · COUNT", "title": "Networks, air and a chain, sorted by what stays"},
  {"id": "monday", "beat": "MONDAY", "t0": 135, "t1": 150, "eyebrow": "NOETHER APPLIED · MONDAY", "title": "What must never change in your system?"}],
 "captions": caps, "brand": {"takeaway": "Find what stays. Then build so it does."},
 "sources": [[k, v] for k, v in src_keys.items()],
 "honest": ["Pictures are simulated. Big steps break it. A turn saves no number."],
 "question": "Where is this used today, outside quantum physics?",
 "knobs": {k[0]: k[1] for k in K},
 "knobs_doc": [{"name": k[0], "range": [k[2], k[3]], "step": k[4], "what": k[5]} for k in K]}
json.dump(film, open(os.path.join(HERE, "..", "film.json"), "w"), ensure_ascii=False, separators=(",", ":"))
print("film.json %d bytes, %d knobs" % (os.path.getsize(os.path.join(HERE, "..", "film.json")), len(K)))
