#!/usr/bin/env python3
"""lib/assemble.py (pass-every-time draft A, "the test floor") · writes ../film.js = lib/gl-camera-rig.js + lib/gl-labels.js
(verbatim copies of arsenal/patterns/<id>/pattern.js; the demo scene of each is cut IN THE ASSEMBLED COPY ONLY, see CUTS; their
sha256 is printed in film.js) + lib/film.src.js (the film). Deterministic: run twice, diff. Comments and indentation are stripped."""
import os, re, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
MODS = ["gl-camera-rig.js", "gl-labels.js"]

def strip(src):
    out, i, n = [], 0, len(src)
    prev = ""                          # last significant char, to tell a regex literal from a division
    while i < n:
        c = src[i]; d = src[i + 1] if i + 1 < n else ""
        if c in "'\"`":
            j = i + 1
            while j < n and src[j] != c:
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1]); prev = c; i = j + 1; continue
        if c == "/" and d == "*":
            j = src.find("*/", i + 2); i = n if j < 0 else j + 2; out.append(" "); continue
        if c == "/" and d == "/":
            j = src.find("\n", i); i = n if j < 0 else j; continue
        if c == "/" and (prev == "" or prev in "(,=:[!&|?{};+-*%<>~^" or re.search(r"\breturn\s*$", "".join(out[-3:]))):
            j, cls = i + 1, False
            while j < n:
                if src[j] == "\\": j += 2; continue
                if src[j] == "[": cls = True
                elif src[j] == "]": cls = False
                elif src[j] == "/" and not cls: break
                j += 1
            j += 1
            while j < n and src[j].isalpha(): j += 1
            out.append(src[i:j]); prev = "/"; i = j; continue
        if c in " \t":
            nxt = src[i + 1] if i + 1 < n else ""
            if (out and out[-1] in (" ", "\t", "\n")) or (out and out[-1] in "{}();,=:?[]<>!&|*%") or nxt in "{}();,=:?[]<>!&|*%":
                i += 1; continue
        out.append(c)
        if not c.isspace(): prev = c
        i += 1
    lines = [l.strip() for l in "".join(out).split("\n")]
    return "\n".join(l for l in lines if l)

CUTS = {
    "gl-camera-rig.js": [   # the demo scene (300 baked boxes, shaders, overlay) and its registration; the rig stays
        (r"^  /\* ═════════════ the demo scene", r"^\}\)\(\);",
         "  A.patterns['gl-camera-rig'] = { id: 'gl-camera-rig', renderer: 'webgl', rig };"),
    ],
    "gl-labels.js": [       # demo scene, field, cameras and the demo registration; the solver, drawGL, kit and project stay
        (r"^  /\* ---------- the demo scene", r"^\}\)\(\);",
         "  A.patterns['gl-labels'] = { id: 'gl-labels', renderer: 'webgl', ROLES, solve, drawGL, kit, project: (cam, W, H) => projector(cam, W, H) };"),
    ],
}

def cut(src, rules):
    lines = src.split("\n")
    for rule in rules:
        start, end, rep = (rule + (None,))[:3]
        i = next(k for k, l in enumerate(lines) if re.match(start, l))
        j = i + 1 if end is None else next(k for k, l in enumerate(lines) if k > i and re.match(end, l))
        lines[i:j] = ["/* [cut by lib/assemble.py: %d lines the film never calls] */" % (j - i)] + ([rep] if rep else [])
    return "\n".join(lines)

def main():
    parts = ["/* pass-every-time draft A, the test floor · film.js is GENERATED by lib/assemble.py; edit lib/film.src.js.\n"
             "   Arsenal modules inlined (comment-stripped, demo scenes cut): lib/gl-camera-rig.js, lib/gl-labels.js. */",
             "window.ARSENAL = window.ARSENAL || {}; ['patterns','structures','materials','brands','core','post'].forEach(function (k) { window.ARSENAL[k] = window.ARSENAL[k] || {}; });"]
    for m in MODS:
        src = open(os.path.join(HERE, m), encoding="utf-8").read()
        parts.append("/* ── lib/%s sha256 %s (cut) ── */\n" % (m, hashlib.sha256(src.encode()).hexdigest()[:16]) + strip(cut(src, CUTS[m])))
    parts.append(open(os.path.join(HERE, "film.src.js"), encoding="utf-8").read())
    out = "\n".join(parts) + "\n"
    with open(os.path.join(HERE, "..", "film.js"), "w", encoding="utf-8") as f:
        f.write(out)
    print("film.js %d bytes" % len(out.encode()))

if __name__ == "__main__":
    main()
