/* pass-every-time · draft A "the test floor" · lib/film.src.js (the film; ../film.js is GENERATED by lib/assemble.py)
   115 tasks x 4 tries as a flat field of cubes seen from above, lit 60 % (CASE). One clock: render(t) draws frame t from t alone.
   The camera lowers to the side and the SAME 460 cubes re-stack into one column per task (M1, plan to side); the columns re-sort
   by passes (M2); a cut plane rises to the all-four bar and only the 44 fully lit columns stay bright (M3); then 296 PRs
   re-partition into merged / not merged (M4) and the horizon is two columns of minutes (27 and 289). No simulated eight-try
   readout is drawn (brief, director's choices): the paper's own eight-try sentence is a caption and one attributed plate.
   Brand: midnight-ink via the film-local copy <draft>/brand.midnight-ink.json (Newsreader 600 display, DM Mono numbers).
   Chain (narrowed, see NOTES.md): gl-camera-rig (every camera key, a script compiled from knobs) + gl-labels (every pin and the
   hard-cut callout, solved in screen space). The cubes are this film's own baked geometry with TWO-THREE homes per cube (as
   gl-stack-city does: the module gl-instances has no second layout, and 1,187 marks need no instancing); the cut plane follows
   gl-volume's rule (it dims, never removes; the count snaps to a column edge) but is drawn here.
   Every tunable is a knob (film.json knobs_doc). Every digit is a film.json param that is a claim value. */
(function () {
'use strict';
const F = window.FILM, P = F.params, A = window.ARSENAL;
const RIG = A.patterns['gl-camera-rig'].rig, GLL = A.patterns['gl-labels'];
const KN = {};
(F.knobs_doc || []).forEach((d) => { KN[d.name] = window.KIT.knob(d.name, undefined); });

const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
const seg = (t, a, b) => clamp((t - a) / Math.max(1e-6, b - a));
const sm = (x) => { x = clamp(x); return x * x * x * (x * (x * 6 - 15) + 10); };
const lerp = (a, b, u) => a + (b - a) * u;
const win = (t, a0, a1, b0, b1) => sm(seg(t, a0, a1)) * (1 - sm(seg(t, b0, b1)));   // in a0..a1, out b0..b1
const D2R = Math.PI / 180;
const pc1 = (v) => v.toFixed(1) + ' %';

/* ── world (y is down in p5: a cube stands at negative y). One cube edge E, pitch PC, a task tile 2 x 2 cubes ── */
const E = KN.cubeEdge, PC = E * (1 + KN.cubeGap), TH = 0.14 * E, TW = 2 * PC + 0.12 * E, TP = 2 * PC + KN.tileGap * E;
const NT = P.tasks, COLS = KN.gridCols, ROWS = Math.ceil(NT / COLS), HW = COLS * TP / 2, HD = ROWS * TP / 2;
const PRC = KN.prCols, PRR = Math.ceil(P.prs / PRC), BW = KN.barCols, ZP = KN.prZ, XM = KN.minX;
const CTAU = [0, -5, KN.camLookZ], CSIDE = [0, -5, KN.camSideLookZ];
const CPR = [0, -2, ZP + KN.camPrLookZ];
const CMIN = [XM, -KN.camMinLookY, 0];
const sph = (c, az, el, r) => [c[0] + r * Math.cos(el * D2R) * Math.sin(az * D2R), c[1] - r * Math.sin(el * D2R), c[2] + r * Math.cos(el * D2R) * Math.cos(az * D2R)];

/* ── data: per-task outcomes of the four published trials (bit s = try s passed); counts are asserted against the claims ── */
const TR = P.trial, bits = (m) => [m & 1, (m >> 1) & 1, (m >> 2) & 1, (m >> 3) & 1];
const QS = TR.map((m) => bits(m).reduce((a, b) => a + b, 0));
{
  const hist = [0, 0, 0, 0, 0]; QS.forEach((q) => hist[q]++);
  if (TR.length !== NT || hist.join() !== [P.n0, P.n1, P.n2, P.n3, P.n4].join() || QS.reduce((a, b) => a + b, 0) !== P.passed || NT * P.triesPer !== P.tries)
    throw new Error('pass-every-time: trial table disagrees with the claims ' + hist.join('/'));
}
const ORDER = TR.map((_, i) => i).sort((a, b) => QS[b] - QS[a] || a - b);   // M2: passes 4,3,2,1,0, stable by task id
const SRANK = []; ORDER.forEach((id, j) => { SRANK[id] = j; });
const posId = (i) => [(i % COLS - (COLS - 1) / 2) * TP, (Math.floor(i / COLS) - (ROWS - 1) / 2) * TP];
/* M2 layout (tier-2 revision): one band per number of tries passed (4, 3, 2, 1, 0) left to right, each band SR columns deep and
   filled front to back, an aisle between bands; with SR = 11 the 44 full columns are one 4 x 11 block of their own */
const SR = KN.sortRows, AIS = KN.sortAisle * TP, SD = SR * TP / 2, SLOT = [];
let SW = 0;
{
  const live = [4, 3, 2, 1, 0].map((q) => QS.filter((x) => x === q).length).filter((n) => n > 0);
  const NS = live.reduce((a, n) => a + Math.ceil(n / SR), 0), WT = NS * TP + (live.length - 1) * AIS;
  let j = 0, s0 = 0, bi = 0;
  for (const n of live) { for (let k = 0; k < n; k++) SLOT[j++] = [-WT / 2 + TP / 2 + (s0 + Math.floor(k / SR)) * TP + bi * AIS, ((SR - 1) / 2 - (k % SR)) * TP]; s0 += Math.ceil(n / SR); bi++; }
  SW = WT / 2;
}
const posSorted = (j) => SLOT[j];
const topY = -(TH + 3 * PC + E);                                              // top face of a four-cube column
const colTop = (id, sorted) => { const q = sorted ? posSorted(SRANK[id]) : posId(id); return [q[0], topY, q[1] + 0.0]; };

/* ── the baked geometry: kind 0 tile · 1 tau cube · 2 PR cube · 3 minute (27) · 4 minute (289) ── */
let GEO = null, SH = null, CAM = null, RIGC = null, CAMFN = null, NCUBE = 0;
const KINDN = [0, 0, 0, 0, 0];
function bake(p, K) {
  const R = [], rn = K.mulberry32(KN.seedLit), rk = K.mulberry32(KN.seedLit + 11), rs = K.mulberry32(KN.seedMerge);
  const litRank = K.shuffle(Array.from({ length: P.passed }, (_, i) => i), KN.seedLit);    // seeded order the passes light in
  let li = 0;
  const col = TR.map(() => rk());
  for (let i = 0; i < NT; i++) {
    const a = posId(i), c = posSorted(SRANK[i]);
    R.push({ kind: 0, cls: 3, ar: i / NT, lr: -1, A: [a[0], -TH / 2, a[1]], B: [a[0], -TH / 2, a[1]], C: [c[0], -TH / 2, c[1]], q: QS[i], st: 0, side: 0, rn: col[i] });
  }
  for (let i = 0; i < NT; i++) {
    const b = bits(TR[i]), a = posId(i), c = posSorted(SRANK[i]); let nl = 0, nu = 0;
    for (let s = 0; s < 4; s++) {
      const slot = b[s] ? nl++ : QS[i] + nu++;
      const y = -(TH + slot * PC + E / 2);
      R.push({ kind: 1, cls: b[s] ? 1 : 0, ar: (i + s / 4) / NT, lr: b[s] ? (litRank[li++] + 0.5) / P.passed : 2,
        A: [a[0] + (s % 2 - 0.5) * PC, -(TH + E / 2), a[1] + (Math.floor(s / 2) - 0.5) * PC], B: [a[0], y, a[1]], C: [c[0], y, c[1]], q: QS[i], st: slot / 3, side: 0, rn: col[i] });
    }
  }
  const side = K.shuffle(Array.from({ length: P.prs }, (_, i) => (i < P.prs / 2 ? 0 : 1)), KN.seedMerge), cnt = [0, 0], hg = KN.prGap * PC / 2;
  for (let i = 0; i < P.prs; i++) {
    const c = i % PRC, r = Math.floor(i / PRC), s = side[i], k = cnt[s]++, c2 = k % PRC, r2 = Math.floor(k / PRC), half = PRR / 2;
    const z2 = s === 0 ? -(hg + PC / 2 + (half - 1 - r2) * PC) : (hg + PC / 2 + r2 * PC);
    R.push({ kind: 2, cls: 1, ar: i / P.prs, lr: -1, A: [(c - (PRC - 1) / 2) * PC, -E / 2, ZP + (r - (PRR - 1) / 2) * PC],
      B: [(c2 - (PRC - 1) / 2) * PC, -E / 2, ZP + z2], C: [0, 0, 0], q: 9, st: rs() * 0 + (c + r) / (PRC + PRR), side: s, rn: rn() });
  }
  const bar = (n, k, cx, cls) => { for (let i = 0; i < n; i++) { const a = [cx + (i % BW - (BW - 1) / 2) * PC, -(E / 2 + Math.floor(i / BW) * PC), 0];
    R.push({ kind: k, cls, ar: i / n, lr: -1, A: a, B: a, C: a, q: 9, st: 0, side: 0, rn: 0 }); } };
  const bx = (BW * PC + KN.barGap * PC) / 2;
  bar(P.h80, 3, XM - bx, 1); bar(P.h50, 4, XM + bx, 2);
  NCUBE = R.length; R.forEach((r) => { KINDN[r.kind]++; });
  // five faces per cube (the bottom is never seen), homes and data as per-vertex properties (the technique of gl-stack-city)
  const FACES = [[[0, -1, 0], [[-1, -1, -1], [1, -1, -1], [1, -1, 1], [-1, -1, 1]]], [[0, 0, 1], [[-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1]]],
    [[0, 0, -1], [[1, -1, -1], [-1, -1, -1], [-1, 1, -1], [1, 1, -1]]], [[1, 0, 0], [[1, -1, 1], [1, -1, -1], [1, 1, -1], [1, 1, 1]]], [[-1, 0, 0], [[-1, -1, -1], [-1, -1, 1], [-1, 1, 1], [-1, 1, -1]]]];
  const N = R.length, V = N * 20, vs = new Array(V), ns = new Array(V), faces = new Array(N * 10);
  const aA = new Float32Array(V * 3), aB = new Float32Array(V * 3), aC = new Float32Array(V * 3), aI = new Float32Array(V * 4), aJ = new Float32Array(V * 4);
  const nv = FACES.map((f) => new p5.Vector(...f[0]));
  let v = 0, f = 0;
  for (let i = 0; i < N; i++) {
    const b = R[i];
    for (let q = 0; q < 5; q++) {
      const base = v;
      for (const cr of FACES[q][1]) {
        vs[v] = new p5.Vector(cr[0] * 0.5, cr[1] * 0.5, cr[2] * 0.5); ns[v] = nv[q];
        aA.set(b.A, v * 3); aB.set(b.B, v * 3); aC.set(b.C, v * 3);
        aI[v * 4] = b.kind; aI[v * 4 + 1] = b.cls; aI[v * 4 + 2] = b.ar; aI[v * 4 + 3] = b.lr;
        aJ[v * 4] = b.q; aJ[v * 4 + 1] = b.st; aJ[v * 4 + 2] = b.side; aJ[v * 4 + 3] = b.rn;
        v++;
      }
      faces[f++] = [base, base + 1, base + 2]; faces[f++] = [base, base + 2, base + 3];
    }
  }
  const geo = new p5.Geometry(1, 1);
  geo.vertices = vs; geo.vertexNormals = ns; geo.faces = faces;
  const prop = (name, arr, size) => { geo._userVertexPropertyHelper(name, [], size); geo[name + 'Src'] = Array.from(arr); };
  prop('aA', aA, 3); prop('aB', aB, 3); prop('aC', aC, 3); prop('aInfo', aI, 4); prop('aInfo2', aJ, 4);
  geo.gid = 'pass-every-time-cubes';
  return geo;
}

const VERT = `precision highp float;
attribute vec3 aPosition; attribute vec3 aNormal; attribute vec3 aA; attribute vec3 aB; attribute vec3 aC; attribute vec4 aInfo; attribute vec4 aInfo2;
uniform mat4 uModelViewMatrix; uniform mat4 uProjectionMatrix;
uniform float uArr[5]; uniform float uMa[5]; uniform float uMb[5]; uniform float uBk[5]; uniform vec3 uSz[5]; uniform vec3 uCol[20]; uniform vec3 uBg;
uniform float uArrW, uDrop, uLift, uLift2, uStag, uLitP, uCut, uCutDim, uGhost, uGlobal;
varying vec3 vCol;
float ez(float u){ return u * u * u * (u * (u * 6.0 - 15.0) + 10.0); }
void main(){
  int kind = int(aInfo.x + 0.5);
  float a = clamp((uArr[kind] - aInfo.z) / uArrW, 0.0, 1.0);
  float u1 = clamp(uMa[kind] * (1.0 + uStag) - aInfo2.y * uStag, 0.0, 1.0);
  float u2 = clamp(uMb[kind] * (1.0 + uStag) - aInfo2.w * uStag, 0.0, 1.0);
  float u3 = clamp(uBk[kind] * (1.0 + uStag) - aInfo2.w * uStag, 0.0, 1.0);
  vec3 c = mix(mix(mix(aA, aB, ez(u1)), aC, ez(u2)), aA, ez(u3));
  c.y -= sin(3.14159265 * u1) * uLift + (sin(3.14159265 * u2) + sin(3.14159265 * u3)) * uLift2 * (0.4 + 0.6 * aInfo2.w) + (1.0 - a) * (1.0 - a) * uDrop;
  vec3 pos = c + aPosition * uSz[kind] * (0.35 + 0.65 * a);
  int fi = aNormal.y < -0.5 ? 0 : (aNormal.z > 0.5 ? 1 : (aNormal.z < -0.5 ? 2 : (aNormal.x > 0.5 ? 3 : 4)));
  float cls = aInfo.y;
  if (kind == 1 && cls > 0.5) cls = step(aInfo.w, uLitP);
  vec3 col = uCol[int(cls + 0.5) * 5 + fi];
  if (kind == 2) col = mix(col, uCol[fi], uGhost * aInfo2.z);
  if (kind < 2) col = mix(col, uBg, uCutDim * ez(clamp((uCut - aInfo2.x - 0.15) / 0.6, 0.0, 1.0)));
  vCol = mix(col, uBg, uGlobal);
  gl_Position = (a <= 0.0) ? vec4(3.0, 3.0, 3.0, 1.0) : uProjectionMatrix * uModelViewMatrix * vec4(pos, 1.0);
}`;
const FRAG = 'precision highp float; varying vec3 vCol; void main(){ gl_FragColor = vec4(vCol, 1.0); }';

/* ── palette (sRGB, from the brand roles only) ── */
let PAL = null, FLOORC = null, GRIDC = null, PLANEC = null, BGC = null, KH = null;
function palette(K) {
  const C = K.C, rgb = (h) => K.hexRgb(h).map((x) => x / 255), mixc = (a, b, u) => a.map((x, i) => x + (b[i] - x) * u);
  const bg = rgb(C.paper), ink = rgb(C.ink), gold = rgb(C.accent), blue = rgb(C.soft), muted = rgb(C.muted), panel = rgb(C.panel);
  const sh = [1.0, KN.shadeFront, KN.shadeBack, KN.shadeRight, KN.shadeLeft];
  const ghost = mixc(bg, muted, KN.ghostMix), plate = mixc(bg, muted, KN.plateMix);
  PAL = []; [ghost, gold, blue, plate].forEach((c) => sh.forEach((f) => PAL.push(...c.map((x) => Math.min(1, x * f)))));
  BGC = bg; FLOORC = mixc(bg, panel, KN.floorMix).map((x) => x * 255); GRIDC = ink.map((x) => x * 255); PLANEC = gold.map((x) => x * 255);
}

/* ── camera: rig script from knobs; ambient yaw drift about the aim point; labels read the same function ── */
function rigScript() {
  const el = KN.camPlanEl, d0 = KN.camPlanDist, side = [KN.camSideAz, KN.camSideEl, d0 * KN.camSideR];
  return { proj: 'persp', dur: 153, near: 10, far: 9000, start: { eye: sph(CTAU, 0, el, d0), center: CTAU, fov: KN.camFov },
    moves: [
      { id: 'm1', move: 'orbit', t0: KN.m1T0, t1: KN.m1T1, az: KN.camSideAz, el: KN.camSideEl, r: KN.camSideR, ease: 'inout', around: CSIDE },
      { id: 'toPR', move: 'cut', t0: KN.prCut, eye: sph(CPR, 0, el, KN.camPrDist), center: CPR },
      { id: 'toMin', move: 'cut', t0: KN.minCut, eye: sph(CMIN, KN.camMinAz, KN.camMinEl, KN.camMinDist), center: CMIN },
      { id: 'toTau', move: 'cut', t0: KN.tauCut, eye: sph(CSIDE, side[0], side[1], side[2]), center: CSIDE },
      { id: 'book', move: 'orbit', t0: KN.bookT0, t1: KN.bookT1, az: -KN.camSideAz, el: KN.camPlanEl, r: 1 / KN.camSideR, ease: 'inout', around: CTAU },
    ] };
}
function poseAt(t) { return RIG.at(RIGC, t); }
function camAt(t, still) {
  const q = poseAt(t), d = still ? 0 : KN.driftDeg * D2R * Math.sin(2 * Math.PI * t / KN.driftPeriod), c = q.center;
  const dx = q.eye[0] - c[0], dz = q.eye[2] - c[2], cs = Math.cos(d), sn = Math.sin(d);
  return { eye: [c[0] + dx * cs + dz * sn, q.eye[1], c[2] - dx * sn + dz * cs], look: c, up: q.up, fov: q.fov };
}

/* the screen rectangle of a world box under the pose at tRest (no drift): labels keep out of the marks they name */
function rectOf(tRest, x0, x1, y0, y1, z0, z1, pad) {
  const pose = poseAt(tRest); let a = 1e9, b = 1e9, c = -1e9, d = -1e9;
  for (const x of [x0, x1]) for (const y of [y0, y1]) for (const z of [z0, z1]) { const s = RIG.worldToScreen(pose, [x, y, z], 960, 540); a = Math.min(a, s.x); b = Math.min(b, s.y); c = Math.max(c, s.x); d = Math.max(d, s.y); }
  return [Math.round(a - pad), Math.round(b - pad), Math.round(c + pad), Math.round(d + pad)];
}

/* ── scenes: tau [0, prCut) and [tauCut, end) · pr · min ── */
const sceneAt = (t) => (t >= KN.minCut && t < KN.tauCut ? 'min' : t >= KN.prCut && t < KN.minCut ? 'pr' : 'tau');
const ORIGIN = { tau: [0, 0], pr: [0, ZP], min: [XM, 0] };

function floorDraw(p, sc) {
  const o = ORIGIN[sc], step = KN.gridStep * TP, n = Math.ceil(KN.floorSize / 2 / step);
  p.resetShader(); p.noStroke(); p.fill(FLOORC[0], FLOORC[1], FLOORC[2]);
  p.push(); p.translate(o[0], 0.5, o[1]); p.rotateX(Math.PI / 2); p.plane(KN.floorSize, KN.floorSize); p.pop();
  p.stroke(GRIDC[0], GRIDC[1], GRIDC[2], KN.gridAlpha * 255); p.strokeWeight(1);
  const h = KN.floorSize / 2;
  for (let i = -n; i <= n; i++) { p.line(o[0] + i * step, 0.2, o[1] - h, o[0] + i * step, 0.2, o[1] + h); p.line(o[0] - h, 0.2, o[1] + i * step, o[0] + h, 0.2, o[1] + i * step); }
  p.noStroke();
}
const cutLevel = (t) => P.triesPer * sm(seg(t, KN.m3T0, KN.m3T1));
function planeDraw(p, t) {
  const op = win(t, KN.m3T0 - 0.3, KN.m3T0 + 0.4, KN.planeOut, KN.planeOut + 0.8); if (op <= 0.01) return;
  const y = -(TH + cutLevel(t) * PC - 0.6), w = SW + KN.planeMargin, d = SD + KN.planeMargin;
  p.resetShader(); p.noStroke(); p.fill(PLANEC[0], PLANEC[1], PLANEC[2], 255 * KN.planeAlpha * op);
  p.push(); p.translate(0, y, 0); p.rotateX(Math.PI / 2); p.plane(2 * w, 2 * d); p.pop();
  p.stroke(PLANEC[0], PLANEC[1], PLANEC[2], 255 * op); p.strokeWeight(1.6);
  p.line(-w, y, -d, w, y, -d); p.line(w, y, -d, w, y, d); p.line(w, y, d, -w, y, d); p.line(-w, y, d, -w, y, -d); p.noStroke();
}
function cubesDraw(p, t) {
  const U = (n, v) => SH.setUniform(n, v), W = KN.arrW, ap = (a, b) => seg(t, a, b) * (1 + W);
  p.shader(SH); p.noStroke(); p.fill(255);
  const m1 = seg(t, KN.m1T0, KN.m1T1), m2 = seg(t, KN.m2T0, KN.m2T1), m4 = seg(t, KN.m4T0, KN.m4T1);
  U('uArr', [ap(KN.tileT0, KN.tileT1), ap(KN.cubeT0, KN.cubeT1), ap(KN.prT0, KN.prT1), ap(KN.min27T0, KN.min27T1), ap(KN.min289T0, KN.min289T1)]);
  const bk = seg(t, KN.bookT0, KN.bookT1);
  U('uMa', [0, m1, m4, 0, 0]); U('uMb', [m2, m2, 0, 0, 0]); U('uBk', [bk, bk, 0, 0, 0]);
  U('uSz', [TW, TH, TW, E, E, E, E, E, E, E, E, E, E, E, E]);
  U('uCol', PAL); U('uBg', BGC); U('uArrW', W); U('uDrop', KN.drop); U('uLift', KN.lift1); U('uLift2', KN.lift2); U('uStag', KN.stagger);
  U('uLitP', seg(t, KN.litT0, KN.litT1)); U('uCut', cutLevel(t)); U('uCutDim', KN.cutDim);
  U('uGhost', sm(seg(t, KN.ghost0, KN.ghost1))); U('uGlobal', KN.mondayDim * sm(seg(t, KN.dimT0, KN.dimT0 + 1.0)));
  p.model(GEO); p.resetShader();
}

/* ── labels: gl-labels placements -> kit2 SVG (roles carried) ── */
function drawPl(K, key, sol, op, keep) {
  const C = K.ROLES;
  for (const q of sol.placements) {
    if (keep && !keep(q)) continue;
    const o = op; if (o <= 0.01) continue;
    const kk = key + q.id + (q.callout ? '.co' : ''), col = C[q.color] || C.ink, b = q.box;
    K.rc(kk + '.p', 'labels', b[0], b[1], b[2] - b[0], b[3] - b[1] + (q.sub ? KN.subGap : 0), { fill: C.paper, fo: KN.plate, op: o });
    K.ln(kk + '.l', 'labels', q.lead[0], q.lead[1], q.lead[2], q.lead[3], { stroke: q.callout ? col : C.muted, w: q.callout ? 1.6 : 1, op: o });
    K.rc(kk + '.d', 'labels', q.ax - 2.5, q.ay - 2.5, 5, 5, { fill: col, op: o });
    const an = q.align === 'right' ? 'end' : q.align === 'center' ? 'middle' : 'start';
    K.tx(kk + '.t', 'labels', q.tx, q.ty, q.text, { fam: q.fam, size: q.size, fill: col, role: q.dataRole, anchor: an, op: o });
    if (q.sub) K.tx(kk + '.s', 'labels', q.tx, q.sy + KN.subGap, q.sub, { fam: q.subFam, size: q.subSize, fill: C.muted, role: q.subDataRole, anchor: an, op: o });
  }
}
let MEAS = null, AN = null, OPT = null, RECT = null;
const topOfBar = (cx, n) => [cx, -(Math.ceil(n / BW) * PC + 9), 0];

function setupLabels() {
  MEAS = (s, size, fam) => String(s).length * size * (fam === 'disp' ? KN.dispAdv : 0.6);
  const tPlan = (KN.cTasks + KN.cPctEnd) / 2, tSide = (KN.cAll + KN.cNone) / 2, tPr = KN.cPrs + 1, tMin = KN.cMin27 + 1;
  const ym = -(TH + 4 * PC), hgp = KN.prGap * PC / 2;
  RECT = {
    plan: rectOf(tPlan, -HW, HW, -(TH + E), 0, -HD, HD, 6),
    side: rectOf(tSide, -HW, HW, ym, 0, -HD, HD, 6),
    sorted: rectOf(KN.c44, -SW, SW, ym, 0, -SD, SD, 6),
    pr: rectOf(tPr, -(PRC * PC) / 2, (PRC * PC) / 2, -E, 0, ZP - (PRR * PC) / 2, ZP + (PRR * PC) / 2, 8),
    prA: rectOf(tPr, -(PRC * PC) / 2, (PRC * PC) / 2, -E, 0, ZP - hgp - PRR * PC / 2, ZP - hgp, 6),
    prB: rectOf(tPr, -(PRC * PC) / 2, (PRC * PC) / 2, -E, 0, ZP + hgp, ZP + hgp + PRR * PC / 2, 6),
    minA: rectOf(tMin, XM - BW * PC - KN.barGap * PC / 2, XM - KN.barGap * PC / 2, -(Math.ceil(P.h80 / BW) * PC), 0, -E, E, 0),
    minB: rectOf(tMin, XM + KN.barGap * PC / 2, XM + KN.barGap * PC / 2 + BW * PC, -(Math.ceil(P.h50 / BW) * PC), 0, -E, E, 0),
  };
  const mk = (id, x, y, z, text, sub, role, pr, sty) => Object.assign({ id, x, y, z, text, sub, role: role || 'secondary', size: role === 'result' ? KN.calloutSize : 0, priority: pr || 0 }, sty || {});
  const yTop = -(TH + E) / 2;
    const back = (q) => { for (let c = COLS - 1; c >= 0; c--) if (QS[c] === q) return c; return 0; };
  const ca = colTop(back(4), false), cn = colTop(back(0), false), sf = colTop(ORDER[Math.min(P.n4, 4 * SR) - 1], true), sn = colTop(ORDER[NT - P.n0 + Math.min(P.n0, SR) - 1], true);
  const LST = {
    case: [mk('a.tasks', HW + 6, yTop, -HD * 0.5, '', '', 'result'), mk('a.tries', HW + 6, yTop, -HD * 0.05, '', '', 'result'), mk('a.pass', HW + 6, yTop, HD * 0.4, '', '', 'result'), mk('a.pct', HW + 6, yTop, HD * 0.85, '', '', 'result')],
    side: [mk('c.all', ca[0], ca[1], ca[2], '', '', 'result'), mk('c.none', cn[0], cn[1], cn[2], '', '', 'result'), mk('s.full', sf[0], sf[1], sf[2], '', '', 'result'), mk('s.none', sn[0], sn[1], sn[2], '', '', 'result')],
    pr: [mk('r.prs', (PRC * PC) / 2, -E / 2, ZP - (PRR * PC) / 2, '', '', 'result'), mk('r.swe', -(PRC * PC) / 2, -E / 2, ZP - (PRR * PC) / 2, '', '', 'result')],
    prB: [mk('r.half', (PRC * PC) / 4, -E / 2, ZP + hgp + PC / 2, '', '', 'result')],
  };
  AN = {
    bar: [mk('p.bar', SW + KN.planeMargin, ym, SD + KN.planeMargin, 'THE ALL-FOUR BAR', null, 'secondary', 1)],
    min: [mk('m.27', ...topOfBar(XM - (BW * PC + KN.barGap * PC) / 2, P.h80), P.h80 + ' min', null, 'secondary', 1, { fam: 'disp', size: KN.refPinSize, color: 'accent' }), mk('m.289', ...topOfBar(XM + (BW * PC + KN.barGap * PC) / 2, P.h50), P.h50h + ' h ' + P.h50m + ' min', null, 'secondary', 1)],
  };
  // callout-only scenes: the anchor list is a function of t that returns just the anchor the callout follows (an ordinary label for it is suppressed
  // by gl-labels while the callout is on it, and no other anchor exists), so nothing but the callout is ever drawn
  const only = (list, sched) => { const by = {}; list.forEach((a) => { by[a.id] = [a]; }); const none = [];
    return (t) => { let id = null; for (const e of sched) if (e.t <= t + 1e-9) id = e.id; return (id && by[id]) || none; }; };
  const SCH_ = {
    case: [[0, null], [KN.cTasks, 'a.tasks'], [KN.cTries, 'a.tries'], [KN.cPass, 'a.pass'], [KN.cPct, 'a.pct'], [KN.cPctEnd, null]],
    side: [[0, null], [KN.cAll, 'c.all'], [KN.cNone, 'c.none'], [KN.cNoneEnd, null], [KN.c44, 's.full'], [KN.c22, 's.none'], [KN.c22End, null], [KN.c44of, 's.full'], [KN.c383, 's.full'], [KN.c383End, null]],
    pr: [[0, null], [KN.cPrs, 'r.prs'], [KN.cSwe, 'r.swe'], [KN.cSweEnd, null]],
    prB: [[0, null], [KN.cHalf, 'r.half'], [KN.cHalfEnd, null]],
  };
  Object.keys(SCH_).forEach((k) => { AN[k] = only(LST[k], SCH_[k].map((e) => ({ t: e[0], id: e[1] }))); });
  const base = { w: 960, h: 540, fps: 30, hold: KN.hold, leader: KN.leader, margin: 14, occlusion: false, maxShown: KN.maxShown, sticky: 'window', measure: MEAS, measureKey: 'pet-a' };
  const BAND = [0, 0, 960, 46], CAP = [0, 418, 960, 540], LEG = [30, 50, 312, 132], SCH = [620, 50, 930, 74];
  const co = (sched) => ({ leader: KN.calloutLeader, size: KN.calloutSize, schedule: sched });
  const S = (t, id, text, sub) => ({ t, id, text, sub });
  OPT = {
    case: Object.assign({}, base, { reserve: [BAND, CAP, LEG, RECT.plan], callout: co([S(0, null),
      S(KN.cTasks, 'a.tasks', '' + P.tasks, 'TASKS · ONE TILE EACH'), S(KN.cTries, 'a.tries', '' + P.tries, 'TRIES · ONE CUBE EACH'),
      S(KN.cPass, 'a.pass', '' + P.passed, 'PASSED · A LIT CUBE'), S(KN.cPct, 'a.pct', pc1(P.pass1), 'OF TRIES PASS'), S(KN.cPctEnd, null)]) }),
    side: Object.assign({}, base, { reserve: [BAND, CAP, LEG, RECT.side, RECT.sorted], callout: co([S(0, null),
      S(KN.cAll, 'c.all', 'All four lit', 'ONE TASK · FOUR TRIES'), S(KN.cNone, 'c.none', 'None lit', 'ONE TASK · NONE PASSED'), S(KN.cNoneEnd, null),
      S(KN.c44, 's.full', '' + P.n4, 'TASKS PASS ALL FOUR TRIES'), S(KN.c22, 's.none', '' + P.n0, 'TASKS NEVER PASS'), S(KN.c22End, null),
      S(KN.c44of, 's.full', P.n4 + ' of ' + P.tasks, 'COLUMNS LIT ALL THE WAY'), S(KN.c383, 's.full', pc1(P.pass4), 'PASS ALL FOUR TRIES'), S(KN.c383End, null)]) }),
    bar: Object.assign({}, base, { reserve: [BAND, CAP, LEG, [150, 56, 810, 126], RECT.side, RECT.sorted], callout: null }),
    pr: Object.assign({}, base, { reserve: [BAND, CAP, LEG, SCH, RECT.pr], callout: co([S(0, null),
      S(KN.cPrs, 'r.prs', '' + P.prs, 'PULL REQUESTS PASS THE TESTS'), S(KN.cSwe, 'r.swe', pc1(P.swe), 'TOP SWE-BENCH VERIFIED SCORE'), S(KN.cSweEnd, null)]) }),
    prB: Object.assign({}, base, { reserve: [BAND, CAP, LEG, SCH, RECT.prA, RECT.prB], callout: co([S(0, null),
      S(KN.cHalf, 'r.half', 'About half', 'WOULD NOT BE MERGED'), S(KN.cHalfEnd, null)]) }),
    min: Object.assign({}, base, { reserve: [BAND, CAP, LEG, RECT.minA, RECT.minB], callout: co([S(0, null),
      S(KN.cMin27, 'm.27', P.h80 + ' min', 'AT THE ' + P.r80 + ' % BAR'), S(KN.cMin27End, null),
      S(KN.cMin289, 'm.289', P.h50h + ' h ' + P.h50m + ' min', 'AT THE ' + P.r50 + ' % BAR'), S(KN.cRatio, 'm.289', 'about ' + P.horizonRatio + 'x', 'LONGER THAN AT THE ' + P.r80 + ' % BAR'), S(KN.cRatioEnd, null)]) }),
  };
}

/* ── text over the scene (all SVG with data-role; nothing here enters the caption band, y >= 418) ── */
function stageText(K, t) {
  const C = K.ROLES, sc = sceneAt(t);
  // header: film name left, the operation right (T7: say which operation it is)
  K.tx('hd.l', 'chrome', 40, 30, 'PASS EVERY TIME · THE TEST FLOOR', { size: 12, fill: C.muted, role: 'chrome', ls: 1.5 });
  const ph = t < KN.tileT0 ? 'THE BELIEF' : t < KN.m1T0 ? 'THE FIELD, SEEN FROM ABOVE' : t < KN.m1T1 ? 'TURNING THE FIELD TO THE SIDE' : t < KN.m2T0 ? 'ONE COLUMN PER TASK'
    : t < KN.m2T1 ? 'SORTED BY TRIES PASSED' : t < KN.m3T0 ? 'THE SAME COLUMNS, IN ORDER' : t < KN.m3T1 ? 'CUT AT THE ALL-FOUR BAR' : t < KN.prCut ? 'ONLY COLUMNS LIT ALL THE WAY STAY BRIGHT'
    : t < KN.m4T0 ? 'ONE SHEET OF PULL REQUESTS' : t < KN.ghost0 ? 'SPLIT BY WHAT A MAINTAINER WOULD MERGE' : t < KN.minCut ? 'MERGED AND NOT MERGED' : t < KN.tauCut ? 'TASK LENGTH, ONE CUBE A MINUTE'
    : t < KN.bookT1 ? 'BACK TO THE FIELD' : 'MONDAY';
  K.tx('hd.r', 'chrome', 920, 30, ph, { size: 12, fill: C.muted, role: 'chrome', anchor: 'end', ls: 1.5 });
  K.ln('hd.rule', 'chrome', 40, 40, 920, 40, { stroke: C.line, w: 0.75, op: 0.8 });

  // HOOK: the belief, then the doubt, as set type over the empty floor (no digit, no cube)
  const h1 = win(t, KN.hook1In, KN.hook1In + 0.6, KN.hook1Out, KN.hook1Out + 0.5), h2 = win(t, KN.hook2In, KN.hook2In + 0.6, KN.hook2Out, KN.hook2Out + 0.6);
  if (h1 > 0.01) {
    K.tx('hk.e1', 'labels', 480, 168, 'THE BELIEF', { size: 12, fill: C.muted, role: 'chrome', anchor: 'middle', ls: 3, op: h1 });
    K.tx('hk.a1', 'labels', 480, 224, 'Usually right', { fam: 'disp', size: KN.hookSize, fill: C.ink, role: 'must-read', anchor: 'middle', op: h1 });
    K.tx('hk.a2', 'labels', 480, 224 + KN.hookSize * 1.15, 'means mostly done.', { fam: 'disp', size: KN.hookSize, fill: C.accent, role: 'must-read', anchor: 'middle', op: h1 });
  }
  if (h2 > 0.01) {
    K.tx('hk.e2', 'labels', 480, 190, 'COUNT EVERY TRY', { size: 12, fill: C.muted, role: 'chrome', anchor: 'middle', ls: 3, op: h2 });
    K.tx('hk.b', 'labels', 480, 262, 'Does it?', { fam: 'disp', size: KN.hookSize * 1.4, fill: C.ink, role: 'must-read', anchor: 'middle', op: h2 });
  }

  // legend (units, words only): what one tile and one cube are
  const lg = (key, y, s, t0, tEnd) => { const o = win(t, t0, t0 + 0.5, tEnd, tEnd + 0.6); if (o > 0.01) K.tx(key, 'labels', 40, y, s, { size: 14, fill: C.ink, role: 'secondary', op: o }); };
  if (t >= KN.tileT0 - 0.5 && t < KN.prCut) {
    const e = KN.legOut;
    lg('lg.m', 62, 'GPT-4o · tau-bench retail · 2024', KN.tileT0 - 0.4, e);
    lg('lg.1', 84, 'ONE TILE = ONE TASK', KN.cTasks - 0.3, e); lg('lg.2', 104, 'ONE CUBE = ONE TRY', KN.cTries - 0.3, e); lg('lg.3', 124, 'GOLD = THE TRY PASSED', KN.litT0, e);
  }
  if (t >= KN.prCut && t < KN.minCut) lg('lg.pr', 62, 'ONE CUBE = ONE PULL REQUEST', KN.prCut - 0.5, KN.minCut - 0.6);
  if (t >= KN.minCut && t < KN.tauCut) lg('lg.mi', 62, 'ONE CUBE = ONE MINUTE', KN.minCut - 0.5, KN.tauCut - 0.6);
  if (t >= KN.bookT1) {   // the bookend: the opening frame, read again (same legend corner, the new meaning of gold)
    lg('lg.cm', 62, 'GPT-4o · tau-bench retail · 2024', KN.bookT1, KN.qOut); lg('lg.c1', 84, 'ONE TILE = ONE TASK', KN.bookT1, KN.qOut);
    lg('lg.c2', 104, 'GOLD = PASSED ALL FOUR TRIES', KN.bookT1, KN.qOut);
  }

  // callouts and pins through gl-labels (screen space, hysteresis, hard cuts; labels are off while a move runs)
  const keepAll = null;
  if (sc === 'tau' && t >= KN.cTasks - 0.2 && t < KN.m1T0) drawPl(K, 'cs.', GLL.solve(t, CAMFN, AN.case, OPT.case), 1, keepAll);
  if (sc === 'tau' && t >= KN.m1T1 && t < KN.prCut) {
    const sol = GLL.solve(t, CAMFN, AN.side, OPT.side);
    drawPl(K, 'sd.', sol, 1, keepAll);
    const pb = win(t, KN.m3T1 + 0.2, KN.m3T1 + 0.8, KN.planeOut - 0.2, KN.planeOut + 0.6);
    if (pb > 0.01) drawPl(K, 'bar.', GLL.solve(t, CAMFN, AN.bar, OPT.bar), pb, keepAll);
  }
  if (sc === 'pr') drawPl(K, 'pr.', t < KN.m4T0 ? GLL.solve(t, CAMFN, AN.pr, OPT.pr) : GLL.solve(t, CAMFN, AN.prB, OPT.prB), 1, keepAll);
  if (sc === 'min') {
    const sol = GLL.solve(t, CAMFN, AN.min, OPT.min);
    drawPl(K, 'mn.', sol, 1, (q) => q.callout || (q.id === 'm.27' ? t >= KN.min27T1 : t >= KN.cMin289));
  }

  // COUNT: the ladder (one row of ratios, each after the counts it comes from) and the paper's own sentence
  const lad = [['ONE TRY · ' + P.passed + ' OF ' + P.tries + ' TRIES', pc1(P.pass1), KN.lad1, KN.ladXL, C.ink], ['EVERY TRY · ' + P.n4 + ' OF ' + P.tasks + ' TASKS', pc1(P.pass4), KN.lad4, KN.ladXR, C.accent]];
  lad.forEach((r, i) => {
    const ok = win(t, r[2], r[2] + 0.5, KN.ladOut, KN.ladOut + 0.5), ov = win(t, r[2] + KN.ladLead, r[2] + KN.ladLead + 0.5, KN.ladOut, KN.ladOut + 0.5);
    if (ov > 0.01) K.tx('ld.v' + i, 'labels', r[3], 86, r[1], { fam: 'disp', size: KN.ladSize, fill: r[4], role: 'must-read', anchor: 'middle', op: ov });
    if (ok > 0.01) K.tx('ld.k' + i, 'labels', r[3], 106, r[0], { size: 14, fill: C.muted, role: 'secondary', anchor: 'middle', ls: 0.5, op: ok });
  });
  const pp = win(t, KN.paperIn, KN.paperIn + 0.6, KN.paperOut, KN.paperOut + 0.6);
  if (pp > 0.01) {
    K.tx('pp.v', 'labels', 480, 88, 'under ' + P.paperPass8Upper + ' %', { fam: 'disp', size: KN.plateSize, fill: C.accent, role: 'must-read', anchor: 'middle', op: pp });
    K.tx('pp.k', 'labels', 480, 109, 'THE PAPER’S OWN RUN · ALL EIGHT TRIES PASS · NOT THESE CUBES', { size: 14, fill: C.muted, role: 'secondary', anchor: 'middle', ls: 1, op: pp });
  }

  // M4: "schematic" tag while the PRs travel (the split is two equal blocks, not a count)
  const sch = win(t, KN.m4T0, KN.m4T0 + 0.6, KN.cHalfEnd - 0.4, KN.cHalfEnd);
  if (sch > 0.01) K.tx('sc.t', 'labels', 920, 62, 'SCHEMATIC SPLIT · TWO EQUAL BLOCKS', { size: 14, fill: C.muted, role: 'secondary', anchor: 'end', op: sch });

  // MONDAY: the question, then the one honest line, both as set type in the free top band
  const q = win(t, KN.qIn, KN.qIn + 0.7, KN.qOut, KN.qOut + 0.5), xl = 40, xr = RECT.plan[2] + KN.colPad, wl = RECT.plan[0] - KN.colPad - xl, wr = 920 - xr;
  if (q > 0.01) {
    K.tx('mo.e', 'labels', xl, KN.monY - 40, 'MONDAY', { size: 12, fill: C.muted, role: 'chrome', ls: 3, op: q });
    K.wrap('How often does it pass when it has to pass every time, and who checks the merge?', wl, KN.mondaySize, 'disp').forEach((s, i) => K.tx('mo.q' + i, 'labels', xl, KN.monY + i * KN.mondaySize * 1.2, s, { fam: 'disp', size: KN.mondaySize, fill: C.ink, role: 'must-read', op: q }));
  }
  const hn = win(t, KN.honestIn, KN.honestIn + 0.8, KN.qOut, KN.qOut + 0.5);
  if (hn > 0.01) {
    K.tx('mo.h', 'labels', xr, KN.monY - 40, 'ONE LIMIT', { size: 12, fill: C.muted, role: 'chrome', ls: 3, op: hn });
    K.wrap('One ' + P.year + ' model, and agents that could not revise: newer ones may do better.', wr, KN.honestSize, 'disp').forEach((s, i) => K.tx('mo.h' + i, 'labels', xr, KN.monY + i * KN.honestSize * 1.2, s, { fam: 'disp', size: KN.honestSize, fill: C.accent, role: 'must-read', op: hn }));
  }
}

window.FILM_RENDER = {
  async setup(p, K) {
    palette(K);
    GEO = bake(p, K);
    SH = p.createShader(VERT, FRAG);
    CAM = p.createCamera();
    RIGC = RIG.compile(rigScript(), null);
    CAMFN = (t) => camAt(t);
    setupLabels();
    p.setCamera(K.cam0);
    // exact counts at any t, for the evaluator and the gate: marks drawn per kind (the arrival rule of the shader)
    const W = KN.arrW;
    window.__pet = { n: NCUBE, kinds: KINDN.slice(), cam: camAt, poseAt, rect: RECT, order: ORDER, qs: QS,
      count: (t) => { const f = (a, b, n) => { const pr = seg(t, a, b) * (1 + W); let k = 0; for (let i = 0; i < n; i++) if ((pr - i / n) / W > 0) k++; return k; };
        return { tiles: f(KN.tileT0, KN.tileT1, NT), tries: f(KN.cubeT0, KN.cubeT1, NT * 4), prs: f(KN.prT0, KN.prT1, P.prs), m27: f(KN.min27T0, KN.min27T1, P.h80), m289: f(KN.min289T0, KN.min289T1, P.h50) }; },
      sol: (w, t) => { const r = GLL.solve(t, CAMFN, AN[w], OPT[w]); return r.placements.map((q) => [q.id, q.callout, Math.round(q.box[0]), Math.round(q.box[1]), Math.round(q.box[2]), Math.round(q.box[3])]); } };
  },

  render(t, s, K) {
    const p = K.p, cam = camAt(t);
    CAM.camera(cam.eye[0], cam.eye[1], cam.eye[2], cam.look[0], cam.look[1], cam.look[2], cam.up[0], cam.up[1], cam.up[2]);
    CAM.perspective(cam.fov, 960 / 540, RIGC.near, RIGC.far);
    p.setCamera(CAM); p.noLights();
    floorDraw(p, sceneAt(t));
    cubesDraw(p, t);
    planeDraw(p, t);
    stageText(K, t);
  },
};
})();
