/* one-query draft B · lib/arsenal.gen.js is GENERATED by lib/assemble.py from verbatim copies (sha256 below).
   Modules: scale-anchor.js, gl-heightfield.js, gl-camera-rig.js, gl-labels.js */
window.ARSENAL = window.ARSENAL || {}; ['patterns','structures','materials','brands','core'].forEach(function (k) { window.ARSENAL[k] = window.ARSENAL[k] || {}; });
/* lib/scale-anchor.js sha256 a6019ad0ae335e4f (patched) */
(function(){
const A=(window.ARSENAL=window.ARSENAL||{patterns:{},structures:{},materials:{},brands:{}});
function mulberry32(a){return function(){a|=0;a=a + 0x6D2B79F5|0;let t=Math.imul(a ^ a>>>15,1|a);t=t + Math.imul(t ^ t>>>7,61|t)^ t;return((t ^ t>>>14)>>>0)/ 4294967296;};}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const smooth=u=>{u=clamp(u,0,1);return u*u*(3 - 2*u);};
const EASE={
linear:u=>u,
quad:u=>u<.5?2*u*u:1 - Math.pow(-2*u + 2,2)/ 2,
cubic:u=>u<.5?4*u*u*u:1 - Math.pow(-2*u + 2,3)/ 2,
sine:u=>(1 - Math.cos(Math.PI*u))/ 2,
expo:u=>u<=0?0:u>=1?1:u<.5?Math.pow(2,20*u - 10)/ 2:(2 - Math.pow(2,-20*u + 10))/ 2
};
const NMAX=100000;
const fmt=n=>Math.round(n).toLocaleString('en-US');
const fmtV=v=>v>=100?fmt(v):v>=10?v.toFixed(1):v.toFixed(2);
function spiralIdx(i,j){
const r=Math.max(Math.abs(i),Math.abs(j));if(r===0)return 0;
const base=(2*r - 1)*(2*r - 1);let k;
if(i===r&&j>-r)k=j + r - 1;
else if(j===r)k=2*r +(r - 1 - i);
else if(i===-r)k=4*r +(r - 1 - j);
else k=6*r +(i + r - 1);
return base + k;
}
function timeline(P){
const top=P.top,seg=P.dwell + P.move,rungs=[];
for(let k=0;k<=top;k++)rungs.push({k,n:Math.pow(10,k),t0:k*seg,t1:k*seg + P.dwell});
return{top,dur:(top + 1)*P.dwell + top*P.move,rungs};
}
function level(t,P){
const top=P.top,seg=P.dwell + P.move;if(t<=0)return 0;if(t>=(top + 1)*P.dwell + top*P.move)return top;
const k=Math.min(top,Math.floor(t / seg)),r=t - k*seg;
if(r<=P.dwell||k>=top)return k;
const e=EASE[P.ease]||EASE.cubic;
return k + e(clamp((r - P.dwell)/ P.move,0,1));
}
const countOf=L=>Math.max(1,Math.min(NMAX,Math.round(Math.pow(10,L))));
function lodAlpha(L,P){
if(P.lod==='marks')return 0;if(P.lod==='tiles')return 1;
const Ls=Math.log10(P.budget),w=P.swapW;return smooth((L -(Ls - w / 2))/ w);
}
function setup(p,ctx,P){
const rnd=mulberry32((ctx&&ctx.seed)|0),cx=new Int16Array(NMAX),cy=new Int16Array(NMAX),flags=new Uint8Array(NMAX);
let n=1;cx[0]=0;cy[0]=0;
for(let r=1;n<NMAX;r++){
for(let j=-r + 1;j<=r&&n<NMAX;j++){cx[n]=r;cy[n++]=j;}
for(let i=r - 1;i>=-r&&n<NMAX;i--){cx[n]=i;cy[n++]=r;}
for(let j=r - 1;j>=-r&&n<NMAX;j--){cx[n]=-r;cy[n++]=j;}
for(let i=-r + 1;i<=r&&n<NMAX;i++){cx[n]=i;cy[n++]=-r;}
}
const data=P&&P.data;
for(let k=0;k<NMAX;k++){const u=rnd();flags[k]=data&&k<data.length?(data[k]?1:0):(u<(P&&P.flagFrac||0)?1:0);}
flags[0]=0;
const pre=new Uint32Array(NMAX + 1);for(let k=0;k<NMAX;k++)pre[k + 1]=pre[k]+ flags[k];
return{cx,cy,flags,pre,last:null,tl:timeline(P)};
}
function draw(){}
const BASE={
anchor:'ruler',mark:'dot',dwell:1.2,move:1.3,ease:'cubic',top:5,
budget:2500,tile:4,swapW:.2,lod:'auto',showSwap:false,loupe:false,tileStroke:false,
flagFrac:.125,flagLabel:'flagged',data:null,m2PerPerson:1,
note:'Marks are shrunk, never resampled; past the budget each tile counts its marks.'
};
A.patterns['scale-anchor']={
id:'scale-anchor',atlas:['camera-choreography','world-to-screen','easing-functions','derived-geometry','pure-function-of-t','seeded-determinism','gpu-instancing'],
renderer:'p2d',rendererFor(){return 'p2d';},
params:BASE,
variants:[
{name:'dots-ruler',params:{anchor:'ruler',mark:'dot',budget:2500,tile:4}},
{name:'people-ladder',params:{anchor:'silhouettes',mark:'person',budget:2500,tile:4,flagFrac:0,m2PerPerson:1,note:'Assumption: one person per square metre, set m2PerPerson to your data.'}},
{name:'tiles-lod',params:{anchor:'ruler',mark:'square',budget:400,tile:5,swapW:.3,showSwap:true,loupe:true,tileStroke:true,note:'Marks are shrunk, never resampled; the swap is shown and every tile counts its marks.'}}
],
setup,draw,EASE,
timeline,level,countOf,lodAlpha,spiralIdx,
count(t,params){const P=Object.assign({},BASE,params);return countOf(level(t,P));},
api:{timeline,level,countOf,lodAlpha,spiralIdx}
};
})();
/* lib/gl-heightfield.js sha256 4a71e92323f28eca (patched) */
(function(){
const A=(window.ARSENAL=window.ARSENAL||{patterns:{},structures:{},materials:{},brands:{}});
function mulberry32(a){return function(){a|=0;a=(a + 0x6D2B79F5)|0;let t=Math.imul(a ^(a>>>15),1|a);t=(t + Math.imul(t ^(t>>>7),61|t))^ t;return((t ^(t>>>14))>>>0)/ 4294967296;};}
const clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x));
const smooth=(x)=>{x=clamp(x);return x*x*x*(x*(x*6 - 15)+ 10);};
const lerp=(a,b,u)=>a +(b - a)*u;
const fmtInt=(n)=>String(n).replace(/\B(?=(\d{3})+(?!\d))/g,',');
const D2R=Math.PI / 180;
const VERT='precision highp float; attribute vec3 aPosition; attribute vec3 aNormal; attribute vec4 aVertexColor;' +
'uniform mat4 uModelViewMatrix; uniform mat4 uProjectionMatrix; varying vec3 vN; varying vec3 vP; varying float vV;' +
'void main(){ vN = aNormal; vP = aPosition; vV = aVertexColor.r; gl_Position = uProjectionMatrix * uModelViewMatrix * vec4(aPosition, 1.0); }';
const FRAG='precision highp float; varying vec3 vN; varying vec3 vP; varying float vV;' +
'uniform vec3 uR0, uR1, uR2, uFill, uLine, uCut, uRim, uKeyDir; uniform float uAmb, uKey, uRimK;' +
'uniform float uStep, uCW, uWire, uCell, uGW, uCutX, uCutW, uClipX, uRevZ; uniform vec2 uOrigin;' +
'void main(){' +
' if (vP.z > uRevZ) discard;' +
' if (vP.x < uClipX) discard;' +
' vec3 n = normalize(vN); float lam = max(dot(n, -uKeyDir), 0.0); float rim = 1.0 - abs(n.y); rim = rim * rim;' +
' vec3 ramp = vV < 0.5 ? mix(uR0, uR1, vV * 2.0) : mix(uR1, uR2, vV * 2.0 - 1.0);' +
' vec3 base = uWire > 0.5 ? uFill : ramp;' +
' vec3 col = base * (uAmb + uKey * lam) + uRim * (uRimK * rim);' +
' float h = -vP.y; float s = length(n.xz) / max(abs(n.y), 0.05);' +
' if (uStep > 0.0) { float f = h / uStep; float d = abs(fract(f + 0.5) - 0.5) * uStep;' +
'   float major = 1.0 - step(0.5, abs(mod(floor(f + 0.5), 5.0)));' +
'   float w = uCW * (1.0 + 0.9 * major); float dh = d / max(s, 0.03);' +
'   float a = (1.0 - smoothstep(w * 0.5, w * 0.5 + 0.7, dh)) * step(0.5 * uStep, h);' +
'   col = mix(col, uLine, a * (0.55 + 0.35 * major)); }' +
' if (uWire > 0.5) { vec2 g = (vP.xz - uOrigin) / uCell; vec2 dg = abs(fract(g + 0.5) - 0.5) * uCell;' +
'   float a = 1.0 - smoothstep(uGW * 0.5, uGW * 0.5 + 0.6, min(dg.x, dg.y)); col = mix(col, ramp, a); }' +
' if (uCutW > 0.0) { float a = 1.0 - smoothstep(uCutW * 0.5, uCutW * 0.5 + 0.8, abs(vP.x - uCutX)); col = mix(col, uCut, a); }' +
' gl_FragColor = vec4(col, 1.0); }';
const rgb=(p,c)=>{c=p.color(c);return[p.red(c)/ 255,p.green(c)/ 255,p.blue(c)/ 255];};
const mixC=(p,a,b,u)=>p.lerpColor(p.color(a),p.color(b),u);
const norm=(v)=>{const l=Math.hypot(...v);return v.map((x)=>x / l);};
function toMatrix(d){
if(!d)return null;
if(Array.isArray(d))return d.map((r)=>Array.from(r,Number));
if(d.values){const m=[];for(let r=0;r<d.rows;r++)m.push(Array.from(d.values.slice(r*d.cols,(r + 1)*d.cols),Number));return m;}
return null;
}
function synth(cols,rows,seed,range){
const rng=mulberry32(seed),K=7,bumps=[];
for(let k=0;k<K;k++)bumps.push({x:0.1 + 0.8*rng(),y:0.1 + 0.8*rng(),s:0.07 + 0.16*rng(),a:(k===0?1:0.25 + 0.6*rng())*(k===5?-0.5:1)});
const ph=[rng()*6.283,rng()*6.283],G=9,lat=[];
for(let i=0;i<G*G;i++)lat.push(rng());
const vn=(u,v)=>{
const x=u*(G - 1),y=v*(G - 1),i=Math.min(G - 2,Math.floor(x)),j=Math.min(G - 2,Math.floor(y)),fx=smooth(x - i),fy=smooth(y - j);
return lerp(lerp(lat[j*G + i],lat[j*G + i + 1],fx),lerp(lat[(j + 1)*G + i],lat[(j + 1)*G + i + 1],fx),fy);
};
const m=[];
for(let r=0;r<rows;r++){
const row=[];
for(let c=0;c<cols;c++){
const u=c /(cols - 1),v=r /(rows - 1);let z=0.12;
for(const b of bumps)z +=b.a*Math.exp(-((u - b.x)**2 +((v - b.y)*1.3)**2)/(2*b.s*b.s));
z +=0.10*Math.sin(u*9 + ph[0])*Math.cos(v*7 + ph[1])+ 0.22*(vn(u,v)- 0.5);
row.push(z);
}
m.push(row);
}
let lo=Infinity,hi=-Infinity;for(const row of m)for(const z of row){lo=Math.min(lo,z);hi=Math.max(hi,z);}
return m.map((row)=>row.map((z)=>+(range[0]+(range[1]- range[0])*(z - lo)/(hi - lo)).toFixed(3)));
}
function buildMesh(p,st,params){
const M=st.M,rows=M.length,cols=M[0].length,XW=params.size,cell=XW /(cols - 1),cellZ=cell*(params.zs||1),ZD=cellZ*(rows - 1);
const x0=-XW / 2,z0=-ZD / 2,H=params.hscale,vmin=st.vmin,span=st.vmax - st.vmin||1;
const C=st.CM,cmin=st.cmin,cspan=st.cmax - st.cmin||1;
const hgt=new Float32Array(rows*cols);
for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)hgt[r*cols + c]=H*clamp((M[r][c]- vmin)/ span);
const g=new p5.Geometry(1,1,undefined,p._renderer);
for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){
const i=r*cols + c;
g.vertices.push(new p5.Vector(x0 + c*cell,-hgt[i],z0 + r*cellZ));
const hx=(hgt[r*cols + Math.min(cols - 1,c + 1)]- hgt[r*cols + Math.max(0,c - 1)])/(cell*((c>0&&c<cols - 1)?2:1));
const hz=(hgt[Math.min(rows - 1,r + 1)*cols + c]- hgt[Math.max(0,r - 1)*cols + c])/(cellZ*((r>0&&r<rows - 1)?2:1));
const n=norm([-hx,-1,-hz]);g.vertexNormals.push(new p5.Vector(n[0],n[1],n[2]));
g.vertexColors.push(clamp((C[r][c]- cmin)/ cspan),0,0,1);
}
for(let r=0;r<rows - 1;r++)for(let c=0;c<cols - 1;c++){
const a=r*cols + c,b=a + 1,d=a + cols,e=d + 1;
g.faces.push([a,d,b],[b,d,e]);
}
const skirt=(a,b,n)=>{const base=g.vertices.length;
for(const i of[a,b]){const v=g.vertices[i],cv=clamp((C[Math.floor(i / cols)][i%cols]- cmin)/ cspan);
g.vertices.push(new p5.Vector(v.x,v.y,v.z),new p5.Vector(v.x,0,v.z));for(let q=0;q<2;q++){g.vertexNormals.push(new p5.Vector(n[0],n[1],n[2]));g.vertexColors.push(cv,0,0,1);}}
g.faces.push([base,base + 1,base + 3],[base,base + 3,base + 2]);};
for(let c=0;c<cols - 1;c++){skirt((rows - 1)*cols + c,(rows - 1)*cols + c + 1,[0,0,1]);skirt(c,c + 1,[0,0,-1]);}
for(let r=0;r<rows - 1;r++){skirt(r*cols,(r + 1)*cols,[-1,0,0]);skirt(r*cols + cols - 1,(r + 1)*cols + cols - 1,[1,0,0]);}
let imax=0;for(let i=1;i<rows*cols;i++)if(M[Math.floor(i / cols)][i%cols]>M[Math.floor(imax / cols)][imax%cols])imax=i;
Object.assign(st,{g,rows,cols,N:rows*cols,cell,cellZ,XW,ZD,x0,z0,hgt,imax,tris:g.faces.length});
}
const FONTCACHE=new WeakMap();
async function faces(p,tk,given){
if(given&&given.disp&&given.mono)return{disp:given.disp,mono:given.mono,note:'host fonts'};
const lib=window.ARSENAL_FONTS||{},keys=Object.keys(lib);
const pick=(role,dflt)=>{
const f=tk.type&&tk.type[role];if(!f)return[dflt,'no role'];
const k=f.family + '|' + f.weight;if(lib[k])return[k,null];
const same=keys.find((x)=>x.split('|')[0]===f.family);if(same)return[same,k + ' -> ' + same];
return[dflt,k + ' -> ' + dflt];
};
const[dk,dn]=pick('disp','Big Shoulders Display|600'),[mk,mn]=pick('mono','IBM Plex Mono|400');
let cache=FONTCACHE.get(p);if(!cache){cache={};FONTCACHE.set(p,cache);}
const load=async(k)=>{if(!lib[k])return null;if(!cache[k])cache[k]=p.loadFont(lib[k]);return cache[k];};
return{disp:await load(dk),mono:await load(mk),note:[dn,mn].filter(Boolean).join('; ')||'pack faces'};
}
function revealRows(u,st,params){if(!params.reveal)return st.rows;return Math.max(1,Math.round(st.rows*smooth((u - params.reveal[0])/(params.reveal[1]- params.reveal[0]))));}
function cutAt(u,st,params){
if(!params.cut||params.cutMode==='off')return null;
const a=(u - params.cut[0])/(params.cut[1]- params.cut[0]);if(a<0)return null;
const col=Math.round(lerp(params.cutMargin,st.cols - 1 - params.cutMargin,smooth(a)));
const prof=[];let pk=0;
for(let r=0;r<st.rows;r++){prof.push(st.M[r][col]);if(st.M[r][col]>st.M[pk][col])pk=r;}
return{col,x:st.x0 + col*st.cell,prof,pk};
}
function keyed(arr,u){
if(!Array.isArray(arr))return arr;if(arr.length===1)return arr[0];
const s=clamp(u)*(arr.length - 1),i=Math.min(arr.length - 2,Math.floor(s));
return lerp(arr[i],arr[i + 1],smooth(s - i));
}
function camAt(u,st,params,cut){
const cu=clamp((u - params.camT[0])/(params.camT[1]- params.camT[0]));
const az=keyed(params.camAz,cu)*D2R,el=clamp(keyed(params.camEl,cu),1,89)*D2R,dist=keyed(params.camDist,cu)*st.XW;
const fx=params.camLook==='cut'&&cut?cut.x*params.follow:0;
const look=[fx,-params.hscale*0.35,0];
const eye=[look[0]+ dist*Math.cos(el)*Math.sin(az),look[1]- dist*Math.sin(el),look[2]+ dist*Math.cos(el)*Math.cos(az)];
return{eye,look,az:az / D2R,el:el / D2R};
}
const valStr=(v,params)=>v.toFixed(params.dp)+(params.unit||'');
function terrain(p,st,tk,params,cut,revZ){
const sh=st.sh,c=tk.color,R=params.ramp.map((role)=>rgb(p,c[role]));
p.shader(sh);p.noStroke();p.fill(255);
sh.setUniform('uR0',R[0]);sh.setUniform('uR1',R[1]);sh.setUniform('uR2',R[2]);
sh.setUniform('uFill',rgb(p,mixC(p,c.bg,c.panel,0.7)));
sh.setUniform('uLine',rgb(p,params.wire?c.accent:c[params.contourRole]));
sh.setUniform('uCut',rgb(p,c.accent2));sh.setUniform('uRim',rgb(p,c.chalk));
sh.setUniform('uKeyDir',norm([-0.5,0.75,-0.35]));sh.setUniform('uAmb',params.amb);sh.setUniform('uKey',params.key);sh.setUniform('uRimK',params.rim);
sh.setUniform('uStep',params.contours>0?params.hscale / params.contours:0);sh.setUniform('uCW',params.contourW);
sh.setUniform('uWire',params.wire?1:0);sh.setUniform('uCell',st.cell);sh.setUniform('uGW',params.gridW);sh.setUniform('uOrigin',[st.x0,st.z0]);
sh.setUniform('uCutX',cut?cut.x:-1e6);sh.setUniform('uCutW',cut&&params.cutMode==='band'?params.cutW:0);
sh.setUniform('uClipX',cut&&params.cutMode==='section'?cut.x - 0.02:-1e6);sh.setUniform('uRevZ',revZ);
p.model(st.g);p.resetShader();
}
function section3d(p,st,tk,params,cut,rowsShown){
const c=tk.color,x=cut.x,n=Math.min(rowsShown,st.rows),slab=params.slab;
if(params.cutMode==='section'){
p.noStroke();p.fill(mixC(p,c.bg,c.accent2,0.85));
p.beginShape(p.TRIANGLE_STRIP);
for(let r=0;r<n;r++){const z=st.z0 + r*st.cell,h=st.hgt[r*st.cols + cut.col];p.vertex(x - 0.05,-h,z);p.vertex(x - 0.05,slab,z);}
p.endShape();
p.noFill();p.stroke(c.chalk);p.strokeWeight(2);
p.beginShape();for(let r=0;r<n;r++)p.vertex(x - 0.3,-st.hgt[r*st.cols + cut.col],st.z0 + r*st.cell);p.endShape();
}else{
const pl=p.color(c.ink);pl.setAlpha(255*0.07);p.noStroke();p.fill(pl);
p.beginShape(p.TRIANGLE_STRIP);
p.vertex(x,0,st.z0);p.vertex(x,-params.hscale*1.15,st.z0);p.vertex(x,0,st.z0 +(n - 1)*st.cell);p.vertex(x,-params.hscale*1.15,st.z0 +(n - 1)*st.cell);
p.endShape();
}
}
A.patterns['gl-heightfield']={
id:'gl-heightfield',atlas:['webgl-mode','build-geometry','p5-strands','lights-and-materials','world-to-screen','camera-slerp','camera-choreography','gpu-instancing','frontier-2026','derived-geometry'],
renderer:'webgl',
params:{
data:null,colorData:null,cols:80,rows:50,synthRange:[0,100],vmin:null,vmax:null,dp:1,unit:'',
dur:12,size:760,hscale:170,slab:14,
wire:false,gridW:1.1,contours:10,contourW:1.1,contourRole:'chalk',ramp:['panel','muted','accent'],amb:0.42,key:0.72,rim:0.10,
reveal:[0.02,0.28],cut:[0.32,0.92],cutMode:'band',cutW:2.4,cutMargin:1,profile:false,profileBox:[560,330,370,170],
camT:[0,1],camAz:[-38,8,42],camEl:[40,30,26],camDist:[1.45,1.25,1.12],camLook:'centre',follow:0.6,fov:0.78,
pins:true,hud:true,
},
variants:[
{name:'wire-40x25',params:{cols:40,rows:25,wire:true,contours:0,cut:null,gridW:1.4,camAz:[32,-6,-34],camEl:[42,34],camDist:[1.4,1.2],reveal:[0.02,0.45]}},
{name:'lit-200x120',params:{cols:200,rows:120,contours:12,contourW:0.9,cutW:2.0}},
{name:'section-120x80',params:{cols:120,rows:80,cutMode:'section',profile:true,contours:8,reveal:[0.0,0.2],cut:[0.24,0.94],cutMargin:4,
camAz:[-62,-54,-46],camEl:[30,24,22],camDist:[1.3,1.1,1.0],camLook:'cut',follow:0.55}},
{name:'plan-80x50',params:{cols:80,rows:50,contours:10,cut:null,reveal:null,camT:[0.12,0.8],camAz:[0,0,24],camEl:[89,60,34],camDist:[1.5,1.3,1.15]}},
],
setup:async function(p,ctx,params){
const seed=ctx.seed==null?7:ctx.seed,tk=ctx.tokens||A.brands['ceti-dark'];
const st={seed};
st.M=toMatrix(params.data)||synth(params.cols,params.rows,seed,params.synthRange);
st.CM=toMatrix(params.colorData)||st.M;
let lo=Infinity,hi=-Infinity,clo=Infinity,chi=-Infinity;
for(const row of st.M)for(const v of row){lo=Math.min(lo,v);hi=Math.max(hi,v);}
for(const row of st.CM)for(const v of row){clo=Math.min(clo,v);chi=Math.max(chi,v);}
st.vmin=params.vmin==null?lo:params.vmin;st.vmax=params.vmax==null?hi:params.vmax;st.cmin=clo;st.cmax=chi;
buildMesh(p,st,params);
st.sh=p.createShader(VERT,FRAG);st.work=p.createCamera();st.hud=p.createCamera();
st.fonts=await faces(p,tk,ctx.fonts);st.fontNote=st.fonts.note;
return st;
},
api:{terrain},
count(t,st,params){
const u=clamp(t / params.dur),rows=revealRows(u,st,params),cut=cutAt(u,st,params);
return{cells:rows*st.cols,of:st.N,rows,cols:st.cols,contours:params.contours,cutCol:cut?cut.col + 1:null,cutPeak:cut?st.M[cut.pk][cut.col]:null};
},
};
})();
/* lib/gl-camera-rig.js sha256 1b4cc859ead02a78 (patched) */
(function(){
const A=(window.ARSENAL=window.ARSENAL||{patterns:{},structures:{},materials:{},brands:{}});
const EASE_COPY={
linear:(u)=>u,smooth:(u)=>u*u*(3 - 2*u),in:(u)=>u*u*u,out:(u)=>1 - Math.pow(1 - u,3),
inout:(u)=>(u<0.5?4*u*u*u:1 - Math.pow(-2*u + 2,3)/ 2),expo:(u)=>(u>=1?1:1 - Math.pow(2,-10*u)),
back:(u)=>1 + 2.70158*Math.pow(u - 1,3)+ 1.70158*Math.pow(u - 1,2),step:(u)=>(u>=1?1:0),
};
const EASES=()=>(A.core&&A.core.timeline&&A.core.timeline.ease)||EASE_COPY;
const EASE_NAMES=['linear','smooth','in','out','inout','expo','back','step'];
const easeOf=(name)=>EASES()[name||'inout']||EASES().inout;
function mulberry32(a){return function(){a|=0;a=(a + 0x6D2B79F5)|0;let t=Math.imul(a ^(a>>>15),1|a);t=(t + Math.imul(t ^(t>>>7),61|t))^ t;return((t ^(t>>>14))>>>0)/ 4294967296;};}
const clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x));
const lerp=(a,b,u)=>a +(b - a)*u;
const geo=(a,b,u)=>(a>0&&b>0?a*Math.pow(b / a,u):lerp(a,b,u));
const D2R=Math.PI / 180,R2D=180 / Math.PI;
const add=(a,b)=>[a[0]+ b[0],a[1]+ b[1],a[2]+ b[2]],sub=(a,b)=>[a[0]- b[0],a[1]- b[1],a[2]- b[2]];
const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s],dot=(a,b)=>a[0]*b[0]+ a[1]*b[1]+ a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]- a[2]*b[1],a[2]*b[0]- a[0]*b[2],a[0]*b[1]- a[1]*b[0]];
const len=(a)=>Math.hypot(a[0],a[1],a[2]),nrm=(a)=>{const l=len(a)||1;return[a[0]/ l,a[1]/ l,a[2]/ l];};
const mix=(a,b,u)=>[lerp(a[0],b[0],u),lerp(a[1],b[1],u),lerp(a[2],b[2],u)];
const fmt=(n)=>String(n).replace(/\B(?=(\d{3})+(?!\d))/g,',');
function basis(eye,center,up){
const z=nrm(sub(eye,center));let x=cross(up,z);
if(len(x)<1e-9)x=cross([0,0,-1],z);
x=nrm(x);return{x,y:cross(z,x),z};
}
function quatOf(B0,B1){
const R=[[0,0,0],[0,0,0],[0,0,0]];
for(const k of['x','y','z'])for(let i=0;i<3;i++)for(let j=0;j<3;j++)R[i][j]+=B1[k][i]*B0[k][j];
const tr=R[0][0]+ R[1][1]+ R[2][2];let w,x,y,z,S;
if(tr>0){S=Math.sqrt(tr + 1)*2;w=0.25*S;x=(R[2][1]- R[1][2])/ S;y=(R[0][2]- R[2][0])/ S;z=(R[1][0]- R[0][1])/ S;}
else if(R[0][0]>R[1][1]&&R[0][0]>R[2][2]){S=Math.sqrt(1 + R[0][0]- R[1][1]- R[2][2])*2;w=(R[2][1]- R[1][2])/ S;x=0.25*S;y=(R[0][1]+ R[1][0])/ S;z=(R[0][2]+ R[2][0])/ S;}
else if(R[1][1]>R[2][2]){S=Math.sqrt(1 + R[1][1]- R[0][0]- R[2][2])*2;w=(R[0][2]- R[2][0])/ S;x=(R[0][1]+ R[1][0])/ S;y=0.25*S;z=(R[1][2]+ R[2][1])/ S;}
else{S=Math.sqrt(1 + R[2][2]- R[0][0]- R[1][1])*2;w=(R[1][0]- R[0][1])/ S;x=(R[0][2]+ R[2][0])/ S;y=(R[1][2]+ R[2][1])/ S;z=0.25*S;}
return w<0?[-w,-x,-y,-z]:[w,x,y,z];
}
function rotate(v,k,a){
const c=Math.cos(a),s=Math.sin(a),kv=cross(k,v),kd=dot(k,v)*(1 - c);
return[v[0]*c + kv[0]*s + k[0]*kd,v[1]*c + kv[1]*s + k[1]*kd,v[2]*c + kv[2]*s + k[2]*kd];
}
function scalars(a,b,s){
return{fov:2*Math.atan(geo(Math.tan(a.fov / 2),Math.tan(b.fov / 2),s)),zoom:geo(a.zoom,b.zoom,s),focus:geo(a.focus,b.focus,s),aperture:lerp(a.aperture,b.aperture,s)};
}
function slerpPose(a,b,s){
const d0=len(sub(a.eye,a.center)),d1=len(sub(b.eye,b.center)),u=geo(d0,d1,s);
const l=sub(a.eye,b.eye),c=add(sub(l,a.center),b.center),cc=dot(c,c);
const d=cc>1e-6?clamp(dot(l,c)/ cc):1;
const f=mix(mix(a.eye,a.center,d),mix(b.eye,b.center,d),s);
const B0=basis(a.eye,a.center,a.up),B1=basis(b.eye,b.center,b.up),q=quatOf(B0,B1);
const half=Math.acos(clamp(q[0],-1,1)),sh=Math.sin(half);let z,y;
if(sh<1e-7){z=nrm(mix(B0.z,B1.z,s));y=nrm(mix(B0.y,B1.y,s));}
else{const k=[q[1]/ sh,q[2]/ sh,q[3]/ sh],ang=2*half*s;z=rotate(B0.z,k,ang);y=rotate(B0.y,k,ang);}
return Object.assign({eye:add(f,mul(z,d*u)),center:add(f,mul(z,(d - 1)*u)),up:y,pivot:d},scalars(a,b,s));
}
function trackPose(a,b,s){return Object.assign({eye:mix(a.eye,b.eye,s),center:mix(a.center,b.center,s),up:nrm(mix(a.up,b.up,s))},scalars(a,b,s));}
const sph=(az,el,r)=>[r*Math.cos(el)*Math.sin(az),-r*Math.sin(el),r*Math.cos(el)*Math.cos(az)];
function sphOf(eye,c){const v=sub(eye,c),r=len(v)||1;return{r,az:Math.atan2(v[0],v[2]),el:Math.asin(clamp(-v[1]/ r,-1,1))};}
function orbitPose(a,b,s,o){
const center=mix(o.c0,o.c1,s),eye=add(center,sph(o.az0 + o.daz*s,lerp(o.el0,o.el1,s),geo(o.r0,o.r1,s)));
return Object.assign({eye,center,up:a.up},scalars(a,b,s));
}
function resolveIdx(spec,scene){
const N=scene&&scene.points?scene.points.length:0;if(!N)return -1;
if(typeof spec==='number')return Math.round(clamp(spec,0,N - 1));
const ord=scene.order||scene.points.map((_,i)=>i);
if(spec==='max')return ord[0];if(spec==='min')return ord[ord.length - 1];if(spec==='median')return ord[Math.floor(ord.length / 2)];
return -1;
}
function resolvePt(spec,scene){
if(Array.isArray(spec))return spec.slice(0,3);
const i=resolveIdx(spec,scene);return i<0?null:scene.points[i].slice(0,3);
}
const depthOf=(pt,pose)=>dot(sub(pt,pose.eye),nrm(sub(pose.center,pose.eye)));
const SCHEME={orbit:'orbit',crane:'track',cut:'cut',dolly:'slerp',lookat:'slerp',focus:'slerp',key:'slerp'};
function endPose(P,m,scene){
const Q={eye:P.eye.slice(),center:P.center.slice(),up:P.up.slice(),fov:P.fov,zoom:P.zoom,focus:P.focus,aperture:P.aperture};
let orbit=null,target=null;
if(m.move==='orbit'){
const c1=m.around!=null?resolvePt(m.around,scene)||P.center:P.center,o=sphOf(P.eye,P.center);
const el1=m.el!=null?clamp(m.el,-89,89)*D2R:o.el,r1=o.r*(m.r==null?1:m.r);
orbit={c0:P.center.slice(),c1,az0:o.az,daz:(m.az||0)*D2R,el0:o.el,el1,r0:o.r,r1};
Q.center=c1.slice();Q.eye=add(c1,sph(o.az + orbit.daz,el1,r1));
}else if(m.move==='dolly'){
const dir=nrm(sub(P.eye,P.center)),d0=len(sub(P.eye,P.center)),d1=m.dist!=null?m.dist:d0*(m.factor==null?1:m.factor);
Q.eye=add(P.center,mul(dir,d1));
if(m.vertigo)Q.fov=2*Math.atan(Math.tan(P.fov / 2)*d0 / d1);
}else if(m.move==='crane'){
const rise=m.rise||0,fol=m.follow==null?0:m.follow;
Q.eye=add(P.eye,[0,-rise,0]);Q.center=add(P.center,[0,-rise*fol,0]);
}else if(m.move==='lookat'){
target=resolvePt(m.target,scene);if(!target)throw new Error('gl-camera-rig: lookat ' + m.id + ' has no target');
Q.center=target.slice();
if(m.dist)Q.eye=add(target,mul(nrm(sub(P.eye,target)),m.dist));
}else if(m.move==='focus'){
const pt=m.target!=null?resolvePt(m.target,scene):null;target=pt;
Q.focus=pt?Math.max(1,depthOf(pt,P)):m.dist!=null?m.dist:P.focus;
}else if(m.move==='key'||m.move==='cut'){
if(m.eye)Q.eye=m.eye.slice();if(m.center)Q.center=m.center.slice();if(m.up)Q.up=m.up.slice();
}else throw new Error('gl-camera-rig: unknown move ' + m.move);
if(m.fov!=null&&!m.vertigo)Q.fov=m.fov*D2R;
if(m.zoom!=null)Q.zoom=m.zoom;
if(m.aperture!=null)Q.aperture=m.aperture;
if(m.move!=='focus'){
const f=m.focus;
if(f==null||f==='center')Q.focus=len(sub(Q.eye,Q.center));
else if(typeof f==='number')Q.focus=f;
else if(f!=='hold'){const pt=resolvePt(f,scene);if(pt)Q.focus=Math.max(1,depthOf(pt,Q));}
}
return{Q,orbit,target};
}
function compile(script,scene){
const s0=script.start||{},eye=(s0.eye||[0,0,800]).slice(),center=(s0.center||[0,0,0]).slice();
const P0={eye,center,up:(s0.up||[0,1,0]).slice(),fov:(s0.fov==null?45:s0.fov)*D2R,zoom:s0.zoom==null?1:s0.zoom,
aperture:s0.aperture==null?0:s0.aperture,focus:typeof s0.focus==='number'?s0.focus:len(sub(eye,center))};
if(s0.focusAt!=null){const pt=resolvePt(s0.focusAt,scene);if(pt)P0.focus=Math.max(1,depthOf(pt,P0));}
const moves=(script.moves||[]).map((m,i)=>Object.assign({id:m.move +(i + 1),ease:'inout'},m))
.map((m)=>Object.assign(m,{t1:m.move==='cut'?m.t0:m.t1})).sort((a,b)=>a.t0 - b.t0);
const ids=new Set();
moves.forEach((m,i)=>{
if(ids.has(m.id))throw new Error('gl-camera-rig: move id ' + m.id + ' twice');ids.add(m.id);
if(!(m.t1>=m.t0))throw new Error('gl-camera-rig: move ' + m.id + ' ends before it starts');
if(i&&m.t0<moves[i - 1].t1 - 1e-9)throw new Error('gl-camera-rig: move ' + m.id + ' overlaps ' + moves[i - 1].id);
});
const keys=[Object.assign({t:0,move:'start',id:'start'},P0)];
let P=P0;
for(const m of moves){
const{Q,orbit,target}=endPose(P,m,scene);
keys.push(Object.assign({t:m.t1,t0:m.t0,move:m.move,id:m.id,ease:m.ease,scheme:SCHEME[m.move],orbit,target},Q));
P=Q;
}
return Object.freeze({script,proj:script.proj||'persp',dur:script.dur||12,near:script.near||10,far:script.far||9000,moves,keys});
}
function at(rig,t){
const K=rig.keys,M=rig.moves;let i=-1;
for(let j=0;j<M.length;j++){if(t>=M[j].t0)i=j;else break;}
const meta=(pose,k,u,s)=>Object.assign(pose,{proj:rig.proj,i:k,move:K[k + 1]?K[k + 1].move:'hold',id:K[k + 1]?K[k + 1].id:'',u,s,active:u>0&&u<1});
const copy=(k)=>{const q=K[k];return{eye:q.eye.slice(),center:q.center.slice(),up:q.up.slice(),fov:q.fov,zoom:q.zoom,focus:q.focus,aperture:q.aperture};};
if(i<0)return meta(copy(0),-1,0,0);
const m=M[i],a=K[i],b=K[i + 1];
if(t>=m.t1)return meta(copy(i + 1),i,1,1);
const u=(t - m.t0)/(m.t1 - m.t0),s=easeOf(m.ease)(u);
const pose=b.scheme==='orbit'?orbitPose(a,b,s,b.orbit):b.scheme==='track'?trackPose(a,b,s):b.scheme==='cut'?copy(i + 1):slerpPose(a,b,s);
return meta(pose,i,u,s);
}
function apply(p,cam,pose,rig){
const W=p.width,H=p.height;
cam.camera(pose.eye[0],pose.eye[1],pose.eye[2],pose.center[0],pose.center[1],pose.center[2],pose.up[0],pose.up[1],pose.up[2]);
if(rig.proj==='ortho'){const z=pose.zoom||1;cam.ortho(-W / 2 / z,W / 2 / z,-H / 2 / z,H / 2 / z,0,rig.far);}
else cam.perspective(pose.fov,W / H,rig.near,rig.far);
return cam;
}
function worldToScreen(pose,pt,W,H){
const B=basis(pose.eye,pose.center,pose.up),v=sub(pt,pose.eye);
const cx=dot(v,B.x),cy=dot(v,B.y),depth=-dot(v,B.z);
let x,y;
if(pose.proj==='ortho'){const z=pose.zoom||1;x=W / 2 + cx*z;y=H / 2 + cy*z;}
else{const f=1 / Math.tan(pose.fov / 2);x=W / 2*(1 +(f*H / W)*cx / depth);y=H / 2*(1 + f*cy / depth);}
return{x,y,depth,on:depth>0&&x>=0&&x<=W&&y>=0&&y<=H};
}
function pxPerUnit(pose,depth,H){return pose.proj==='ortho'?pose.zoom||1:(H / 2)/(Math.tan(pose.fov / 2)*Math.max(depth,1e-6));}
function dof(pose,rig){
const n=rig.near,f=rig.far,z=pose.focus;
const buf=rig.proj==='ortho'?clamp(z / f):clamp((f /(f - n))*(1 - n / z));
return{focus:z,aperture:pose.aperture,near:n,far:f,focusDepth01:buf,proj:rig.proj};
}
function sample(rig,n){const out=[];for(let k=0;k<=n;k++){const t=rig.dur*k / n,q=at(rig,t);out.push({t,eye:q.eye,center:q.center});}return out;}
const cap=(s)=>String(s).replace(/[^A-Za-z0-9]+(.)?/g,(_,c)=>(c?c.toUpperCase():'')).replace(/^./,(c)=>c.toUpperCase());
const XYZ=['X','Y','Z'],COORD=[-6000,6000];
const SPEC={
t0:[null,0.1,'start (s)'],t1:[null,0.1,'end (s)'],ease:[EASE_NAMES,null,'ease (arsenal/core/timeline curves)'],
az:[[-720,720],5,'degrees swept round the centre'],el:[[-10,89],1,'end elevation (deg above the centre)'],r:[[0.2,5],0.05,'end radius as a factor of the start'],
dist:[[0,6000],10,'distance to the centre / target (world units; lookat 0 = pan from the eye)'],factor:[[0.05,20],0.05,'distance factor'],
vertigo:[[false,true],null,'dolly zoom: fov compensates so the subject keeps its size'],
rise:[[-3000,3000],10,'eye rise (world units, + = up)'],follow:[[0,1],0.05,'how much of the rise the aim follows (0 = keep the subject)'],
target:[null,1,'data index the camera aims or focuses at'],focusAt:[null,1,'data index the start focus sits on'],aperture:[[0,1],0.05,'focus blur strength (0 = all sharp)'],
focus:[[1,8000],10,'focus distance (world units)'],fov:[[5,120],1,'vertical field of view (deg)'],zoom:[[0.1,10],0.05,'ortho magnification'],
eye:[COORD,10,'eye'],center:[COORD,10,'aim point'],
};
function rows(script,scene,opts){
const pre=(opts&&opts.prefix)||'cam',dur=script.dur||12,N=scene&&scene.points?scene.points.length:0,out=[];
const row=(obj,key,idx,base,label)=>{
const sp=SPEC[key];if(!sp)return;
let v=idx==null?obj[key]:obj[key][idx];
const name=pre + cap(base)+ cap(key)+(idx==null?'':XYZ[idx]);
const r={name,obj,key,idx,step:sp[1],what:label + ': ' + sp[2]+(idx==null?'':' ' + 'xyz'[idx])};
if(key==='t0'||key==='t1')r.range=[0,dur];
else if(key==='target'||key==='focusAt'){const i=resolveIdx(v,scene);if(i<0)return;v=i;r.range=[0,Math.max(0,N - 1)];r.resolved=true;}
else if(key==='focus'&&typeof v!=='number')return;
else if(sp[0]&&typeof sp[0][0]==='number')r.range=sp[0].slice();else r.options=sp[0].slice();
if(r.range){if(typeof v!=='number')return;r.range=[Math.min(r.range[0],v),Math.max(r.range[1],v)];}
r.value=v;out.push(r);
};
const s0=script.start||{};
for(const k of['eye','center'])if(s0[k])for(let j=0;j<3;j++)row(s0,k,j,'start','start pose');
for(const k of['fov','zoom','aperture','focus'])if(s0[k]!=null)row(s0,k,null,'start','start pose');
if(s0.focusAt!=null)row(s0,'focusAt',null,'start','start pose');
(script.moves||[]).forEach((m,i)=>{
const id=m.id||m.move +(i + 1),lab=id + ' (' + m.move + ')';
for(const k of['t0','t1','ease'])if(m[k]!=null||k==='ease'){if(m.move==='cut'&&k==='t1')continue;if(m[k]==null)m[k]='inout';row(m,k,null,id,lab);}
for(const k in m)if(!['id','move','t0','t1','ease','up','around'].includes(k)){
if(Array.isArray(m[k])&&(k==='eye'||k==='center'))for(let j=0;j<3;j++)row(m,k,j,id,lab);
else if(!Array.isArray(m[k]))row(m,k,null,id,lab);
}
});
return out;
}
const clone=(o)=>JSON.parse(JSON.stringify(o));
function toKnobs(script,scene,opts){
const R=rows(clone(script),scene,opts),knobs={},knobs_doc=[];
for(const r of R){
knobs[r.name]=r.value;
const d={name:r.name};if(r.range)d.range=r.range;else d.options=r.options;
if(r.step!=null)d.step=r.step;d.what='camera rig · ' + r.what;knobs_doc.push(d);
}
return{knobs,knobs_doc};
}
function fromKnobs(script,knobs,scene,opts){
const out=clone(script);if(!knobs)return out;
for(const r of rows(out,scene,opts)){
let v=typeof knobs==='function'?knobs(r.name,r.value):knobs[r.name];
if(v===undefined)continue;
if(r.range){if(typeof v!=='number'||!isFinite(v))continue;v=clamp(v,r.range[0],r.range[1]);if(r.key==='target'||r.key==='focusAt')v=Math.round(v);}
else if(!r.options.includes(v))continue;
if(r.idx==null)r.obj[r.key]=v;else r.obj[r.key][r.idx]=v;
}
return out;
}
const rig={compile,at,apply,worldToScreen,pxPerUnit,dof,sample,toKnobs,fromKnobs,rows,basis,slerpPose,eases:EASE_NAMES};
A.patterns['gl-camera-rig']={id:'gl-camera-rig',renderer:'webgl',rig};
})();
/* lib/gl-labels.js sha256 3832b197f432f712 (patched) */
(function(){
const A=(window.ARSENAL=window.ARSENAL||{patterns:{},structures:{},materials:{},brands:{}});
function mulberry32(a){return function(){a|=0;a=(a + 0x6D2B79F5)|0;let t=Math.imul(a ^(a>>>15),1|a);t=(t + Math.imul(t ^(t>>>7),61|t))^ t;return((t ^(t>>>14))>>>0)/ 4294967296;};}
const clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x));
const smooth=(x)=>{x=clamp(x);return x*x*x*(x*(x*6 - 15)+ 10);};
const lerp=(a,b,u)=>a +(b - a)*u;
const fmt=(n)=>String(n).replace(/\B(?=(\d{3})+(?!\d))/g,',');
const sub=(a,b)=>[a[0]- b[0],a[1]- b[1],a[2]- b[2]];
const dot=(a,b)=>a[0]*b[0]+ a[1]*b[1]+ a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]- a[2]*b[1],a[2]*b[0]- a[0]*b[2],a[0]*b[1]- a[1]*b[0]];
const nrm=(a)=>{const l=Math.hypot(a[0],a[1],a[2])||1;return[a[0]/ l,a[1]/ l,a[2]/ l];};
const ROLES={
result:{size:28,fam:'disp',color:'accent',data:'must-read',sub:'secondary'},
secondary:{size:14,fam:'mono',color:'ink',data:'secondary',sub:'chrome'},
chrome:{size:12,fam:'mono',color:'muted',data:'chrome',sub:'chrome'},
};
const DIRS=[[1,-1],[-1,-1],[1,1],[-1,1],[1,0],[-1,0],[0,-1],[0,1]];
const MULT=[1,2.2,3.4];
const DEF={w:960,h:540,fps:30,hold:8,window:0,leader:20,margin:14,pad:3,dot:3.5,occlusion:true,avoidDots:true,
reserve:[],occluders:null,near:1,maxShown:Infinity,callout:null,measure:null};
function camOf(camera,t){
let c=typeof camera==='function'?camera(t):camera;
if(c&&c.eyeX!=null)c={eye:[c.eyeX,c.eyeY,c.eyeZ],look:[c.centerX,c.centerY,c.centerZ],up:[c.upX,c.upY,c.upZ],fov:c.cameraFOV,aspect:c.aspectRatio};
return c;
}
function basis(c){
const z=nrm(sub(c.eye,c.look)),x=nrm(cross(c.up||[0,1,0],z)),y=cross(z,x);
return{z,x,y};
}
function projector(c,W,H){
const B=basis(c),asp=c.aspect||W / H;
if(c.ortho!=null){
const s=c.ortho||1;
return(P)=>{const r=sub(P,c.eye),xc=dot(r,B.x),yc=dot(r,B.y),d=-dot(r,B.z);return[(1 + xc /(W / 2*s))/ 2*W,(1 + yc /(H / 2*s))/ 2*H,d];};
}
const f=1 / Math.tan((c.fov||0.8)/ 2);
return(P)=>{const r=sub(P,c.eye),xc=dot(r,B.x),yc=dot(r,B.y),d=-dot(r,B.z);return d<=1e-6?[NaN,NaN,d]:[(1 + f / asp*xc / d)/ 2*W,(1 + f*yc / d)/ 2*H,d];};
}
function occludedBy(c,B,P,occ){
const o=c.ortho!=null?(()=>{const d=-dot(sub(P,c.eye),B.z);return[P[0]+ B.z[0]*d,P[1]+ B.z[1]*d,P[2]+ B.z[2]*d];})():c.eye;
const dv=sub(P,o);
for(let i=0;i<occ.length;i++){
const b=occ[i];let t0=0,t1=1 - 1e-3,hit=true;
for(let a=0;a<3;a++){
if(Math.abs(dv[a])<1e-12){if(o[a]<b.min[a]||o[a]>b.max[a]){hit=false;break;}continue;}
let u0=(b.min[a]- o[a])/ dv[a],u1=(b.max[a]- o[a])/ dv[a];if(u0>u1){const s=u0;u0=u1;u1=s;}
if(u0>t0)t0=u0;if(u1<t1)t1=u1;if(t0>t1){hit=false;break;}
}
if(hit)return i;
}
return -1;
}
function styleOf(a,o){
const r=ROLES[a.role]||ROLES.secondary,rs=ROLES[r.sub];
const size=Math.max(r.size,a.size||0),fam=a.fam||r.fam;
const m=o.measure||((s,z,f)=>s.length*z*(f==='disp'?0.46:0.6));
const w1=m(String(a.text),size,fam),w2=a.sub?m(String(a.sub),rs.size,rs.fam):0;
const cap=size*(fam==='disp'?0.74:0.72),h2=a.sub?rs.size*1.25:0,p=o.pad;
return{size,fam,color:a.color||r.color,dataRole:r.data,subSize:rs.size,subFam:rs.fam,subDataRole:rs.data,
w:Math.max(w1,w2)+ 2*p,h:cap + h2 + 2*p,cap,p};
}
function candBox(ax,ay,s,c,L){
const d=DIRS[c%8],m=MULT[Math.floor(c / 8)],k=d[0]&&d[1]?0.72:1,ex=ax + d[0]*L*m*k,ey=ay + d[1]*L*m*k;
const x0=d[0]>0?ex:d[0]<0?ex - s.w:ex - s.w / 2,y0=d[1]>0?ey:d[1]<0?ey - s.h:ey - s.h / 2;
return{x0,y0,x1:x0 + s.w,y1:y0 + s.h,ex,ey};
}
const hit=(a,b)=>a.x0<b.x1&&a.x1>b.x0&&a.y0<b.y1&&a.y1>b.y0;
const free=(b,occ)=>{for(let i=0;i<occ.length;i++)if(hit(b,occ[i]))return false;return true;};
function segHit(x0,y0,x1,y1,r){
let u0=0,u1=1;const dx=x1 - x0,dy=y1 - y0;
for(const[pp,q]of[[-dx,x0 - r.x0],[dx,r.x1 - x0],[-dy,y0 - r.y0],[dy,r.y1 - y0]]){
if(Math.abs(pp)<1e-12){if(q<0)return false;continue;}
const u=q / pp;if(pp<0){if(u>u1)return false;if(u>u0)u0=u;}else{if(u<u0)return false;if(u<u1)u1=u;}
}
return u0<u1;
}
const leadFree=(ax,ay,b,occ,from,leads)=>{
for(let i=from;i<occ.length;i++)if(segHit(ax,ay,b.ex,b.ey,occ[i]))return false;
for(let i=0;i<leads.length;i++)if(segHit(leads[i][0],leads[i][1],leads[i][2],leads[i][3],b))return false;
return true;
};
function frame(t,camera,anchors,o){
const c=camOf(camera,t),W=o.w,H=o.h,pr=projector(c,W,H),B=basis(c);
const list=typeof anchors==='function'?anchors(t):anchors,n=list.length,P=new Array(n);
for(let i=0;i<n;i++){
const a=list[i],q=pr([a.x,a.y,a.z]);
const off=!(q[2]>o.near)||!(q[0]>=0&&q[0]<=W&&q[1]>=0&&q[1]<=H);
const oc=!off&&o.occlusion&&o.occluders&&o.occluders.length?occludedBy(c,B,[a.x,a.y,a.z],o.occluders):-1;
P[i]={i,a,x:q[0],y:q[1],depth:q[2],off,occ:oc>=0,occBy:oc};
}
return{t,c,P};
}
function calloutAt(t,o){
const S=o.callout&&o.callout.schedule;if(!S||!S.length)return null;
let j=-1;for(let i=0;i<S.length;i++)if(S[i].t<=t + 1e-9)j=i;
if(j<0)return null;
const e=S[j];return e.id==null?null:{seg:j,t0:e.t,id:e.id,text:e.text,sub:e.sub,role:e.role||'result',size:e.size||o.callout.size||32,color:e.color||o.callout.color};
}
function makeOcc(o){
const M=o.margin,occ=[{x0:-1e5,y0:-1e5,x1:1e5,y1:M},{x0:-1e5,y0:o.h - M,x1:1e5,y1:1e5},{x0:-1e5,y0:-1e5,x1:M,y1:1e5},{x0:o.w - M,y0:-1e5,x1:1e5,y1:1e5}];
for(const r of o.reserve||[])occ.push({x0:r[0],y0:r[1],x1:r[2],y1:r[3]});
return occ;
}
const dotBox=(x,y,r)=>({x0:x - r,y0:y - r,x1:x + r,y1:y + r});
function greedy(F,order,o,styles,prefs,force,L,extraOcc){
const occ=makeOcc(o).concat(extraOcc||[]),res=new Map(),r=o.dot + 1,leads=[],NM=4 +(o.reserve||[]).length;
let shown=0;
for(const i of order){
const q=F.P[i],s=styles[i];
if(shown>=o.maxShown){res.set(i,{placed:false,why:'cap'});continue;}
const db=dotBox(q.x,q.y,r);
if(!free(db,occ)&&!force(i)){res.set(i,{placed:false,why:'dot'});continue;}
let got=-1,bx=null;
for(const c of prefs(i)){const b=candBox(q.x,q.y,s,c,L(i));if(free(b,occ)&&!hit(b,db)&&leadFree(q.x,q.y,b,occ,NM,leads)){got=c;bx=b;break;}}
let overlap=false;
if(got<0){if(!force(i)){res.set(i,{placed:false,why:'blocked'});continue;}got=prefs(i)[0];bx=candBox(q.x,q.y,s,got,L(i));overlap=true;}
occ.push(bx);if(o.avoidDots)occ.push(db);leads.push([q.x,q.y,bx.ex,bx.ey]);shown++;
res.set(i,{placed:true,c:got,box:bx,overlap});
}
return res;
}
const PREF=Array.from({length:DIRS.length*MULT.length},(_,i)=>i);
function orderOf(F,idx){
return idx.slice().sort((a,b)=>(F.P[b].a.priority||0)-(F.P[a].a.priority||0)||a - b);
}
function rawSample(k,camera,anchors,o,styles,coStyle,prev){
const t=k / o.fps,F=frame(t,camera,anchors,o),n=F.P.length,co=calloutAt(t,o);
const coIdx=co?F.P.findIndex((q)=>q.a.id===co.id):-1;
let extra=[],coRes=null;
if(coIdx>=0&&!F.P[coIdx].off){
const st=coStyle(co,F.P[coIdx].a),sty=styles.slice();sty[coIdx]=st;
const pc=prev&&prev.co&&prev.co.seg===co.seg?prev.co.c:-1;
const r=greedy(F,[coIdx],o,sty,()=>stick(pc),()=>true,()=>(o.callout.leader||52),[]).get(coIdx);
coRes={ok:true,c:r.c,seg:co.seg};extra=[r.box,dotBox(F.P[coIdx].x,F.P[coIdx].y,o.dot + 1)];
}
const idx=[];for(let i=0;i<n;i++)if(i!==coIdx&&!F.P[i].off&&!F.P[i].occ)idx.push(i);
const g=greedy(F,orderOf(F,idx),o,styles,(i)=>stick(prev?prev.cs[i]:-1),()=>false,()=>o.leader,extra);
const ok=new Uint8Array(n),cs=new Int8Array(n).fill(-1),why=new Array(n);
for(let i=0;i<n;i++){const q=F.P[i];why[i]=i===coIdx?'callout':q.off?'off':q.occ?'occluded':'blocked';}
for(const[i,r]of g){if(r.placed){ok[i]=1;cs[i]=r.c;why[i]='shown';}else why[i]=r.why==='dot'?'blocked':r.why;}
return{ok,cs,why,co:coRes};
}
function schmitt(i,k0,hold,get){
let k=k0,v=get(k).ok[i];
for(;;){
let len=0;while(k>=0&&get(k).ok[i]===v){len++;k--;}
if(len>=hold||k<0)return v;
v=get(k).ok[i];
}
}
const STICK=PREF.map((c)=>[c].concat(PREF.filter((x)=>x!==c)));
const stick=(c)=>(c>=0?STICK[c]:PREF);
function debounce(vals,hold,reachesStart,fallback){
let i=0;const n=vals.length;
while(i<n){
let j=i;while(j<n&&vals[j]===vals[i])j++;
if(j - i>=hold||(j===n&&reachesStart))return vals[i];
i=j;
}
return fallback;
}
const MEMO=new WeakMap();
function memoFor(anchors,camera,o){
let m1=MEMO.get(anchors);if(!m1)MEMO.set(anchors,(m1=new WeakMap()));
const ck=typeof camera==='object'||typeof camera==='function'?camera:null;
let m2=ck?m1.get(ck):null;if(!m2){m2=new Map();if(ck)m1.set(ck,m2);}
const key=JSON.stringify([o.w,o.h,o.fps,o.leader,o.margin,o.pad,o.dot,o.occlusion,o.avoidDots,o.reserve,o.near,o.maxShown,o.callout,o.sticky,o.occluders?o.occluders.length:0,o.measureKey||'']);
let m3=m2.get(key);if(!m3){m3=new Map();m2.set(key,m3);}
if(m3.size>40000)m3.clear();
return m3;
}
function solve(t,camera,anchors,opts){
const o=Object.assign({},DEF,opts||{}),list0=typeof anchors==='function'?anchors(t):anchors,n=list0.length;
const styles=list0.map((a)=>styleOf(a,o));
const coStyle=(co,a)=>styleOf({text:co.text!=null?co.text:a.text,sub:co.sub!=null?co.sub:a.sub,role:co.role,size:co.size,color:co.color},o);
const hold=Math.max(0,o.hold|0),M=o.window||Math.max(1,4*hold),memo=memoFor(anchors,camera,o),chain=o.sticky!=='window';
const k0=Math.floor(t*o.fps + 1e-6),co=calloutAt(t,o);
const raw=(k)=>{
let r=memo.get(k);if(r)return r;
if(!chain){r=rawSample(k,camera,anchors,o,styles,coStyle,null);memo.set(k,r);return r;}
let j=k;while(j>0&&!memo.has(j - 1))j--;
for(let m=j;m<=k;m++)memo.set(m,rawSample(m,camera,anchors,o,styles,coStyle,m>0?memo.get(m - 1):null));
return memo.get(k);
};
const ks=[];for(let k=k0;k>k0 - M&&k>=0;k--)ks.push(k);
const reachesStart=ks[ks.length - 1]===0;
const R=hold?ks.map(raw):[raw(k0)];
const vis=new Uint8Array(n),cand=new Int8Array(n).fill(0);
for(let i=0;i<n;i++){
if(chain&&hold){vis[i]=schmitt(i,k0,hold,(k)=>memo.get(k)||raw(k));}
else{const v=R.map((r)=>r.ok[i]);vis[i]=hold?debounce(v,hold,reachesStart,0):v[0];}
const cs=R.map((r)=>r.cs[i]).filter((c)=>c>=0);cand[i]=cs.length?(chain||!hold?cs[0]:debounce(cs,hold,true,cs[0])):0;
}
const F=frame(t,camera,anchors,o),out=[],extra=[];
let coIdx=-1;
if(co){
coIdx=F.P.findIndex((q)=>q.a.id===co.id);
if(coIdx>=0&&!F.P[coIdx].off){
const kc=Math.ceil(co.t0*o.fps - 1e-6),seg=R.filter((r,j)=>ks[j]>=kc&&r.co&&r.co.seg===co.seg).map((r)=>r.co.c);
const c0=seg.length?seg[0]:0,st=coStyle(co,F.P[coIdx].a),sty=styles.slice();sty[coIdx]=st;
const r=greedy(F,[coIdx],o,sty,()=>[c0].concat(PREF.filter((c)=>c!==c0)),()=>true,()=>(o.callout.leader||52),[]).get(coIdx);
extra.push(r.box,dotBox(F.P[coIdx].x,F.P[coIdx].y,o.dot + 1));
out.push(place(F.P[coIdx],st,r,true,co));
}else coIdx=-1;
}
const inc=[];for(let i=0;i<n;i++)if(i!==coIdx&&vis[i]&&!F.P[i].off&&(!co||F.P[i].a.id!==co.id))inc.push(i);
const g=greedy(F,orderOf(F,inc),o,styles,(i)=>[cand[i]].concat(PREF.filter((c)=>c!==cand[i])),()=>true,()=>o.leader,extra);
const placed=[];for(const i of orderOf(F,inc)){const r=g.get(i);if(r&&r.placed)placed.push(place(F.P[i],styles[i],r,false,null));}
out.splice(0,0,...placed.reverse());
const last=raw(k0),cnt={total:n,onscreen:0,occluded:0,shown:out.length,crowded:0,overlap:out.filter((q)=>q.overlap).length,callout:co&&coIdx>=0?co.id:null};
for(let i=0;i<n;i++){const q=F.P[i];if(q.off)continue;cnt.onscreen++;if(q.occ)cnt.occluded++;}
cnt.crowded=Math.max(0,cnt.onscreen - cnt.occluded - cnt.shown);
return{t,placements:out,counts:cnt,why:last.why};
}
function place(q,s,r,isCallout,co){
const a=q.a,b=r.box,d=DIRS[r.c%8],right=d[0]<0;
const text=isCallout&&co.text!=null?co.text:a.text,sb=isCallout&&co.sub!=null?co.sub:a.sub;
const tx=right?b.x1 - s.p:d[0]===0?(b.x0 + b.x1)/ 2:b.x0 + s.p,align=right?'right':d[0]===0?'center':'left';
return{id:a.id,text:String(text),sub:sb!=null?String(sb):null,role:isCallout?co.role:(a.role||'secondary'),
dataRole:s.dataRole,subDataRole:s.subDataRole,size:s.size,fam:s.fam,subSize:s.subSize,subFam:s.subFam,color:s.color,
ax:q.x,ay:q.y,depth:q.depth,occluded:q.occ,box:[b.x0,b.y0,b.x1,b.y1],lead:[q.x,q.y,b.ex,b.ey],cand:r.c,
tx,ty:b.y0 + s.p + s.cap,sy:b.y0 + s.p + s.cap + s.subSize*1.15,align,overlap:!!r.overlap,callout:!!isCallout};
}
A.patterns['gl-labels']={id:'gl-labels',renderer:'webgl',ROLES,solve,project:(cam,W,H)=>projector(cam,W,H)};
})();
